FROM asciidoctor/docker-asciidoctor:latest

RUN apk add nodejs npm rsync openssh
RUN npm update
RUN npm install -g antora \
    @antora/cli \
    @antora/site-generator \
    @antora/pdf-extension \
    @antora/lunr-extension \
    antora-shiki-extension \
    @asciidoctor/tabs
RUN gem install bundle

