// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: metarr/v1/agents.proto

package metarrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentConfig mirrors internal/shared/appconfig.AgentConfig — the operator's
// side of one agent's configuration.
type AgentConfig struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Slug          string                   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	DisplayName   string                   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Mappings      []*AgentDirectoryMapping `protobuf:"bytes,3,rep,name=mappings,proto3" json:"mappings,omitempty"`
	LogLevel      string                   `protobuf:"bytes,4,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_metarr_v1_agents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{0}
}

func (x *AgentConfig) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *AgentConfig) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AgentConfig) GetMappings() []*AgentDirectoryMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

func (x *AgentConfig) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

// AgentDirectoryMapping mirrors internal/shared/appconfig.AgentDirectoryMapping.
type AgentDirectoryMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScannerSlug   string                 `protobuf:"bytes,1,opt,name=scanner_slug,json=scannerSlug,proto3" json:"scanner_slug,omitempty"`
	AgentPath     string                 `protobuf:"bytes,2,opt,name=agent_path,json=agentPath,proto3" json:"agent_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDirectoryMapping) Reset() {
	*x = AgentDirectoryMapping{}
	mi := &file_metarr_v1_agents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDirectoryMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDirectoryMapping) ProtoMessage() {}

func (x *AgentDirectoryMapping) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDirectoryMapping.ProtoReflect.Descriptor instead.
func (*AgentDirectoryMapping) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{1}
}

func (x *AgentDirectoryMapping) GetScannerSlug() string {
	if x != nil {
		return x.ScannerSlug
	}
	return ""
}

func (x *AgentDirectoryMapping) GetAgentPath() string {
	if x != nil {
		return x.AgentPath
	}
	return ""
}

// GPUTelemetry mirrors internal/shared/agentproto.GPUTelemetry.
type GPUTelemetry struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UtilizationPercent float64                `protobuf:"fixed64,2,opt,name=utilization_percent,json=utilizationPercent,proto3" json:"utilization_percent,omitempty"`
	MemoryUsedBytes    uint64                 `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes   uint64                 `protobuf:"varint,4,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GPUTelemetry) Reset() {
	*x = GPUTelemetry{}
	mi := &file_metarr_v1_agents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUTelemetry) ProtoMessage() {}

func (x *GPUTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUTelemetry.ProtoReflect.Descriptor instead.
func (*GPUTelemetry) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{2}
}

func (x *GPUTelemetry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUTelemetry) GetUtilizationPercent() float64 {
	if x != nil {
		return x.UtilizationPercent
	}
	return 0
}

func (x *GPUTelemetry) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *GPUTelemetry) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

// AgentTelemetry mirrors internal/shared/agentproto.AgentTelemetry.
type AgentTelemetry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent       float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryUsedBytes  uint64                 `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes uint64                 `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	Gpus             []*GPUTelemetry        `protobuf:"bytes,4,rep,name=gpus,proto3" json:"gpus,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentTelemetry) Reset() {
	*x = AgentTelemetry{}
	mi := &file_metarr_v1_agents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTelemetry) ProtoMessage() {}

func (x *AgentTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTelemetry.ProtoReflect.Descriptor instead.
func (*AgentTelemetry) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{3}
}

func (x *AgentTelemetry) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *AgentTelemetry) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *AgentTelemetry) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *AgentTelemetry) GetGpus() []*GPUTelemetry {
	if x != nil {
		return x.Gpus
	}
	return nil
}

// AgentIdentity mirrors internal/shared/agentproto.AgentIdentity.
type AgentIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Uid           int32                  `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Os            string                 `protobuf:"bytes,7,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,8,opt,name=arch,proto3" json:"arch,omitempty"`
	Version       string                 `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`
	Started       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=started,proto3" json:"started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentIdentity) Reset() {
	*x = AgentIdentity{}
	mi := &file_metarr_v1_agents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIdentity) ProtoMessage() {}

func (x *AgentIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIdentity.ProtoReflect.Descriptor instead.
func (*AgentIdentity) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{4}
}

func (x *AgentIdentity) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *AgentIdentity) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AgentIdentity) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentIdentity) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AgentIdentity) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AgentIdentity) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AgentIdentity) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentIdentity) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *AgentIdentity) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentIdentity) GetStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.Started
	}
	return nil
}

// AgentMappingView mirrors internal/server/agentregistry.MappingView — one
// library mapping shown in both machines' terms.
type AgentMappingView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScannerSlug   string                 `protobuf:"bytes,1,opt,name=scanner_slug,json=scannerSlug,proto3" json:"scanner_slug,omitempty"`
	ScanType      string                 `protobuf:"bytes,2,opt,name=scan_type,json=scanType,proto3" json:"scan_type,omitempty"`
	ServerPath    string                 `protobuf:"bytes,3,opt,name=server_path,json=serverPath,proto3" json:"server_path,omitempty"`
	AgentPath     string                 `protobuf:"bytes,4,opt,name=agent_path,json=agentPath,proto3" json:"agent_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMappingView) Reset() {
	*x = AgentMappingView{}
	mi := &file_metarr_v1_agents_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMappingView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMappingView) ProtoMessage() {}

func (x *AgentMappingView) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMappingView.ProtoReflect.Descriptor instead.
func (*AgentMappingView) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{5}
}

func (x *AgentMappingView) GetScannerSlug() string {
	if x != nil {
		return x.ScannerSlug
	}
	return ""
}

func (x *AgentMappingView) GetScanType() string {
	if x != nil {
		return x.ScanType
	}
	return ""
}

func (x *AgentMappingView) GetServerPath() string {
	if x != nil {
		return x.ServerPath
	}
	return ""
}

func (x *AgentMappingView) GetAgentPath() string {
	if x != nil {
		return x.AgentPath
	}
	return ""
}

// AgentView mirrors internal/server/agentregistry.AgentView — what List
// returns: configuration merged with live presence.
type AgentView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	Configured    bool                   `protobuf:"varint,4,opt,name=configured,proto3" json:"configured,omitempty"`
	Identity      *AgentIdentity         `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	Telemetry     *AgentTelemetry        `protobuf:"bytes,6,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	ReportedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	Mappings      []*AgentMappingView    `protobuf:"bytes,8,rep,name=mappings,proto3" json:"mappings,omitempty"`
	LogLevel      string                 `protobuf:"bytes,9,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentView) Reset() {
	*x = AgentView{}
	mi := &file_metarr_v1_agents_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentView) ProtoMessage() {}

func (x *AgentView) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentView.ProtoReflect.Descriptor instead.
func (*AgentView) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{6}
}

func (x *AgentView) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *AgentView) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AgentView) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *AgentView) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *AgentView) GetIdentity() *AgentIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *AgentView) GetTelemetry() *AgentTelemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *AgentView) GetReportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportedAt
	}
	return nil
}

func (x *AgentView) GetMappings() []*AgentMappingView {
	if x != nil {
		return x.Mappings
	}
	return nil
}

func (x *AgentView) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

type AgentServiceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServiceListRequest) Reset() {
	*x = AgentServiceListRequest{}
	mi := &file_metarr_v1_agents_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServiceListRequest) ProtoMessage() {}

func (x *AgentServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServiceListRequest.ProtoReflect.Descriptor instead.
func (*AgentServiceListRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{7}
}

type AgentServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentView           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServiceListResponse) Reset() {
	*x = AgentServiceListResponse{}
	mi := &file_metarr_v1_agents_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServiceListResponse) ProtoMessage() {}

func (x *AgentServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServiceListResponse.ProtoReflect.Descriptor instead.
func (*AgentServiceListResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{8}
}

func (x *AgentServiceListResponse) GetAgents() []*AgentView {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentServiceUpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentConfig           `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServiceUpsertRequest) Reset() {
	*x = AgentServiceUpsertRequest{}
	mi := &file_metarr_v1_agents_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServiceUpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServiceUpsertRequest) ProtoMessage() {}

func (x *AgentServiceUpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServiceUpsertRequest.ProtoReflect.Descriptor instead.
func (*AgentServiceUpsertRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{9}
}

func (x *AgentServiceUpsertRequest) GetAgent() *AgentConfig {
	if x != nil {
		return x.Agent
	}
	return nil
}

type AgentServiceDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServiceDeleteRequest) Reset() {
	*x = AgentServiceDeleteRequest{}
	mi := &file_metarr_v1_agents_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServiceDeleteRequest) ProtoMessage() {}

func (x *AgentServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*AgentServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{10}
}

func (x *AgentServiceDeleteRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type AgentServiceSetLogLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	LogLevel      string                 `protobuf:"bytes,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServiceSetLogLevelRequest) Reset() {
	*x = AgentServiceSetLogLevelRequest{}
	mi := &file_metarr_v1_agents_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServiceSetLogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServiceSetLogLevelRequest) ProtoMessage() {}

func (x *AgentServiceSetLogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServiceSetLogLevelRequest.ProtoReflect.Descriptor instead.
func (*AgentServiceSetLogLevelRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{11}
}

func (x *AgentServiceSetLogLevelRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *AgentServiceSetLogLevelRequest) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

type AgentServiceStreamPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServiceStreamPresenceRequest) Reset() {
	*x = AgentServiceStreamPresenceRequest{}
	mi := &file_metarr_v1_agents_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServiceStreamPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServiceStreamPresenceRequest) ProtoMessage() {}

func (x *AgentServiceStreamPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServiceStreamPresenceRequest.ProtoReflect.Descriptor instead.
func (*AgentServiceStreamPresenceRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{12}
}

type AgentServiceStreamPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentView           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServiceStreamPresenceResponse) Reset() {
	*x = AgentServiceStreamPresenceResponse{}
	mi := &file_metarr_v1_agents_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServiceStreamPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServiceStreamPresenceResponse) ProtoMessage() {}

func (x *AgentServiceStreamPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_agents_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServiceStreamPresenceResponse.ProtoReflect.Descriptor instead.
func (*AgentServiceStreamPresenceResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_agents_proto_rawDescGZIP(), []int{13}
}

func (x *AgentServiceStreamPresenceResponse) GetAgents() []*AgentView {
	if x != nil {
		return x.Agents
	}
	return nil
}

var File_metarr_v1_agents_proto protoreflect.FileDescriptor

const file_metarr_v1_agents_proto_rawDesc = "" +
	"\n" +
	"\x16metarr/v1/agents.proto\x12\tmetarr.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16metarr/v1/common.proto\"\x9f\x01\n" +
	"\vAgentConfig\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12<\n" +
	"\bmappings\x18\x03 \x03(\v2 .metarr.v1.AgentDirectoryMappingR\bmappings\x12\x1b\n" +
	"\tlog_level\x18\x04 \x01(\tR\blogLevel\"Y\n" +
	"\x15AgentDirectoryMapping\x12!\n" +
	"\fscanner_slug\x18\x01 \x01(\tR\vscannerSlug\x12\x1d\n" +
	"\n" +
	"agent_path\x18\x02 \x01(\tR\tagentPath\"\xad\x01\n" +
	"\fGPUTelemetry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x13utilization_percent\x18\x02 \x01(\x01R\x12utilizationPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x04 \x01(\x04R\x10memoryTotalBytes\"\xb8\x01\n" +
	"\x0eAgentTelemetry\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x04R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x04R\x10memoryTotalBytes\x12+\n" +
	"\x04gpus\x18\x04 \x03(\v2\x17.metarr.v1.GPUTelemetryR\x04gpus\"\x92\x02\n" +
	"\rAgentIdentity\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\x05R\x03uid\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x0e\n" +
	"\x02os\x18\a \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\b \x01(\tR\x04arch\x12\x18\n" +
	"\aversion\x18\t \x01(\tR\aversion\x124\n" +
	"\astarted\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\astarted\"\x92\x01\n" +
	"\x10AgentMappingView\x12!\n" +
	"\fscanner_slug\x18\x01 \x01(\tR\vscannerSlug\x12\x1b\n" +
	"\tscan_type\x18\x02 \x01(\tR\bscanType\x12\x1f\n" +
	"\vserver_path\x18\x03 \x01(\tR\n" +
	"serverPath\x12\x1d\n" +
	"\n" +
	"agent_path\x18\x04 \x01(\tR\tagentPath\"\xfc\x02\n" +
	"\tAgentView\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x12\x1e\n" +
	"\n" +
	"configured\x18\x04 \x01(\bR\n" +
	"configured\x124\n" +
	"\bidentity\x18\x05 \x01(\v2\x18.metarr.v1.AgentIdentityR\bidentity\x127\n" +
	"\ttelemetry\x18\x06 \x01(\v2\x19.metarr.v1.AgentTelemetryR\ttelemetry\x12;\n" +
	"\vreported_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reportedAt\x127\n" +
	"\bmappings\x18\b \x03(\v2\x1b.metarr.v1.AgentMappingViewR\bmappings\x12\x1b\n" +
	"\tlog_level\x18\t \x01(\tR\blogLevel\"\x19\n" +
	"\x17AgentServiceListRequest\"H\n" +
	"\x18AgentServiceListResponse\x12,\n" +
	"\x06agents\x18\x01 \x03(\v2\x14.metarr.v1.AgentViewR\x06agents\"I\n" +
	"\x19AgentServiceUpsertRequest\x12,\n" +
	"\x05agent\x18\x01 \x01(\v2\x16.metarr.v1.AgentConfigR\x05agent\"/\n" +
	"\x19AgentServiceDeleteRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"Q\n" +
	"\x1eAgentServiceSetLogLevelRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x1b\n" +
	"\tlog_level\x18\x02 \x01(\tR\blogLevel\"#\n" +
	"!AgentServiceStreamPresenceRequest\"R\n" +
	"\"AgentServiceStreamPresenceResponse\x12,\n" +
	"\x06agents\x18\x01 \x03(\v2\x14.metarr.v1.AgentViewR\x06agents2\xc1\x03\n" +
	"\fAgentService\x12O\n" +
	"\x04List\x12\".metarr.v1.AgentServiceListRequest\x1a#.metarr.v1.AgentServiceListResponse\x12o\n" +
	"\x0eStreamPresence\x12,.metarr.v1.AgentServiceStreamPresenceRequest\x1a-.metarr.v1.AgentServiceStreamPresenceResponse0\x01\x12K\n" +
	"\x06Upsert\x12$.metarr.v1.AgentServiceUpsertRequest\x1a\x1b.metarr.v1.AcceptedResponse\x12K\n" +
	"\x06Delete\x12$.metarr.v1.AgentServiceDeleteRequest\x1a\x1b.metarr.v1.AcceptedResponse\x12U\n" +
	"\vSetLogLevel\x12).metarr.v1.AgentServiceSetLogLevelRequest\x1a\x1b.metarr.v1.AcceptedResponseB-Z+Metarr/internal/genproto/metarr/v1;metarrv1b\x06proto3"

var (
	file_metarr_v1_agents_proto_rawDescOnce sync.Once
	file_metarr_v1_agents_proto_rawDescData []byte
)

func file_metarr_v1_agents_proto_rawDescGZIP() []byte {
	file_metarr_v1_agents_proto_rawDescOnce.Do(func() {
		file_metarr_v1_agents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metarr_v1_agents_proto_rawDesc), len(file_metarr_v1_agents_proto_rawDesc)))
	})
	return file_metarr_v1_agents_proto_rawDescData
}

var file_metarr_v1_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_metarr_v1_agents_proto_goTypes = []any{
	(*AgentConfig)(nil),                        // 0: metarr.v1.AgentConfig
	(*AgentDirectoryMapping)(nil),              // 1: metarr.v1.AgentDirectoryMapping
	(*GPUTelemetry)(nil),                       // 2: metarr.v1.GPUTelemetry
	(*AgentTelemetry)(nil),                     // 3: metarr.v1.AgentTelemetry
	(*AgentIdentity)(nil),                      // 4: metarr.v1.AgentIdentity
	(*AgentMappingView)(nil),                   // 5: metarr.v1.AgentMappingView
	(*AgentView)(nil),                          // 6: metarr.v1.AgentView
	(*AgentServiceListRequest)(nil),            // 7: metarr.v1.AgentServiceListRequest
	(*AgentServiceListResponse)(nil),           // 8: metarr.v1.AgentServiceListResponse
	(*AgentServiceUpsertRequest)(nil),          // 9: metarr.v1.AgentServiceUpsertRequest
	(*AgentServiceDeleteRequest)(nil),          // 10: metarr.v1.AgentServiceDeleteRequest
	(*AgentServiceSetLogLevelRequest)(nil),     // 11: metarr.v1.AgentServiceSetLogLevelRequest
	(*AgentServiceStreamPresenceRequest)(nil),  // 12: metarr.v1.AgentServiceStreamPresenceRequest
	(*AgentServiceStreamPresenceResponse)(nil), // 13: metarr.v1.AgentServiceStreamPresenceResponse
	(*timestamppb.Timestamp)(nil),              // 14: google.protobuf.Timestamp
	(*AcceptedResponse)(nil),                   // 15: metarr.v1.AcceptedResponse
}
var file_metarr_v1_agents_proto_depIdxs = []int32{
	1,  // 0: metarr.v1.AgentConfig.mappings:type_name -> metarr.v1.AgentDirectoryMapping
	2,  // 1: metarr.v1.AgentTelemetry.gpus:type_name -> metarr.v1.GPUTelemetry
	14, // 2: metarr.v1.AgentIdentity.started:type_name -> google.protobuf.Timestamp
	4,  // 3: metarr.v1.AgentView.identity:type_name -> metarr.v1.AgentIdentity
	3,  // 4: metarr.v1.AgentView.telemetry:type_name -> metarr.v1.AgentTelemetry
	14, // 5: metarr.v1.AgentView.reported_at:type_name -> google.protobuf.Timestamp
	5,  // 6: metarr.v1.AgentView.mappings:type_name -> metarr.v1.AgentMappingView
	6,  // 7: metarr.v1.AgentServiceListResponse.agents:type_name -> metarr.v1.AgentView
	0,  // 8: metarr.v1.AgentServiceUpsertRequest.agent:type_name -> metarr.v1.AgentConfig
	6,  // 9: metarr.v1.AgentServiceStreamPresenceResponse.agents:type_name -> metarr.v1.AgentView
	7,  // 10: metarr.v1.AgentService.List:input_type -> metarr.v1.AgentServiceListRequest
	12, // 11: metarr.v1.AgentService.StreamPresence:input_type -> metarr.v1.AgentServiceStreamPresenceRequest
	9,  // 12: metarr.v1.AgentService.Upsert:input_type -> metarr.v1.AgentServiceUpsertRequest
	10, // 13: metarr.v1.AgentService.Delete:input_type -> metarr.v1.AgentServiceDeleteRequest
	11, // 14: metarr.v1.AgentService.SetLogLevel:input_type -> metarr.v1.AgentServiceSetLogLevelRequest
	8,  // 15: metarr.v1.AgentService.List:output_type -> metarr.v1.AgentServiceListResponse
	13, // 16: metarr.v1.AgentService.StreamPresence:output_type -> metarr.v1.AgentServiceStreamPresenceResponse
	15, // 17: metarr.v1.AgentService.Upsert:output_type -> metarr.v1.AcceptedResponse
	15, // 18: metarr.v1.AgentService.Delete:output_type -> metarr.v1.AcceptedResponse
	15, // 19: metarr.v1.AgentService.SetLogLevel:output_type -> metarr.v1.AcceptedResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_metarr_v1_agents_proto_init() }
func file_metarr_v1_agents_proto_init() {
	if File_metarr_v1_agents_proto != nil {
		return
	}
	file_metarr_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metarr_v1_agents_proto_rawDesc), len(file_metarr_v1_agents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metarr_v1_agents_proto_goTypes,
		DependencyIndexes: file_metarr_v1_agents_proto_depIdxs,
		MessageInfos:      file_metarr_v1_agents_proto_msgTypes,
	}.Build()
	File_metarr_v1_agents_proto = out.File
	file_metarr_v1_agents_proto_goTypes = nil
	file_metarr_v1_agents_proto_depIdxs = nil
}
