// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: metarr/v1/config.proto

package metarrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AdminUser mirrors internal/shared/appconfig.AdminUser, deliberately
// omitting password_salt/password_hash: those never cross the wire in
// either direction. GetConfig's REST equivalent redacts them to "" before
// responding, and UpdateAdmin is the only write path for a new password.
type AdminUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUser) Reset() {
	*x = AdminUser{}
	mi := &file_metarr_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUser) ProtoMessage() {}

func (x *AdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUser.ProtoReflect.Descriptor instead.
func (*AdminUser) Descriptor() ([]byte, []int) {
	return file_metarr_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *AdminUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AdminUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// APIKeyEntry mirrors internal/shared/appconfig.APIKeyEntry. id is the
// stable handle a scoped edit addresses this entry by; it is empty only
// when a client is proposing a brand new entry that has not been minted
// one yet.
type APIKeyEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyEntry) Reset() {
	*x = APIKeyEntry{}
	mi := &file_metarr_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyEntry) ProtoMessage() {}

func (x *APIKeyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyEntry.ProtoReflect.Descriptor instead.
func (*APIKeyEntry) Descriptor() ([]byte, []int) {
	return file_metarr_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *APIKeyEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKeyEntry) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *APIKeyEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// APIKeysConfig mirrors internal/shared/appconfig.APIKeysConfig.
type APIKeysConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         []*APIKeyEntry         `protobuf:"bytes,1,rep,name=admin,proto3" json:"admin,omitempty"`
	User          []*APIKeyEntry         `protobuf:"bytes,2,rep,name=user,proto3" json:"user,omitempty"`
	Webhook       []*APIKeyEntry         `protobuf:"bytes,3,rep,name=webhook,proto3" json:"webhook,omitempty"`
	ReadOnly      []*APIKeyEntry         `protobuf:"bytes,4,rep,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeysConfig) Reset() {
	*x = APIKeysConfig{}
	mi := &file_metarr_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeysConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeysConfig) ProtoMessage() {}

func (x *APIKeysConfig) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeysConfig.ProtoReflect.Descriptor instead.
func (*APIKeysConfig) Descriptor() ([]byte, []int) {
	return file_metarr_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *APIKeysConfig) GetAdmin() []*APIKeyEntry {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *APIKeysConfig) GetUser() []*APIKeyEntry {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *APIKeysConfig) GetWebhook() []*APIKeyEntry {
	if x != nil {
		return x.Webhook
	}
	return nil
}

func (x *APIKeysConfig) GetReadOnly() []*APIKeyEntry {
	if x != nil {
		return x.ReadOnly
	}
	return nil
}

// InterfacesConfig mirrors internal/shared/appconfig.InterfacesConfig.
type InterfacesConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sonarr        []*SonarrInstance      `protobuf:"bytes,1,rep,name=sonarr,proto3" json:"sonarr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfacesConfig) Reset() {
	*x = InterfacesConfig{}
	mi := &file_metarr_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfacesConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfacesConfig) ProtoMessage() {}

func (x *InterfacesConfig) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfacesConfig.ProtoReflect.Descriptor instead.
func (*InterfacesConfig) Descriptor() ([]byte, []int) {
	return file_metarr_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *InterfacesConfig) GetSonarr() []*SonarrInstance {
	if x != nil {
		return x.Sonarr
	}
	return nil
}

// Config mirrors internal/shared/appconfig.Config field-for-field — the
// whole application configuration document.
type Config struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	ApiKeys          *APIKeysConfig          `protobuf:"bytes,1,opt,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	Admin            *AdminUser              `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	Interfaces       *InterfacesConfig       `protobuf:"bytes,3,opt,name=interfaces,proto3" json:"interfaces,omitempty"`
	DirectoryScanner *DirectoryScannerConfig `protobuf:"bytes,4,opt,name=directory_scanner,json=directoryScanner,proto3" json:"directory_scanner,omitempty"`
	Agents           []*AgentConfig          `protobuf:"bytes,5,rep,name=agents,proto3" json:"agents,omitempty"`
	Logging          *LoggingConfig          `protobuf:"bytes,6,opt,name=logging,proto3" json:"logging,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_metarr_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_metarr_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *Config) GetApiKeys() *APIKeysConfig {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

func (x *Config) GetAdmin() *AdminUser {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *Config) GetInterfaces() *InterfacesConfig {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *Config) GetDirectoryScanner() *DirectoryScannerConfig {
	if x != nil {
		return x.DirectoryScanner
	}
	return nil
}

func (x *Config) GetAgents() []*AgentConfig {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *Config) GetLogging() *LoggingConfig {
	if x != nil {
		return x.Logging
	}
	return nil
}

type ConfigServiceGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigServiceGetRequest) Reset() {
	*x = ConfigServiceGetRequest{}
	mi := &file_metarr_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigServiceGetRequest) ProtoMessage() {}

func (x *ConfigServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigServiceGetRequest.ProtoReflect.Descriptor instead.
func (*ConfigServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_config_proto_rawDescGZIP(), []int{5}
}

type ConfigServiceGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Config                `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigServiceGetResponse) Reset() {
	*x = ConfigServiceGetResponse{}
	mi := &file_metarr_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigServiceGetResponse) ProtoMessage() {}

func (x *ConfigServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigServiceGetResponse.ProtoReflect.Descriptor instead.
func (*ConfigServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigServiceGetResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// ConfigServiceUpdateAdminRequest is a partial update: only the fields set
// are changed. An explicitly-empty string for a set field is rejected
// rather than silently clearing it — see UpdateAdmin's implementation.
type ConfigServiceUpdateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Password      *string                `protobuf:"bytes,3,opt,name=password,proto3,oneof" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigServiceUpdateAdminRequest) Reset() {
	*x = ConfigServiceUpdateAdminRequest{}
	mi := &file_metarr_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigServiceUpdateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigServiceUpdateAdminRequest) ProtoMessage() {}

func (x *ConfigServiceUpdateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigServiceUpdateAdminRequest.ProtoReflect.Descriptor instead.
func (*ConfigServiceUpdateAdminRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigServiceUpdateAdminRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *ConfigServiceUpdateAdminRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *ConfigServiceUpdateAdminRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

// ConfigServiceUpsertApiKeyRequest replaces the entry in group matching
// entry.id. If entry.id is empty, the server mints one and creates a new
// entry — ids are always server-minted, never client-chosen, so a
// non-empty entry.id that doesn't match an existing entry is rejected as
// not found rather than treated as a creation request. group is one of
// "admin", "user", "webhook", "read_only" — the same names
// internal/shared/appconfig.APIKeyGroup uses.
type ConfigServiceUpsertApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Entry         *APIKeyEntry           `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigServiceUpsertApiKeyRequest) Reset() {
	*x = ConfigServiceUpsertApiKeyRequest{}
	mi := &file_metarr_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigServiceUpsertApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigServiceUpsertApiKeyRequest) ProtoMessage() {}

func (x *ConfigServiceUpsertApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigServiceUpsertApiKeyRequest.ProtoReflect.Descriptor instead.
func (*ConfigServiceUpsertApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_config_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigServiceUpsertApiKeyRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigServiceUpsertApiKeyRequest) GetEntry() *APIKeyEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ConfigServiceDeleteApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigServiceDeleteApiKeyRequest) Reset() {
	*x = ConfigServiceDeleteApiKeyRequest{}
	mi := &file_metarr_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigServiceDeleteApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigServiceDeleteApiKeyRequest) ProtoMessage() {}

func (x *ConfigServiceDeleteApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigServiceDeleteApiKeyRequest.ProtoReflect.Descriptor instead.
func (*ConfigServiceDeleteApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigServiceDeleteApiKeyRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ConfigServiceDeleteApiKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_metarr_v1_config_proto protoreflect.FileDescriptor

const file_metarr_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x16metarr/v1/config.proto\x12\tmetarr.v1\x1a\x16metarr/v1/agents.proto\x1a\x16metarr/v1/common.proto\x1a!metarr/v1/directory_scanner.proto\x1a\x17metarr/v1/logging.proto\x1a!metarr/v1/sonarr_interfaces.proto\"=\n" +
	"\tAdminUser\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"J\n" +
	"\vAPIKeyEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xd0\x01\n" +
	"\rAPIKeysConfig\x12,\n" +
	"\x05admin\x18\x01 \x03(\v2\x16.metarr.v1.APIKeyEntryR\x05admin\x12*\n" +
	"\x04user\x18\x02 \x03(\v2\x16.metarr.v1.APIKeyEntryR\x04user\x120\n" +
	"\awebhook\x18\x03 \x03(\v2\x16.metarr.v1.APIKeyEntryR\awebhook\x123\n" +
	"\tread_only\x18\x04 \x03(\v2\x16.metarr.v1.APIKeyEntryR\breadOnly\"E\n" +
	"\x10InterfacesConfig\x121\n" +
	"\x06sonarr\x18\x01 \x03(\v2\x19.metarr.v1.SonarrInstanceR\x06sonarr\"\xda\x02\n" +
	"\x06Config\x123\n" +
	"\bapi_keys\x18\x01 \x01(\v2\x18.metarr.v1.APIKeysConfigR\aapiKeys\x12*\n" +
	"\x05admin\x18\x02 \x01(\v2\x14.metarr.v1.AdminUserR\x05admin\x12;\n" +
	"\n" +
	"interfaces\x18\x03 \x01(\v2\x1b.metarr.v1.InterfacesConfigR\n" +
	"interfaces\x12N\n" +
	"\x11directory_scanner\x18\x04 \x01(\v2!.metarr.v1.DirectoryScannerConfigR\x10directoryScanner\x12.\n" +
	"\x06agents\x18\x05 \x03(\v2\x16.metarr.v1.AgentConfigR\x06agents\x122\n" +
	"\alogging\x18\x06 \x01(\v2\x18.metarr.v1.LoggingConfigR\alogging\"\x19\n" +
	"\x17ConfigServiceGetRequest\"E\n" +
	"\x18ConfigServiceGetResponse\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x11.metarr.v1.ConfigR\x06config\"\xa2\x01\n" +
	"\x1fConfigServiceUpdateAdminRequest\x12\x1f\n" +
	"\busername\x18\x01 \x01(\tH\x00R\busername\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x03 \x01(\tH\x02R\bpassword\x88\x01\x01B\v\n" +
	"\t_usernameB\b\n" +
	"\x06_emailB\v\n" +
	"\t_password\"f\n" +
	" ConfigServiceUpsertApiKeyRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12,\n" +
	"\x05entry\x18\x02 \x01(\v2\x16.metarr.v1.APIKeyEntryR\x05entry\"H\n" +
	" ConfigServiceDeleteApiKeyRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id2\xeb\x02\n" +
	"\rConfigService\x12N\n" +
	"\x03Get\x12\".metarr.v1.ConfigServiceGetRequest\x1a#.metarr.v1.ConfigServiceGetResponse\x12V\n" +
	"\vUpdateAdmin\x12*.metarr.v1.ConfigServiceUpdateAdminRequest\x1a\x1b.metarr.v1.AcceptedResponse\x12X\n" +
	"\fUpsertApiKey\x12+.metarr.v1.ConfigServiceUpsertApiKeyRequest\x1a\x1b.metarr.v1.AcceptedResponse\x12X\n" +
	"\fDeleteApiKey\x12+.metarr.v1.ConfigServiceDeleteApiKeyRequest\x1a\x1b.metarr.v1.AcceptedResponseB-Z+Metarr/internal/genproto/metarr/v1;metarrv1b\x06proto3"

var (
	file_metarr_v1_config_proto_rawDescOnce sync.Once
	file_metarr_v1_config_proto_rawDescData []byte
)

func file_metarr_v1_config_proto_rawDescGZIP() []byte {
	file_metarr_v1_config_proto_rawDescOnce.Do(func() {
		file_metarr_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metarr_v1_config_proto_rawDesc), len(file_metarr_v1_config_proto_rawDesc)))
	})
	return file_metarr_v1_config_proto_rawDescData
}

var file_metarr_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_metarr_v1_config_proto_goTypes = []any{
	(*AdminUser)(nil),                        // 0: metarr.v1.AdminUser
	(*APIKeyEntry)(nil),                      // 1: metarr.v1.APIKeyEntry
	(*APIKeysConfig)(nil),                    // 2: metarr.v1.APIKeysConfig
	(*InterfacesConfig)(nil),                 // 3: metarr.v1.InterfacesConfig
	(*Config)(nil),                           // 4: metarr.v1.Config
	(*ConfigServiceGetRequest)(nil),          // 5: metarr.v1.ConfigServiceGetRequest
	(*ConfigServiceGetResponse)(nil),         // 6: metarr.v1.ConfigServiceGetResponse
	(*ConfigServiceUpdateAdminRequest)(nil),  // 7: metarr.v1.ConfigServiceUpdateAdminRequest
	(*ConfigServiceUpsertApiKeyRequest)(nil), // 8: metarr.v1.ConfigServiceUpsertApiKeyRequest
	(*ConfigServiceDeleteApiKeyRequest)(nil), // 9: metarr.v1.ConfigServiceDeleteApiKeyRequest
	(*SonarrInstance)(nil),                   // 10: metarr.v1.SonarrInstance
	(*DirectoryScannerConfig)(nil),           // 11: metarr.v1.DirectoryScannerConfig
	(*AgentConfig)(nil),                      // 12: metarr.v1.AgentConfig
	(*LoggingConfig)(nil),                    // 13: metarr.v1.LoggingConfig
	(*AcceptedResponse)(nil),                 // 14: metarr.v1.AcceptedResponse
}
var file_metarr_v1_config_proto_depIdxs = []int32{
	1,  // 0: metarr.v1.APIKeysConfig.admin:type_name -> metarr.v1.APIKeyEntry
	1,  // 1: metarr.v1.APIKeysConfig.user:type_name -> metarr.v1.APIKeyEntry
	1,  // 2: metarr.v1.APIKeysConfig.webhook:type_name -> metarr.v1.APIKeyEntry
	1,  // 3: metarr.v1.APIKeysConfig.read_only:type_name -> metarr.v1.APIKeyEntry
	10, // 4: metarr.v1.InterfacesConfig.sonarr:type_name -> metarr.v1.SonarrInstance
	2,  // 5: metarr.v1.Config.api_keys:type_name -> metarr.v1.APIKeysConfig
	0,  // 6: metarr.v1.Config.admin:type_name -> metarr.v1.AdminUser
	3,  // 7: metarr.v1.Config.interfaces:type_name -> metarr.v1.InterfacesConfig
	11, // 8: metarr.v1.Config.directory_scanner:type_name -> metarr.v1.DirectoryScannerConfig
	12, // 9: metarr.v1.Config.agents:type_name -> metarr.v1.AgentConfig
	13, // 10: metarr.v1.Config.logging:type_name -> metarr.v1.LoggingConfig
	4,  // 11: metarr.v1.ConfigServiceGetResponse.config:type_name -> metarr.v1.Config
	1,  // 12: metarr.v1.ConfigServiceUpsertApiKeyRequest.entry:type_name -> metarr.v1.APIKeyEntry
	5,  // 13: metarr.v1.ConfigService.Get:input_type -> metarr.v1.ConfigServiceGetRequest
	7,  // 14: metarr.v1.ConfigService.UpdateAdmin:input_type -> metarr.v1.ConfigServiceUpdateAdminRequest
	8,  // 15: metarr.v1.ConfigService.UpsertApiKey:input_type -> metarr.v1.ConfigServiceUpsertApiKeyRequest
	9,  // 16: metarr.v1.ConfigService.DeleteApiKey:input_type -> metarr.v1.ConfigServiceDeleteApiKeyRequest
	6,  // 17: metarr.v1.ConfigService.Get:output_type -> metarr.v1.ConfigServiceGetResponse
	14, // 18: metarr.v1.ConfigService.UpdateAdmin:output_type -> metarr.v1.AcceptedResponse
	14, // 19: metarr.v1.ConfigService.UpsertApiKey:output_type -> metarr.v1.AcceptedResponse
	14, // 20: metarr.v1.ConfigService.DeleteApiKey:output_type -> metarr.v1.AcceptedResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_metarr_v1_config_proto_init() }
func file_metarr_v1_config_proto_init() {
	if File_metarr_v1_config_proto != nil {
		return
	}
	file_metarr_v1_agents_proto_init()
	file_metarr_v1_common_proto_init()
	file_metarr_v1_directory_scanner_proto_init()
	file_metarr_v1_logging_proto_init()
	file_metarr_v1_sonarr_interfaces_proto_init()
	file_metarr_v1_config_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metarr_v1_config_proto_rawDesc), len(file_metarr_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metarr_v1_config_proto_goTypes,
		DependencyIndexes: file_metarr_v1_config_proto_depIdxs,
		MessageInfos:      file_metarr_v1_config_proto_msgTypes,
	}.Build()
	File_metarr_v1_config_proto = out.File
	file_metarr_v1_config_proto_goTypes = nil
	file_metarr_v1_config_proto_depIdxs = nil
}
