// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: metarr/v1/event_bus.proto

package metarrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventBusConfig tunes the Redis event bus without a rebuild (docs/adr/0006):
// stream size caps, the retention window, and the Router's retry-then-
// dead-letter policy. Server-side reads come from live config; the built-in
// defaults in builtin_defaults.json are the values a fresh install runs
// with and match eventbus.DefaultRetryPolicy / DefaultRetentionPolicy.
type EventBusConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// max_len_high is the approximate MAXLEN for the high-volume result
	// streams (events.agent_scan_results, events.agent_node_results).
	MaxLenHigh int32 `protobuf:"varint,1,opt,name=max_len_high,json=maxLenHigh,proto3" json:"max_len_high,omitempty"`
	// max_len_default is the approximate MAXLEN for every other stream,
	// including events.dead_letter.
	MaxLenDefault int32 `protobuf:"varint,2,opt,name=max_len_default,json=maxLenDefault,proto3" json:"max_len_default,omitempty"`
	// retention_hours is how far back the periodic XTRIM sweep keeps entries.
	// The external-subscriber contract is at least 48 hours, or MAXLEN
	// entries, whichever is larger; setting this below 48 narrows that
	// guarantee.
	RetentionHours int32 `protobuf:"varint,3,opt,name=retention_hours,json=retentionHours,proto3" json:"retention_hours,omitempty"`
	// retry_attempts is the number of retries after the first attempt before
	// a handler's message is parked on events.dead_letter.
	RetryAttempts int32 `protobuf:"varint,4,opt,name=retry_attempts,json=retryAttempts,proto3" json:"retry_attempts,omitempty"`
	// retry_backoff_base_ms is the wait before the first retry.
	RetryBackoffBaseMs int32 `protobuf:"varint,5,opt,name=retry_backoff_base_ms,json=retryBackoffBaseMs,proto3" json:"retry_backoff_base_ms,omitempty"`
	// retry_backoff_max_ms caps the exponential backoff between retries.
	RetryBackoffMaxMs int32 `protobuf:"varint,6,opt,name=retry_backoff_max_ms,json=retryBackoffMaxMs,proto3" json:"retry_backoff_max_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventBusConfig) Reset() {
	*x = EventBusConfig{}
	mi := &file_metarr_v1_event_bus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBusConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBusConfig) ProtoMessage() {}

func (x *EventBusConfig) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_event_bus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBusConfig.ProtoReflect.Descriptor instead.
func (*EventBusConfig) Descriptor() ([]byte, []int) {
	return file_metarr_v1_event_bus_proto_rawDescGZIP(), []int{0}
}

func (x *EventBusConfig) GetMaxLenHigh() int32 {
	if x != nil {
		return x.MaxLenHigh
	}
	return 0
}

func (x *EventBusConfig) GetMaxLenDefault() int32 {
	if x != nil {
		return x.MaxLenDefault
	}
	return 0
}

func (x *EventBusConfig) GetRetentionHours() int32 {
	if x != nil {
		return x.RetentionHours
	}
	return 0
}

func (x *EventBusConfig) GetRetryAttempts() int32 {
	if x != nil {
		return x.RetryAttempts
	}
	return 0
}

func (x *EventBusConfig) GetRetryBackoffBaseMs() int32 {
	if x != nil {
		return x.RetryBackoffBaseMs
	}
	return 0
}

func (x *EventBusConfig) GetRetryBackoffMaxMs() int32 {
	if x != nil {
		return x.RetryBackoffMaxMs
	}
	return 0
}

type EventBusServiceGetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBusServiceGetConfigRequest) Reset() {
	*x = EventBusServiceGetConfigRequest{}
	mi := &file_metarr_v1_event_bus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBusServiceGetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBusServiceGetConfigRequest) ProtoMessage() {}

func (x *EventBusServiceGetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_event_bus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBusServiceGetConfigRequest.ProtoReflect.Descriptor instead.
func (*EventBusServiceGetConfigRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_event_bus_proto_rawDescGZIP(), []int{1}
}

type EventBusServiceGetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *EventBusConfig        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBusServiceGetConfigResponse) Reset() {
	*x = EventBusServiceGetConfigResponse{}
	mi := &file_metarr_v1_event_bus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBusServiceGetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBusServiceGetConfigResponse) ProtoMessage() {}

func (x *EventBusServiceGetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_event_bus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBusServiceGetConfigResponse.ProtoReflect.Descriptor instead.
func (*EventBusServiceGetConfigResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_event_bus_proto_rawDescGZIP(), []int{2}
}

func (x *EventBusServiceGetConfigResponse) GetConfig() *EventBusConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// EventBusServiceUpdateConfigRequest carries the whole section: it is one
// small fixed-shape block of scalars, not a collection, so a single
// upserting write is the CRUD shape (see CLAUDE.md). The write still goes
// through the config store as a scoped mutation — cfg.EventBus = config —
// never a whole-document write.
type EventBusServiceUpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *EventBusConfig        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBusServiceUpdateConfigRequest) Reset() {
	*x = EventBusServiceUpdateConfigRequest{}
	mi := &file_metarr_v1_event_bus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBusServiceUpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBusServiceUpdateConfigRequest) ProtoMessage() {}

func (x *EventBusServiceUpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_event_bus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBusServiceUpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*EventBusServiceUpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_event_bus_proto_rawDescGZIP(), []int{3}
}

func (x *EventBusServiceUpdateConfigRequest) GetConfig() *EventBusConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_metarr_v1_event_bus_proto protoreflect.FileDescriptor

const file_metarr_v1_event_bus_proto_rawDesc = "" +
	"\n" +
	"\x19metarr/v1/event_bus.proto\x12\tmetarr.v1\x1a\x16metarr/v1/common.proto\"\x8e\x02\n" +
	"\x0eEventBusConfig\x12 \n" +
	"\fmax_len_high\x18\x01 \x01(\x05R\n" +
	"maxLenHigh\x12&\n" +
	"\x0fmax_len_default\x18\x02 \x01(\x05R\rmaxLenDefault\x12'\n" +
	"\x0fretention_hours\x18\x03 \x01(\x05R\x0eretentionHours\x12%\n" +
	"\x0eretry_attempts\x18\x04 \x01(\x05R\rretryAttempts\x121\n" +
	"\x15retry_backoff_base_ms\x18\x05 \x01(\x05R\x12retryBackoffBaseMs\x12/\n" +
	"\x14retry_backoff_max_ms\x18\x06 \x01(\x05R\x11retryBackoffMaxMs\"!\n" +
	"\x1fEventBusServiceGetConfigRequest\"U\n" +
	" EventBusServiceGetConfigResponse\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.metarr.v1.EventBusConfigR\x06config\"W\n" +
	"\"EventBusServiceUpdateConfigRequest\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.metarr.v1.EventBusConfigR\x06config2\xd3\x01\n" +
	"\x0fEventBusService\x12d\n" +
	"\tGetConfig\x12*.metarr.v1.EventBusServiceGetConfigRequest\x1a+.metarr.v1.EventBusServiceGetConfigResponse\x12Z\n" +
	"\fUpdateConfig\x12-.metarr.v1.EventBusServiceUpdateConfigRequest\x1a\x1b.metarr.v1.AcceptedResponseB-Z+Metarr/internal/genproto/metarr/v1;metarrv1b\x06proto3"

var (
	file_metarr_v1_event_bus_proto_rawDescOnce sync.Once
	file_metarr_v1_event_bus_proto_rawDescData []byte
)

func file_metarr_v1_event_bus_proto_rawDescGZIP() []byte {
	file_metarr_v1_event_bus_proto_rawDescOnce.Do(func() {
		file_metarr_v1_event_bus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metarr_v1_event_bus_proto_rawDesc), len(file_metarr_v1_event_bus_proto_rawDesc)))
	})
	return file_metarr_v1_event_bus_proto_rawDescData
}

var file_metarr_v1_event_bus_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_metarr_v1_event_bus_proto_goTypes = []any{
	(*EventBusConfig)(nil),                     // 0: metarr.v1.EventBusConfig
	(*EventBusServiceGetConfigRequest)(nil),    // 1: metarr.v1.EventBusServiceGetConfigRequest
	(*EventBusServiceGetConfigResponse)(nil),   // 2: metarr.v1.EventBusServiceGetConfigResponse
	(*EventBusServiceUpdateConfigRequest)(nil), // 3: metarr.v1.EventBusServiceUpdateConfigRequest
	(*AcceptedResponse)(nil),                   // 4: metarr.v1.AcceptedResponse
}
var file_metarr_v1_event_bus_proto_depIdxs = []int32{
	0, // 0: metarr.v1.EventBusServiceGetConfigResponse.config:type_name -> metarr.v1.EventBusConfig
	0, // 1: metarr.v1.EventBusServiceUpdateConfigRequest.config:type_name -> metarr.v1.EventBusConfig
	1, // 2: metarr.v1.EventBusService.GetConfig:input_type -> metarr.v1.EventBusServiceGetConfigRequest
	3, // 3: metarr.v1.EventBusService.UpdateConfig:input_type -> metarr.v1.EventBusServiceUpdateConfigRequest
	2, // 4: metarr.v1.EventBusService.GetConfig:output_type -> metarr.v1.EventBusServiceGetConfigResponse
	4, // 5: metarr.v1.EventBusService.UpdateConfig:output_type -> metarr.v1.AcceptedResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metarr_v1_event_bus_proto_init() }
func file_metarr_v1_event_bus_proto_init() {
	if File_metarr_v1_event_bus_proto != nil {
		return
	}
	file_metarr_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metarr_v1_event_bus_proto_rawDesc), len(file_metarr_v1_event_bus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metarr_v1_event_bus_proto_goTypes,
		DependencyIndexes: file_metarr_v1_event_bus_proto_depIdxs,
		MessageInfos:      file_metarr_v1_event_bus_proto_msgTypes,
	}.Build()
	File_metarr_v1_event_bus_proto = out.File
	file_metarr_v1_event_bus_proto_goTypes = nil
	file_metarr_v1_event_bus_proto_depIdxs = nil
}
