// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: metarr/v1/local_directories.proto

package metarrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalDirectoryServiceListDirectoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ScanRoot      string                 `protobuf:"bytes,2,opt,name=scan_root,json=scanRoot,proto3" json:"scan_root,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip          int32                  `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalDirectoryServiceListDirectoriesRequest) Reset() {
	*x = LocalDirectoryServiceListDirectoriesRequest{}
	mi := &file_metarr_v1_local_directories_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDirectoryServiceListDirectoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDirectoryServiceListDirectoriesRequest) ProtoMessage() {}

func (x *LocalDirectoryServiceListDirectoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_local_directories_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDirectoryServiceListDirectoriesRequest.ProtoReflect.Descriptor instead.
func (*LocalDirectoryServiceListDirectoriesRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_local_directories_proto_rawDescGZIP(), []int{0}
}

func (x *LocalDirectoryServiceListDirectoriesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LocalDirectoryServiceListDirectoriesRequest) GetScanRoot() string {
	if x != nil {
		return x.ScanRoot
	}
	return ""
}

func (x *LocalDirectoryServiceListDirectoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LocalDirectoryServiceListDirectoriesRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

type LocalDirectoryServiceListDirectoriesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DirectoriesJson []byte                 `protobuf:"bytes,1,opt,name=directories_json,json=directoriesJson,proto3" json:"directories_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LocalDirectoryServiceListDirectoriesResponse) Reset() {
	*x = LocalDirectoryServiceListDirectoriesResponse{}
	mi := &file_metarr_v1_local_directories_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDirectoryServiceListDirectoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDirectoryServiceListDirectoriesResponse) ProtoMessage() {}

func (x *LocalDirectoryServiceListDirectoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_local_directories_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDirectoryServiceListDirectoriesResponse.ProtoReflect.Descriptor instead.
func (*LocalDirectoryServiceListDirectoriesResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_local_directories_proto_rawDescGZIP(), []int{1}
}

func (x *LocalDirectoryServiceListDirectoriesResponse) GetDirectoriesJson() []byte {
	if x != nil {
		return x.DirectoriesJson
	}
	return nil
}

type LocalDirectoryServiceGetDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalDirectoryServiceGetDirectoryRequest) Reset() {
	*x = LocalDirectoryServiceGetDirectoryRequest{}
	mi := &file_metarr_v1_local_directories_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDirectoryServiceGetDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDirectoryServiceGetDirectoryRequest) ProtoMessage() {}

func (x *LocalDirectoryServiceGetDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_local_directories_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDirectoryServiceGetDirectoryRequest.ProtoReflect.Descriptor instead.
func (*LocalDirectoryServiceGetDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_local_directories_proto_rawDescGZIP(), []int{2}
}

func (x *LocalDirectoryServiceGetDirectoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LocalDirectoryServiceGetDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectoryJson []byte                 `protobuf:"bytes,1,opt,name=directory_json,json=directoryJson,proto3" json:"directory_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalDirectoryServiceGetDirectoryResponse) Reset() {
	*x = LocalDirectoryServiceGetDirectoryResponse{}
	mi := &file_metarr_v1_local_directories_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDirectoryServiceGetDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDirectoryServiceGetDirectoryResponse) ProtoMessage() {}

func (x *LocalDirectoryServiceGetDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_local_directories_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDirectoryServiceGetDirectoryResponse.ProtoReflect.Descriptor instead.
func (*LocalDirectoryServiceGetDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_local_directories_proto_rawDescGZIP(), []int{3}
}

func (x *LocalDirectoryServiceGetDirectoryResponse) GetDirectoryJson() []byte {
	if x != nil {
		return x.DirectoryJson
	}
	return nil
}

type LocalDirectoryServiceListMediaFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectoryId   string                 `protobuf:"bytes,1,opt,name=directory_id,json=directoryId,proto3" json:"directory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalDirectoryServiceListMediaFilesRequest) Reset() {
	*x = LocalDirectoryServiceListMediaFilesRequest{}
	mi := &file_metarr_v1_local_directories_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDirectoryServiceListMediaFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDirectoryServiceListMediaFilesRequest) ProtoMessage() {}

func (x *LocalDirectoryServiceListMediaFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_local_directories_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDirectoryServiceListMediaFilesRequest.ProtoReflect.Descriptor instead.
func (*LocalDirectoryServiceListMediaFilesRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_local_directories_proto_rawDescGZIP(), []int{4}
}

func (x *LocalDirectoryServiceListMediaFilesRequest) GetDirectoryId() string {
	if x != nil {
		return x.DirectoryId
	}
	return ""
}

type LocalDirectoryServiceListMediaFilesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MediaFilesJson []byte                 `protobuf:"bytes,1,opt,name=media_files_json,json=mediaFilesJson,proto3" json:"media_files_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LocalDirectoryServiceListMediaFilesResponse) Reset() {
	*x = LocalDirectoryServiceListMediaFilesResponse{}
	mi := &file_metarr_v1_local_directories_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDirectoryServiceListMediaFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDirectoryServiceListMediaFilesResponse) ProtoMessage() {}

func (x *LocalDirectoryServiceListMediaFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_local_directories_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDirectoryServiceListMediaFilesResponse.ProtoReflect.Descriptor instead.
func (*LocalDirectoryServiceListMediaFilesResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_local_directories_proto_rawDescGZIP(), []int{5}
}

func (x *LocalDirectoryServiceListMediaFilesResponse) GetMediaFilesJson() []byte {
	if x != nil {
		return x.MediaFilesJson
	}
	return nil
}

type LocalDirectoryServiceGetMediaFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalDirectoryServiceGetMediaFileRequest) Reset() {
	*x = LocalDirectoryServiceGetMediaFileRequest{}
	mi := &file_metarr_v1_local_directories_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDirectoryServiceGetMediaFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDirectoryServiceGetMediaFileRequest) ProtoMessage() {}

func (x *LocalDirectoryServiceGetMediaFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_local_directories_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDirectoryServiceGetMediaFileRequest.ProtoReflect.Descriptor instead.
func (*LocalDirectoryServiceGetMediaFileRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_local_directories_proto_rawDescGZIP(), []int{6}
}

func (x *LocalDirectoryServiceGetMediaFileRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LocalDirectoryServiceGetMediaFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaFileJson []byte                 `protobuf:"bytes,1,opt,name=media_file_json,json=mediaFileJson,proto3" json:"media_file_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalDirectoryServiceGetMediaFileResponse) Reset() {
	*x = LocalDirectoryServiceGetMediaFileResponse{}
	mi := &file_metarr_v1_local_directories_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDirectoryServiceGetMediaFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDirectoryServiceGetMediaFileResponse) ProtoMessage() {}

func (x *LocalDirectoryServiceGetMediaFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_local_directories_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDirectoryServiceGetMediaFileResponse.ProtoReflect.Descriptor instead.
func (*LocalDirectoryServiceGetMediaFileResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_local_directories_proto_rawDescGZIP(), []int{7}
}

func (x *LocalDirectoryServiceGetMediaFileResponse) GetMediaFileJson() []byte {
	if x != nil {
		return x.MediaFileJson
	}
	return nil
}

type LocalDirectoryServiceGetDirectoryNFORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectoryId   string                 `protobuf:"bytes,1,opt,name=directory_id,json=directoryId,proto3" json:"directory_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalDirectoryServiceGetDirectoryNFORequest) Reset() {
	*x = LocalDirectoryServiceGetDirectoryNFORequest{}
	mi := &file_metarr_v1_local_directories_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDirectoryServiceGetDirectoryNFORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDirectoryServiceGetDirectoryNFORequest) ProtoMessage() {}

func (x *LocalDirectoryServiceGetDirectoryNFORequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_local_directories_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDirectoryServiceGetDirectoryNFORequest.ProtoReflect.Descriptor instead.
func (*LocalDirectoryServiceGetDirectoryNFORequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_local_directories_proto_rawDescGZIP(), []int{8}
}

func (x *LocalDirectoryServiceGetDirectoryNFORequest) GetDirectoryId() string {
	if x != nil {
		return x.DirectoryId
	}
	return ""
}

func (x *LocalDirectoryServiceGetDirectoryNFORequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type LocalDirectoryServiceGetDirectoryNFOResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetadataJson  []byte                 `protobuf:"bytes,1,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalDirectoryServiceGetDirectoryNFOResponse) Reset() {
	*x = LocalDirectoryServiceGetDirectoryNFOResponse{}
	mi := &file_metarr_v1_local_directories_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalDirectoryServiceGetDirectoryNFOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalDirectoryServiceGetDirectoryNFOResponse) ProtoMessage() {}

func (x *LocalDirectoryServiceGetDirectoryNFOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_local_directories_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalDirectoryServiceGetDirectoryNFOResponse.ProtoReflect.Descriptor instead.
func (*LocalDirectoryServiceGetDirectoryNFOResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_local_directories_proto_rawDescGZIP(), []int{9}
}

func (x *LocalDirectoryServiceGetDirectoryNFOResponse) GetMetadataJson() []byte {
	if x != nil {
		return x.MetadataJson
	}
	return nil
}

var File_metarr_v1_local_directories_proto protoreflect.FileDescriptor

const file_metarr_v1_local_directories_proto_rawDesc = "" +
	"\n" +
	"!metarr/v1/local_directories.proto\x12\tmetarr.v1\"\x88\x01\n" +
	"+LocalDirectoryServiceListDirectoriesRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tscan_root\x18\x02 \x01(\tR\bscanRoot\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04skip\x18\x04 \x01(\x05R\x04skip\"Y\n" +
	",LocalDirectoryServiceListDirectoriesResponse\x12)\n" +
	"\x10directories_json\x18\x01 \x01(\fR\x0fdirectoriesJson\":\n" +
	"(LocalDirectoryServiceGetDirectoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	")LocalDirectoryServiceGetDirectoryResponse\x12%\n" +
	"\x0edirectory_json\x18\x01 \x01(\fR\rdirectoryJson\"O\n" +
	"*LocalDirectoryServiceListMediaFilesRequest\x12!\n" +
	"\fdirectory_id\x18\x01 \x01(\tR\vdirectoryId\"W\n" +
	"+LocalDirectoryServiceListMediaFilesResponse\x12(\n" +
	"\x10media_files_json\x18\x01 \x01(\fR\x0emediaFilesJson\":\n" +
	"(LocalDirectoryServiceGetMediaFileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	")LocalDirectoryServiceGetMediaFileResponse\x12&\n" +
	"\x0fmedia_file_json\x18\x01 \x01(\fR\rmediaFileJson\"d\n" +
	"+LocalDirectoryServiceGetDirectoryNFORequest\x12!\n" +
	"\fdirectory_id\x18\x01 \x01(\tR\vdirectoryId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"S\n" +
	",LocalDirectoryServiceGetDirectoryNFOResponse\x12#\n" +
	"\rmetadata_json\x18\x01 \x01(\fR\fmetadataJson2\x98\x05\n" +
	"\x15LocalDirectoryService\x12\x82\x01\n" +
	"\x0fListDirectories\x126.metarr.v1.LocalDirectoryServiceListDirectoriesRequest\x1a7.metarr.v1.LocalDirectoryServiceListDirectoriesResponse\x12y\n" +
	"\fGetDirectory\x123.metarr.v1.LocalDirectoryServiceGetDirectoryRequest\x1a4.metarr.v1.LocalDirectoryServiceGetDirectoryResponse\x12\x7f\n" +
	"\x0eListMediaFiles\x125.metarr.v1.LocalDirectoryServiceListMediaFilesRequest\x1a6.metarr.v1.LocalDirectoryServiceListMediaFilesResponse\x12y\n" +
	"\fGetMediaFile\x123.metarr.v1.LocalDirectoryServiceGetMediaFileRequest\x1a4.metarr.v1.LocalDirectoryServiceGetMediaFileResponse\x12\x82\x01\n" +
	"\x0fGetDirectoryNFO\x126.metarr.v1.LocalDirectoryServiceGetDirectoryNFORequest\x1a7.metarr.v1.LocalDirectoryServiceGetDirectoryNFOResponseB-Z+Metarr/internal/genproto/metarr/v1;metarrv1b\x06proto3"

var (
	file_metarr_v1_local_directories_proto_rawDescOnce sync.Once
	file_metarr_v1_local_directories_proto_rawDescData []byte
)

func file_metarr_v1_local_directories_proto_rawDescGZIP() []byte {
	file_metarr_v1_local_directories_proto_rawDescOnce.Do(func() {
		file_metarr_v1_local_directories_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metarr_v1_local_directories_proto_rawDesc), len(file_metarr_v1_local_directories_proto_rawDesc)))
	})
	return file_metarr_v1_local_directories_proto_rawDescData
}

var file_metarr_v1_local_directories_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_metarr_v1_local_directories_proto_goTypes = []any{
	(*LocalDirectoryServiceListDirectoriesRequest)(nil),  // 0: metarr.v1.LocalDirectoryServiceListDirectoriesRequest
	(*LocalDirectoryServiceListDirectoriesResponse)(nil), // 1: metarr.v1.LocalDirectoryServiceListDirectoriesResponse
	(*LocalDirectoryServiceGetDirectoryRequest)(nil),     // 2: metarr.v1.LocalDirectoryServiceGetDirectoryRequest
	(*LocalDirectoryServiceGetDirectoryResponse)(nil),    // 3: metarr.v1.LocalDirectoryServiceGetDirectoryResponse
	(*LocalDirectoryServiceListMediaFilesRequest)(nil),   // 4: metarr.v1.LocalDirectoryServiceListMediaFilesRequest
	(*LocalDirectoryServiceListMediaFilesResponse)(nil),  // 5: metarr.v1.LocalDirectoryServiceListMediaFilesResponse
	(*LocalDirectoryServiceGetMediaFileRequest)(nil),     // 6: metarr.v1.LocalDirectoryServiceGetMediaFileRequest
	(*LocalDirectoryServiceGetMediaFileResponse)(nil),    // 7: metarr.v1.LocalDirectoryServiceGetMediaFileResponse
	(*LocalDirectoryServiceGetDirectoryNFORequest)(nil),  // 8: metarr.v1.LocalDirectoryServiceGetDirectoryNFORequest
	(*LocalDirectoryServiceGetDirectoryNFOResponse)(nil), // 9: metarr.v1.LocalDirectoryServiceGetDirectoryNFOResponse
}
var file_metarr_v1_local_directories_proto_depIdxs = []int32{
	0, // 0: metarr.v1.LocalDirectoryService.ListDirectories:input_type -> metarr.v1.LocalDirectoryServiceListDirectoriesRequest
	2, // 1: metarr.v1.LocalDirectoryService.GetDirectory:input_type -> metarr.v1.LocalDirectoryServiceGetDirectoryRequest
	4, // 2: metarr.v1.LocalDirectoryService.ListMediaFiles:input_type -> metarr.v1.LocalDirectoryServiceListMediaFilesRequest
	6, // 3: metarr.v1.LocalDirectoryService.GetMediaFile:input_type -> metarr.v1.LocalDirectoryServiceGetMediaFileRequest
	8, // 4: metarr.v1.LocalDirectoryService.GetDirectoryNFO:input_type -> metarr.v1.LocalDirectoryServiceGetDirectoryNFORequest
	1, // 5: metarr.v1.LocalDirectoryService.ListDirectories:output_type -> metarr.v1.LocalDirectoryServiceListDirectoriesResponse
	3, // 6: metarr.v1.LocalDirectoryService.GetDirectory:output_type -> metarr.v1.LocalDirectoryServiceGetDirectoryResponse
	5, // 7: metarr.v1.LocalDirectoryService.ListMediaFiles:output_type -> metarr.v1.LocalDirectoryServiceListMediaFilesResponse
	7, // 8: metarr.v1.LocalDirectoryService.GetMediaFile:output_type -> metarr.v1.LocalDirectoryServiceGetMediaFileResponse
	9, // 9: metarr.v1.LocalDirectoryService.GetDirectoryNFO:output_type -> metarr.v1.LocalDirectoryServiceGetDirectoryNFOResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metarr_v1_local_directories_proto_init() }
func file_metarr_v1_local_directories_proto_init() {
	if File_metarr_v1_local_directories_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metarr_v1_local_directories_proto_rawDesc), len(file_metarr_v1_local_directories_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metarr_v1_local_directories_proto_goTypes,
		DependencyIndexes: file_metarr_v1_local_directories_proto_depIdxs,
		MessageInfos:      file_metarr_v1_local_directories_proto_msgTypes,
	}.Build()
	File_metarr_v1_local_directories_proto = out.File
	file_metarr_v1_local_directories_proto_goTypes = nil
	file_metarr_v1_local_directories_proto_depIdxs = nil
}
