// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: metarr/v1/logging.proto

package metarrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoggingConfig controls the centralized logging pipeline: the servers own
// log level, plus informational fields describing where Fluent Bit ships
// logs. Each agents own level lives on its AgentConfig entry instead.
type LoggingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerLevel   string                 `protobuf:"bytes,1,opt,name=server_level,json=serverLevel,proto3" json:"server_level,omitempty"`
	Sink          string                 `protobuf:"bytes,2,opt,name=sink,proto3" json:"sink,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Stream        string                 `protobuf:"bytes,4,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingConfig) Reset() {
	*x = LoggingConfig{}
	mi := &file_metarr_v1_logging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingConfig) ProtoMessage() {}

func (x *LoggingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_logging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingConfig.ProtoReflect.Descriptor instead.
func (*LoggingConfig) Descriptor() ([]byte, []int) {
	return file_metarr_v1_logging_proto_rawDescGZIP(), []int{0}
}

func (x *LoggingConfig) GetServerLevel() string {
	if x != nil {
		return x.ServerLevel
	}
	return ""
}

func (x *LoggingConfig) GetSink() string {
	if x != nil {
		return x.Sink
	}
	return ""
}

func (x *LoggingConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *LoggingConfig) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

type GetLoggingConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoggingConfigRequest) Reset() {
	*x = GetLoggingConfigRequest{}
	mi := &file_metarr_v1_logging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoggingConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoggingConfigRequest) ProtoMessage() {}

func (x *GetLoggingConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_logging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoggingConfigRequest.ProtoReflect.Descriptor instead.
func (*GetLoggingConfigRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_logging_proto_rawDescGZIP(), []int{1}
}

type GetLoggingConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *LoggingConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoggingConfigResponse) Reset() {
	*x = GetLoggingConfigResponse{}
	mi := &file_metarr_v1_logging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoggingConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoggingConfigResponse) ProtoMessage() {}

func (x *GetLoggingConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_logging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoggingConfigResponse.ProtoReflect.Descriptor instead.
func (*GetLoggingConfigResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_logging_proto_rawDescGZIP(), []int{2}
}

func (x *GetLoggingConfigResponse) GetConfig() *LoggingConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// UpdateLoggingConfigRequest is an AIP-134 partial update: update_mask names
// the fields to change and config carries their new values. A missing config,
// an empty mask, or a path naming no LoggingConfig field is rejected with
// InvalidArgument (docs/adr/0010). The write goes through the config store as a
// scoped mutation — the masked fields are merged onto cfg.Logging — and blocks
// until the change has persisted and propagated in-process (docs/adr/0002).
type UpdateLoggingConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *LoggingConfig         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLoggingConfigRequest) Reset() {
	*x = UpdateLoggingConfigRequest{}
	mi := &file_metarr_v1_logging_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoggingConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoggingConfigRequest) ProtoMessage() {}

func (x *UpdateLoggingConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_logging_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoggingConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateLoggingConfigRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_logging_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLoggingConfigRequest) GetConfig() *LoggingConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateLoggingConfigRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// LogRecord is the vendor-neutral shape of one log line, shared by both
// binaries. It is the single definition of that shape:
// internal/shared/logging aliases it, publishes it to Redis (where Fluent
// Bit ships it onward), and the live-tail pane on the Logging screen reads
// it. It deliberately carries no vendor-specific field names — Fluent Bit's
// own filters do that translation, which is what keeps the vendor swappable
// at the Fluent Bit layer rather than this one.
//
// time is an RFC3339 nanosecond string rather than google.protobuf.Timestamp
// because that string is the vendor-neutral wire form Fluent Bit already
// consumes verbatim; normalising it through a Timestamp would change the
// bytes on the Redis channel for no gain here.
type LogRecord struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Time    string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Level   string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source  string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// attrs is the caller's free-form key/value context, carried as a
	// structured value so typing the record does not flatten what a caller
	// attached to it. Absent when the caller attached nothing.
	Attrs         *structpb.Struct `protobuf:"bytes,5,opt,name=attrs,proto3" json:"attrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_metarr_v1_logging_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_logging_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_metarr_v1_logging_proto_rawDescGZIP(), []int{4}
}

func (x *LogRecord) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *LogRecord) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogRecord) GetAttrs() *structpb.Struct {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type LoggingServiceGetTailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingServiceGetTailRequest) Reset() {
	*x = LoggingServiceGetTailRequest{}
	mi := &file_metarr_v1_logging_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingServiceGetTailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingServiceGetTailRequest) ProtoMessage() {}

func (x *LoggingServiceGetTailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_logging_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingServiceGetTailRequest.ProtoReflect.Descriptor instead.
func (*LoggingServiceGetTailRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_logging_proto_rawDescGZIP(), []int{5}
}

// LoggingServiceGetTailResponse/StreamTailResponse carry the tail buffer as
// typed LogRecord messages, oldest first.
type LoggingServiceGetTailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*LogRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingServiceGetTailResponse) Reset() {
	*x = LoggingServiceGetTailResponse{}
	mi := &file_metarr_v1_logging_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingServiceGetTailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingServiceGetTailResponse) ProtoMessage() {}

func (x *LoggingServiceGetTailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_logging_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingServiceGetTailResponse.ProtoReflect.Descriptor instead.
func (*LoggingServiceGetTailResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_logging_proto_rawDescGZIP(), []int{6}
}

func (x *LoggingServiceGetTailResponse) GetRecords() []*LogRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type LoggingServiceStreamTailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingServiceStreamTailRequest) Reset() {
	*x = LoggingServiceStreamTailRequest{}
	mi := &file_metarr_v1_logging_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingServiceStreamTailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingServiceStreamTailRequest) ProtoMessage() {}

func (x *LoggingServiceStreamTailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_logging_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingServiceStreamTailRequest.ProtoReflect.Descriptor instead.
func (*LoggingServiceStreamTailRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_logging_proto_rawDescGZIP(), []int{7}
}

type LoggingServiceStreamTailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*LogRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingServiceStreamTailResponse) Reset() {
	*x = LoggingServiceStreamTailResponse{}
	mi := &file_metarr_v1_logging_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingServiceStreamTailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingServiceStreamTailResponse) ProtoMessage() {}

func (x *LoggingServiceStreamTailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_logging_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingServiceStreamTailResponse.ProtoReflect.Descriptor instead.
func (*LoggingServiceStreamTailResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_logging_proto_rawDescGZIP(), []int{8}
}

func (x *LoggingServiceStreamTailResponse) GetRecords() []*LogRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_metarr_v1_logging_proto protoreflect.FileDescriptor

const file_metarr_v1_logging_proto_rawDesc = "" +
	"\n" +
	"\x17metarr/v1/logging.proto\x12\tmetarr.v1\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x86\x01\n" +
	"\rLoggingConfig\x12!\n" +
	"\fserver_level\x18\x01 \x01(\tR\vserverLevel\x12\x12\n" +
	"\x04sink\x18\x02 \x01(\tR\x04sink\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06stream\x18\x04 \x01(\tR\x06streamJ\x04\b\x05\x10\x06R\x04etag\"\x19\n" +
	"\x17GetLoggingConfigRequest\"L\n" +
	"\x18GetLoggingConfigResponse\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x18.metarr.v1.LoggingConfigR\x06config\"\x8b\x01\n" +
	"\x1aUpdateLoggingConfigRequest\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x18.metarr.v1.LoggingConfigR\x06config\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x96\x01\n" +
	"\tLogRecord\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12-\n" +
	"\x05attrs\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x05attrs\"\x1e\n" +
	"\x1cLoggingServiceGetTailRequest\"O\n" +
	"\x1dLoggingServiceGetTailResponse\x12.\n" +
	"\arecords\x18\x01 \x03(\v2\x14.metarr.v1.LogRecordR\arecords\"!\n" +
	"\x1fLoggingServiceStreamTailRequest\"R\n" +
	" LoggingServiceStreamTailResponse\x12.\n" +
	"\arecords\x18\x01 \x03(\v2\x14.metarr.v1.LogRecordR\arecords2\x8c\x03\n" +
	"\x0eLoggingService\x12[\n" +
	"\x10GetLoggingConfig\x12\".metarr.v1.GetLoggingConfigRequest\x1a#.metarr.v1.GetLoggingConfigResponse\x12V\n" +
	"\x13UpdateLoggingConfig\x12%.metarr.v1.UpdateLoggingConfigRequest\x1a\x18.metarr.v1.LoggingConfig\x12\\\n" +
	"\aGetTail\x12'.metarr.v1.LoggingServiceGetTailRequest\x1a(.metarr.v1.LoggingServiceGetTailResponse\x12g\n" +
	"\n" +
	"StreamTail\x12*.metarr.v1.LoggingServiceStreamTailRequest\x1a+.metarr.v1.LoggingServiceStreamTailResponse0\x01B-Z+Metarr/internal/genproto/metarr/v1;metarrv1b\x06proto3"

var (
	file_metarr_v1_logging_proto_rawDescOnce sync.Once
	file_metarr_v1_logging_proto_rawDescData []byte
)

func file_metarr_v1_logging_proto_rawDescGZIP() []byte {
	file_metarr_v1_logging_proto_rawDescOnce.Do(func() {
		file_metarr_v1_logging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metarr_v1_logging_proto_rawDesc), len(file_metarr_v1_logging_proto_rawDesc)))
	})
	return file_metarr_v1_logging_proto_rawDescData
}

var file_metarr_v1_logging_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_metarr_v1_logging_proto_goTypes = []any{
	(*LoggingConfig)(nil),                    // 0: metarr.v1.LoggingConfig
	(*GetLoggingConfigRequest)(nil),          // 1: metarr.v1.GetLoggingConfigRequest
	(*GetLoggingConfigResponse)(nil),         // 2: metarr.v1.GetLoggingConfigResponse
	(*UpdateLoggingConfigRequest)(nil),       // 3: metarr.v1.UpdateLoggingConfigRequest
	(*LogRecord)(nil),                        // 4: metarr.v1.LogRecord
	(*LoggingServiceGetTailRequest)(nil),     // 5: metarr.v1.LoggingServiceGetTailRequest
	(*LoggingServiceGetTailResponse)(nil),    // 6: metarr.v1.LoggingServiceGetTailResponse
	(*LoggingServiceStreamTailRequest)(nil),  // 7: metarr.v1.LoggingServiceStreamTailRequest
	(*LoggingServiceStreamTailResponse)(nil), // 8: metarr.v1.LoggingServiceStreamTailResponse
	(*fieldmaskpb.FieldMask)(nil),            // 9: google.protobuf.FieldMask
	(*structpb.Struct)(nil),                  // 10: google.protobuf.Struct
}
var file_metarr_v1_logging_proto_depIdxs = []int32{
	0,  // 0: metarr.v1.GetLoggingConfigResponse.config:type_name -> metarr.v1.LoggingConfig
	0,  // 1: metarr.v1.UpdateLoggingConfigRequest.config:type_name -> metarr.v1.LoggingConfig
	9,  // 2: metarr.v1.UpdateLoggingConfigRequest.update_mask:type_name -> google.protobuf.FieldMask
	10, // 3: metarr.v1.LogRecord.attrs:type_name -> google.protobuf.Struct
	4,  // 4: metarr.v1.LoggingServiceGetTailResponse.records:type_name -> metarr.v1.LogRecord
	4,  // 5: metarr.v1.LoggingServiceStreamTailResponse.records:type_name -> metarr.v1.LogRecord
	1,  // 6: metarr.v1.LoggingService.GetLoggingConfig:input_type -> metarr.v1.GetLoggingConfigRequest
	3,  // 7: metarr.v1.LoggingService.UpdateLoggingConfig:input_type -> metarr.v1.UpdateLoggingConfigRequest
	5,  // 8: metarr.v1.LoggingService.GetTail:input_type -> metarr.v1.LoggingServiceGetTailRequest
	7,  // 9: metarr.v1.LoggingService.StreamTail:input_type -> metarr.v1.LoggingServiceStreamTailRequest
	2,  // 10: metarr.v1.LoggingService.GetLoggingConfig:output_type -> metarr.v1.GetLoggingConfigResponse
	0,  // 11: metarr.v1.LoggingService.UpdateLoggingConfig:output_type -> metarr.v1.LoggingConfig
	6,  // 12: metarr.v1.LoggingService.GetTail:output_type -> metarr.v1.LoggingServiceGetTailResponse
	8,  // 13: metarr.v1.LoggingService.StreamTail:output_type -> metarr.v1.LoggingServiceStreamTailResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_metarr_v1_logging_proto_init() }
func file_metarr_v1_logging_proto_init() {
	if File_metarr_v1_logging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metarr_v1_logging_proto_rawDesc), len(file_metarr_v1_logging_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metarr_v1_logging_proto_goTypes,
		DependencyIndexes: file_metarr_v1_logging_proto_depIdxs,
		MessageInfos:      file_metarr_v1_logging_proto_msgTypes,
	}.Build()
	File_metarr_v1_logging_proto = out.File
	file_metarr_v1_logging_proto_goTypes = nil
	file_metarr_v1_logging_proto_depIdxs = nil
}
