// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: metarr/v1/metadata.proto

package metarrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Link is one external-provider identifier, such as {tmdb, 603}. Keeping
// these as key/value pairs means a provider Metarr has never heard of is
// still captured and queryable. default names the provider a scraper treats
// as authoritative.
type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Default       bool                   `protobuf:"varint,3,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Link) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Link) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

// UniqueId is one on-disk <uniqueid> tag. Links are derived from these on
// read and rebuilt from them on write.
type UniqueId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Default       bool                   `protobuf:"varint,2,opt,name=default,proto3" json:"default,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueId) Reset() {
	*x = UniqueId{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueId) ProtoMessage() {}

func (x *UniqueId) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueId.ProtoReflect.Descriptor instead.
func (*UniqueId) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *UniqueId) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UniqueId) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *UniqueId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Rating is one site's rating.
type Rating struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Max           string                 `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
	Default       bool                   `protobuf:"varint,3,opt,name=default,proto3" json:"default,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Votes         string                 `protobuf:"bytes,5,opt,name=votes,proto3" json:"votes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rating) Reset() {
	*x = Rating{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *Rating) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rating) GetMax() string {
	if x != nil {
		return x.Max
	}
	return ""
}

func (x *Rating) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *Rating) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Rating) GetVotes() string {
	if x != nil {
		return x.Votes
	}
	return ""
}

// Ratings wraps the per-site ratings collection.
type Ratings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rating        []*Rating              `protobuf:"bytes,1,rep,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ratings) Reset() {
	*x = Ratings{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ratings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ratings) ProtoMessage() {}

func (x *Ratings) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ratings.ProtoReflect.Descriptor instead.
func (*Ratings) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *Ratings) GetRating() []*Rating {
	if x != nil {
		return x.Rating
	}
	return nil
}

// Thumb is an artwork reference. type and season only appear in tvshow
// documents, where one file describes artwork for several seasons.
type Thumb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aspect        string                 `protobuf:"bytes,1,opt,name=aspect,proto3" json:"aspect,omitempty"`
	Preview       string                 `protobuf:"bytes,2,opt,name=preview,proto3" json:"preview,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Season        string                 `protobuf:"bytes,4,opt,name=season,proto3" json:"season,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Thumb) Reset() {
	*x = Thumb{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thumb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thumb) ProtoMessage() {}

func (x *Thumb) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thumb.ProtoReflect.Descriptor instead.
func (*Thumb) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *Thumb) GetAspect() string {
	if x != nil {
		return x.Aspect
	}
	return ""
}

func (x *Thumb) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *Thumb) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Thumb) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

func (x *Thumb) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Fanart wraps the background artwork references.
type Fanart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thumbs        []*Thumb               `protobuf:"bytes,1,rep,name=thumbs,proto3" json:"thumbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fanart) Reset() {
	*x = Fanart{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fanart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fanart) ProtoMessage() {}

func (x *Fanart) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fanart.ProtoReflect.Descriptor instead.
func (*Fanart) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *Fanart) GetThumbs() []*Thumb {
	if x != nil {
		return x.Thumbs
	}
	return nil
}

// Actor is one cast member.
type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Order         string                 `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	Thumb         string                 `protobuf:"bytes,4,opt,name=thumb,proto3" json:"thumb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *Actor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Actor) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Actor) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Actor) GetThumb() string {
	if x != nil {
		return x.Thumb
	}
	return ""
}

// Resume is playback position state.
type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      string                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Total         string                 `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *Resume) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Resume) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

// EpisodeBookmark marks the position where an episode's content proper
// begins.
type EpisodeBookmark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      string                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeBookmark) Reset() {
	*x = EpisodeBookmark{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeBookmark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeBookmark) ProtoMessage() {}

func (x *EpisodeBookmark) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeBookmark.ProtoReflect.Descriptor instead.
func (*EpisodeBookmark) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{8}
}

func (x *EpisodeBookmark) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

// MovieSet is the collection a movie belongs to.
type MovieSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Overview      string                 `protobuf:"bytes,2,opt,name=overview,proto3" json:"overview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieSet) Reset() {
	*x = MovieSet{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieSet) ProtoMessage() {}

func (x *MovieSet) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieSet.ProtoReflect.Descriptor instead.
func (*MovieSet) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{9}
}

func (x *MovieSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MovieSet) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

// XmlAttr is one attribute preserved on an unrecognised element.
type XmlAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XmlAttr) Reset() {
	*x = XmlAttr{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XmlAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XmlAttr) ProtoMessage() {}

func (x *XmlAttr) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XmlAttr.ProtoReflect.Descriptor instead.
func (*XmlAttr) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{10}
}

func (x *XmlAttr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *XmlAttr) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// UnknownElement captures a tag the model does not recognise so it survives
// a read/write round trip. NFO files are the system of record — discarding a
// field Kodi wrote would destroy user metadata.
type UnknownElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Attrs         []*XmlAttr             `protobuf:"bytes,2,rep,name=attrs,proto3" json:"attrs,omitempty"`
	InnerXml      string                 `protobuf:"bytes,3,opt,name=inner_xml,json=innerXml,proto3" json:"inner_xml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnknownElement) Reset() {
	*x = UnknownElement{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnknownElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnknownElement) ProtoMessage() {}

func (x *UnknownElement) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnknownElement.ProtoReflect.Descriptor instead.
func (*UnknownElement) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{11}
}

func (x *UnknownElement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnknownElement) GetAttrs() []*XmlAttr {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *UnknownElement) GetInnerXml() string {
	if x != nil {
		return x.InnerXml
	}
	return ""
}

// CastCrew groups the people credited on an item.
type CastCrew struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directors     []string               `protobuf:"bytes,1,rep,name=directors,proto3" json:"directors,omitempty"`
	Actors        []*Actor               `protobuf:"bytes,2,rep,name=actors,proto3" json:"actors,omitempty"`
	Credits       []string               `protobuf:"bytes,3,rep,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastCrew) Reset() {
	*x = CastCrew{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastCrew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastCrew) ProtoMessage() {}

func (x *CastCrew) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastCrew.ProtoReflect.Descriptor instead.
func (*CastCrew) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{12}
}

func (x *CastCrew) GetDirectors() []string {
	if x != nil {
		return x.Directors
	}
	return nil
}

func (x *CastCrew) GetActors() []*Actor {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *CastCrew) GetCredits() []string {
	if x != nil {
		return x.Credits
	}
	return nil
}

// SeasonSummary is a queryable index over a series' media files.
type SeasonSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeasonNumber  int32                  `protobuf:"varint,1,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	FolderName    string                 `protobuf:"bytes,2,opt,name=folder_name,json=folderName,proto3" json:"folder_name,omitempty"`
	NamedSeason   string                 `protobuf:"bytes,3,opt,name=named_season,json=namedSeason,proto3" json:"named_season,omitempty"`
	SeasonPlot    string                 `protobuf:"bytes,4,opt,name=season_plot,json=seasonPlot,proto3" json:"season_plot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeasonSummary) Reset() {
	*x = SeasonSummary{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeasonSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonSummary) ProtoMessage() {}

func (x *SeasonSummary) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonSummary.ProtoReflect.Descriptor instead.
func (*SeasonSummary) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{13}
}

func (x *SeasonSummary) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *SeasonSummary) GetFolderName() string {
	if x != nil {
		return x.FolderName
	}
	return ""
}

func (x *SeasonSummary) GetNamedSeason() string {
	if x != nil {
		return x.NamedSeason
	}
	return ""
}

func (x *SeasonSummary) GetSeasonPlot() string {
	if x != nil {
		return x.SeasonPlot
	}
	return ""
}

// MovieFields holds the fields unique to a movie document.
type MovieFields struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SortTitle        string                 `protobuf:"bytes,1,opt,name=sort_title,json=sortTitle,proto3" json:"sort_title,omitempty"`
	Fanart           *Fanart                `protobuf:"bytes,2,opt,name=fanart,proto3" json:"fanart,omitempty"`
	Set              *MovieSet              `protobuf:"bytes,3,opt,name=set,proto3" json:"set,omitempty"`
	Countries        []string               `protobuf:"bytes,4,rep,name=countries,proto3" json:"countries,omitempty"`
	ShowLinks        []string               `protobuf:"bytes,5,rep,name=show_links,json=showLinks,proto3" json:"show_links,omitempty"`
	OriginalLanguage string                 `protobuf:"bytes,6,opt,name=original_language,json=originalLanguage,proto3" json:"original_language,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MovieFields) Reset() {
	*x = MovieFields{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieFields) ProtoMessage() {}

func (x *MovieFields) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieFields.ProtoReflect.Descriptor instead.
func (*MovieFields) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{14}
}

func (x *MovieFields) GetSortTitle() string {
	if x != nil {
		return x.SortTitle
	}
	return ""
}

func (x *MovieFields) GetFanart() *Fanart {
	if x != nil {
		return x.Fanart
	}
	return nil
}

func (x *MovieFields) GetSet() *MovieSet {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *MovieFields) GetCountries() []string {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *MovieFields) GetShowLinks() []string {
	if x != nil {
		return x.ShowLinks
	}
	return nil
}

func (x *MovieFields) GetOriginalLanguage() string {
	if x != nil {
		return x.OriginalLanguage
	}
	return ""
}

// TVShowFields holds the fields unique to a tvshow document.
type TVShowFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seasons       []*SeasonSummary       `protobuf:"bytes,1,rep,name=seasons,proto3" json:"seasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TVShowFields) Reset() {
	*x = TVShowFields{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TVShowFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TVShowFields) ProtoMessage() {}

func (x *TVShowFields) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TVShowFields.ProtoReflect.Descriptor instead.
func (*TVShowFields) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{15}
}

func (x *TVShowFields) GetSeasons() []*SeasonSummary {
	if x != nil {
		return x.Seasons
	}
	return nil
}

// EpisodeFields holds the fields unique to an episode document.
type EpisodeFields struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ShowTitle       string                 `protobuf:"bytes,1,opt,name=show_title,json=showTitle,proto3" json:"show_title,omitempty"`
	Season          string                 `protobuf:"bytes,2,opt,name=season,proto3" json:"season,omitempty"`
	Episode         string                 `protobuf:"bytes,3,opt,name=episode,proto3" json:"episode,omitempty"`
	DisplayEpisode  string                 `protobuf:"bytes,4,opt,name=display_episode,json=displayEpisode,proto3" json:"display_episode,omitempty"`
	DisplaySeason   string                 `protobuf:"bytes,5,opt,name=display_season,json=displaySeason,proto3" json:"display_season,omitempty"`
	EpisodeBookmark *EpisodeBookmark       `protobuf:"bytes,6,opt,name=episode_bookmark,json=episodeBookmark,proto3" json:"episode_bookmark,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EpisodeFields) Reset() {
	*x = EpisodeFields{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeFields) ProtoMessage() {}

func (x *EpisodeFields) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeFields.ProtoReflect.Descriptor instead.
func (*EpisodeFields) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{16}
}

func (x *EpisodeFields) GetShowTitle() string {
	if x != nil {
		return x.ShowTitle
	}
	return ""
}

func (x *EpisodeFields) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

func (x *EpisodeFields) GetEpisode() string {
	if x != nil {
		return x.Episode
	}
	return ""
}

func (x *EpisodeFields) GetDisplayEpisode() string {
	if x != nil {
		return x.DisplayEpisode
	}
	return ""
}

func (x *EpisodeFields) GetDisplaySeason() string {
	if x != nil {
		return x.DisplaySeason
	}
	return ""
}

func (x *EpisodeFields) GetEpisodeBookmark() *EpisodeBookmark {
	if x != nil {
		return x.EpisodeBookmark
	}
	return nil
}

// MusicVideoFields holds the fields unique to a music-video document.
type MusicVideoFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         string                 `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	Album         string                 `protobuf:"bytes,2,opt,name=album,proto3" json:"album,omitempty"`
	Artists       []string               `protobuf:"bytes,3,rep,name=artists,proto3" json:"artists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MusicVideoFields) Reset() {
	*x = MusicVideoFields{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicVideoFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicVideoFields) ProtoMessage() {}

func (x *MusicVideoFields) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicVideoFields.ProtoReflect.Descriptor instead.
func (*MusicVideoFields) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{17}
}

func (x *MusicVideoFields) GetTrack() string {
	if x != nil {
		return x.Track
	}
	return ""
}

func (x *MusicVideoFields) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *MusicVideoFields) GetArtists() []string {
	if x != nil {
		return x.Artists
	}
	return nil
}

// VideoAttributes is everything parsed out of a video file's name.
type VideoAttributes struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Title        string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	EpisodeTitle string                 `protobuf:"bytes,2,opt,name=episode_title,json=episodeTitle,proto3" json:"episode_title,omitempty"`
	Year         int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	// season_number is unset when it could not be resolved, which is
	// different from season zero (specials).
	SeasonNumber   *int32  `protobuf:"varint,4,opt,name=season_number,json=seasonNumber,proto3,oneof" json:"season_number,omitempty"`
	EpisodeNumbers []int32 `protobuf:"varint,5,rep,packed,name=episode_numbers,json=episodeNumbers,proto3" json:"episode_numbers,omitempty"`
	AirDate        string  `protobuf:"bytes,6,opt,name=air_date,json=airDate,proto3" json:"air_date,omitempty"`
	IsSpecial      bool    `protobuf:"varint,7,opt,name=is_special,json=isSpecial,proto3" json:"is_special,omitempty"`
	Edition        string  `protobuf:"bytes,8,opt,name=edition,proto3" json:"edition,omitempty"`
	VersionLabel   string  `protobuf:"bytes,9,opt,name=version_label,json=versionLabel,proto3" json:"version_label,omitempty"`
	StackType      string  `protobuf:"bytes,10,opt,name=stack_type,json=stackType,proto3" json:"stack_type,omitempty"`
	StackNumber    int32   `protobuf:"varint,11,opt,name=stack_number,json=stackNumber,proto3" json:"stack_number,omitempty"`
	ThreeDFormat   string  `protobuf:"bytes,12,opt,name=three_d_format,json=threeDFormat,proto3" json:"three_d_format,omitempty"`
	// extra_type and extra_source are set only on extra videos.
	ExtraType     string `protobuf:"bytes,13,opt,name=extra_type,json=extraType,proto3" json:"extra_type,omitempty"`
	ExtraSource   string `protobuf:"bytes,14,opt,name=extra_source,json=extraSource,proto3" json:"extra_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoAttributes) Reset() {
	*x = VideoAttributes{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoAttributes) ProtoMessage() {}

func (x *VideoAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoAttributes.ProtoReflect.Descriptor instead.
func (*VideoAttributes) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{18}
}

func (x *VideoAttributes) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoAttributes) GetEpisodeTitle() string {
	if x != nil {
		return x.EpisodeTitle
	}
	return ""
}

func (x *VideoAttributes) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *VideoAttributes) GetSeasonNumber() int32 {
	if x != nil && x.SeasonNumber != nil {
		return *x.SeasonNumber
	}
	return 0
}

func (x *VideoAttributes) GetEpisodeNumbers() []int32 {
	if x != nil {
		return x.EpisodeNumbers
	}
	return nil
}

func (x *VideoAttributes) GetAirDate() string {
	if x != nil {
		return x.AirDate
	}
	return ""
}

func (x *VideoAttributes) GetIsSpecial() bool {
	if x != nil {
		return x.IsSpecial
	}
	return false
}

func (x *VideoAttributes) GetEdition() string {
	if x != nil {
		return x.Edition
	}
	return ""
}

func (x *VideoAttributes) GetVersionLabel() string {
	if x != nil {
		return x.VersionLabel
	}
	return ""
}

func (x *VideoAttributes) GetStackType() string {
	if x != nil {
		return x.StackType
	}
	return ""
}

func (x *VideoAttributes) GetStackNumber() int32 {
	if x != nil {
		return x.StackNumber
	}
	return 0
}

func (x *VideoAttributes) GetThreeDFormat() string {
	if x != nil {
		return x.ThreeDFormat
	}
	return ""
}

func (x *VideoAttributes) GetExtraType() string {
	if x != nil {
		return x.ExtraType
	}
	return ""
}

func (x *VideoAttributes) GetExtraSource() string {
	if x != nil {
		return x.ExtraSource
	}
	return ""
}

// Metadata records the parsed contents of an NFO sidecar. scope names which
// level of the tree it applies to ("directory", "season", "video"); kind is
// the NFO root element the file turned out to contain.
type Metadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Scope          string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	TargetBaseName string                 `protobuf:"bytes,2,opt,name=target_base_name,json=targetBaseName,proto3" json:"target_base_name,omitempty"`
	ExternalLinks  []*Link                `protobuf:"bytes,3,rep,name=external_links,json=externalLinks,proto3" json:"external_links,omitempty"`
	Kind           string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	OriginalTitle  string                 `protobuf:"bytes,6,opt,name=original_title,json=originalTitle,proto3" json:"original_title,omitempty"`
	Ratings        *Ratings               `protobuf:"bytes,7,opt,name=ratings,proto3" json:"ratings,omitempty"`
	UserRating     string                 `protobuf:"bytes,8,opt,name=user_rating,json=userRating,proto3" json:"user_rating,omitempty"`
	Top250         string                 `protobuf:"bytes,9,opt,name=top250,proto3" json:"top250,omitempty"`
	Outline        string                 `protobuf:"bytes,10,opt,name=outline,proto3" json:"outline,omitempty"`
	Plot           string                 `protobuf:"bytes,11,opt,name=plot,proto3" json:"plot,omitempty"`
	Tagline        string                 `protobuf:"bytes,12,opt,name=tagline,proto3" json:"tagline,omitempty"`
	Runtime        string                 `protobuf:"bytes,13,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Thumbs         []*Thumb               `protobuf:"bytes,14,rep,name=thumbs,proto3" json:"thumbs,omitempty"`
	Mpaa           string                 `protobuf:"bytes,15,opt,name=mpaa,proto3" json:"mpaa,omitempty"`
	PlayCount      int32                  `protobuf:"varint,16,opt,name=play_count,json=playCount,proto3" json:"play_count,omitempty"`
	LastPlayed     string                 `protobuf:"bytes,17,opt,name=last_played,json=lastPlayed,proto3" json:"last_played,omitempty"`
	Id             string                 `protobuf:"bytes,18,opt,name=id,proto3" json:"id,omitempty"`
	Genres         []string               `protobuf:"bytes,19,rep,name=genres,proto3" json:"genres,omitempty"`
	Tags           []string               `protobuf:"bytes,20,rep,name=tags,proto3" json:"tags,omitempty"`
	Premiered      string                 `protobuf:"bytes,21,opt,name=premiered,proto3" json:"premiered,omitempty"`
	Year           int32                  `protobuf:"varint,22,opt,name=year,proto3" json:"year,omitempty"`
	Status         string                 `protobuf:"bytes,23,opt,name=status,proto3" json:"status,omitempty"`
	Code           string                 `protobuf:"bytes,24,opt,name=code,proto3" json:"code,omitempty"`
	Aired          string                 `protobuf:"bytes,25,opt,name=aired,proto3" json:"aired,omitempty"`
	Studios        []string               `protobuf:"bytes,26,rep,name=studios,proto3" json:"studios,omitempty"`
	Trailer        string                 `protobuf:"bytes,27,opt,name=trailer,proto3" json:"trailer,omitempty"`
	Resume         *Resume                `protobuf:"bytes,28,opt,name=resume,proto3" json:"resume,omitempty"`
	DateAdded      string                 `protobuf:"bytes,29,opt,name=date_added,json=dateAdded,proto3" json:"date_added,omitempty"`
	Extra          []*UnknownElement      `protobuf:"bytes,30,rep,name=extra,proto3" json:"extra,omitempty"`
	Movie          *MovieFields           `protobuf:"bytes,31,opt,name=movie,proto3" json:"movie,omitempty"`
	Episode        *EpisodeFields         `protobuf:"bytes,32,opt,name=episode,proto3" json:"episode,omitempty"`
	MusicVideo     *MusicVideoFields      `protobuf:"bytes,33,opt,name=music_video,json=musicVideo,proto3" json:"music_video,omitempty"`
	TvShow         *TVShowFields          `protobuf:"bytes,34,opt,name=tv_show,json=tvShow,proto3" json:"tv_show,omitempty"`
	CastCrew       *CastCrew              `protobuf:"bytes,35,opt,name=cast_crew,json=castCrew,proto3" json:"cast_crew,omitempty"`
	// parse_error records why an NFO could not be read; a malformed sidecar is
	// reported here rather than failing the scan.
	ParseError    string `protobuf:"bytes,36,opt,name=parse_error,json=parseError,proto3" json:"parse_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_metarr_v1_metadata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_metadata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_metarr_v1_metadata_proto_rawDescGZIP(), []int{19}
}

func (x *Metadata) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Metadata) GetTargetBaseName() string {
	if x != nil {
		return x.TargetBaseName
	}
	return ""
}

func (x *Metadata) GetExternalLinks() []*Link {
	if x != nil {
		return x.ExternalLinks
	}
	return nil
}

func (x *Metadata) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Metadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Metadata) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

func (x *Metadata) GetRatings() *Ratings {
	if x != nil {
		return x.Ratings
	}
	return nil
}

func (x *Metadata) GetUserRating() string {
	if x != nil {
		return x.UserRating
	}
	return ""
}

func (x *Metadata) GetTop250() string {
	if x != nil {
		return x.Top250
	}
	return ""
}

func (x *Metadata) GetOutline() string {
	if x != nil {
		return x.Outline
	}
	return ""
}

func (x *Metadata) GetPlot() string {
	if x != nil {
		return x.Plot
	}
	return ""
}

func (x *Metadata) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

func (x *Metadata) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Metadata) GetThumbs() []*Thumb {
	if x != nil {
		return x.Thumbs
	}
	return nil
}

func (x *Metadata) GetMpaa() string {
	if x != nil {
		return x.Mpaa
	}
	return ""
}

func (x *Metadata) GetPlayCount() int32 {
	if x != nil {
		return x.PlayCount
	}
	return 0
}

func (x *Metadata) GetLastPlayed() string {
	if x != nil {
		return x.LastPlayed
	}
	return ""
}

func (x *Metadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metadata) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Metadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Metadata) GetPremiered() string {
	if x != nil {
		return x.Premiered
	}
	return ""
}

func (x *Metadata) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Metadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Metadata) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Metadata) GetAired() string {
	if x != nil {
		return x.Aired
	}
	return ""
}

func (x *Metadata) GetStudios() []string {
	if x != nil {
		return x.Studios
	}
	return nil
}

func (x *Metadata) GetTrailer() string {
	if x != nil {
		return x.Trailer
	}
	return ""
}

func (x *Metadata) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

func (x *Metadata) GetDateAdded() string {
	if x != nil {
		return x.DateAdded
	}
	return ""
}

func (x *Metadata) GetExtra() []*UnknownElement {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *Metadata) GetMovie() *MovieFields {
	if x != nil {
		return x.Movie
	}
	return nil
}

func (x *Metadata) GetEpisode() *EpisodeFields {
	if x != nil {
		return x.Episode
	}
	return nil
}

func (x *Metadata) GetMusicVideo() *MusicVideoFields {
	if x != nil {
		return x.MusicVideo
	}
	return nil
}

func (x *Metadata) GetTvShow() *TVShowFields {
	if x != nil {
		return x.TvShow
	}
	return nil
}

func (x *Metadata) GetCastCrew() *CastCrew {
	if x != nil {
		return x.CastCrew
	}
	return nil
}

func (x *Metadata) GetParseError() string {
	if x != nil {
		return x.ParseError
	}
	return ""
}

var File_metarr_v1_metadata_proto protoreflect.FileDescriptor

const file_metarr_v1_metadata_proto_rawDesc = "" +
	"\n" +
	"\x18metarr/v1/metadata.proto\x12\tmetarr.v1\"H\n" +
	"\x04Link\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\adefault\x18\x03 \x01(\bR\adefault\"N\n" +
	"\bUniqueId\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\adefault\x18\x02 \x01(\bR\adefault\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"t\n" +
	"\x06Rating\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03max\x18\x02 \x01(\tR\x03max\x12\x18\n" +
	"\adefault\x18\x03 \x01(\bR\adefault\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x14\n" +
	"\x05votes\x18\x05 \x01(\tR\x05votes\"4\n" +
	"\aRatings\x12)\n" +
	"\x06rating\x18\x01 \x03(\v2\x11.metarr.v1.RatingR\x06rating\"{\n" +
	"\x05Thumb\x12\x16\n" +
	"\x06aspect\x18\x01 \x01(\tR\x06aspect\x12\x18\n" +
	"\apreview\x18\x02 \x01(\tR\apreview\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06season\x18\x04 \x01(\tR\x06season\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\"2\n" +
	"\x06Fanart\x12(\n" +
	"\x06thumbs\x18\x01 \x03(\v2\x10.metarr.v1.ThumbR\x06thumbs\"[\n" +
	"\x05Actor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x14\n" +
	"\x05order\x18\x03 \x01(\tR\x05order\x12\x14\n" +
	"\x05thumb\x18\x04 \x01(\tR\x05thumb\":\n" +
	"\x06Resume\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\tR\bposition\x12\x14\n" +
	"\x05total\x18\x02 \x01(\tR\x05total\"-\n" +
	"\x0fEpisodeBookmark\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\tR\bposition\":\n" +
	"\bMovieSet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\boverview\x18\x02 \x01(\tR\boverview\"3\n" +
	"\aXmlAttr\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"k\n" +
	"\x0eUnknownElement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x05attrs\x18\x02 \x03(\v2\x12.metarr.v1.XmlAttrR\x05attrs\x12\x1b\n" +
	"\tinner_xml\x18\x03 \x01(\tR\binnerXml\"l\n" +
	"\bCastCrew\x12\x1c\n" +
	"\tdirectors\x18\x01 \x03(\tR\tdirectors\x12(\n" +
	"\x06actors\x18\x02 \x03(\v2\x10.metarr.v1.ActorR\x06actors\x12\x18\n" +
	"\acredits\x18\x03 \x03(\tR\acredits\"\x99\x01\n" +
	"\rSeasonSummary\x12#\n" +
	"\rseason_number\x18\x01 \x01(\x05R\fseasonNumber\x12\x1f\n" +
	"\vfolder_name\x18\x02 \x01(\tR\n" +
	"folderName\x12!\n" +
	"\fnamed_season\x18\x03 \x01(\tR\vnamedSeason\x12\x1f\n" +
	"\vseason_plot\x18\x04 \x01(\tR\n" +
	"seasonPlot\"\xe8\x01\n" +
	"\vMovieFields\x12\x1d\n" +
	"\n" +
	"sort_title\x18\x01 \x01(\tR\tsortTitle\x12)\n" +
	"\x06fanart\x18\x02 \x01(\v2\x11.metarr.v1.FanartR\x06fanart\x12%\n" +
	"\x03set\x18\x03 \x01(\v2\x13.metarr.v1.MovieSetR\x03set\x12\x1c\n" +
	"\tcountries\x18\x04 \x03(\tR\tcountries\x12\x1d\n" +
	"\n" +
	"show_links\x18\x05 \x03(\tR\tshowLinks\x12+\n" +
	"\x11original_language\x18\x06 \x01(\tR\x10originalLanguage\"B\n" +
	"\fTVShowFields\x122\n" +
	"\aseasons\x18\x01 \x03(\v2\x18.metarr.v1.SeasonSummaryR\aseasons\"\xf7\x01\n" +
	"\rEpisodeFields\x12\x1d\n" +
	"\n" +
	"show_title\x18\x01 \x01(\tR\tshowTitle\x12\x16\n" +
	"\x06season\x18\x02 \x01(\tR\x06season\x12\x18\n" +
	"\aepisode\x18\x03 \x01(\tR\aepisode\x12'\n" +
	"\x0fdisplay_episode\x18\x04 \x01(\tR\x0edisplayEpisode\x12%\n" +
	"\x0edisplay_season\x18\x05 \x01(\tR\rdisplaySeason\x12E\n" +
	"\x10episode_bookmark\x18\x06 \x01(\v2\x1a.metarr.v1.EpisodeBookmarkR\x0fepisodeBookmark\"X\n" +
	"\x10MusicVideoFields\x12\x14\n" +
	"\x05track\x18\x01 \x01(\tR\x05track\x12\x14\n" +
	"\x05album\x18\x02 \x01(\tR\x05album\x12\x18\n" +
	"\aartists\x18\x03 \x03(\tR\aartists\"\xe8\x03\n" +
	"\x0fVideoAttributes\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12#\n" +
	"\repisode_title\x18\x02 \x01(\tR\fepisodeTitle\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12(\n" +
	"\rseason_number\x18\x04 \x01(\x05H\x00R\fseasonNumber\x88\x01\x01\x12'\n" +
	"\x0fepisode_numbers\x18\x05 \x03(\x05R\x0eepisodeNumbers\x12\x19\n" +
	"\bair_date\x18\x06 \x01(\tR\aairDate\x12\x1d\n" +
	"\n" +
	"is_special\x18\a \x01(\bR\tisSpecial\x12\x18\n" +
	"\aedition\x18\b \x01(\tR\aedition\x12#\n" +
	"\rversion_label\x18\t \x01(\tR\fversionLabel\x12\x1d\n" +
	"\n" +
	"stack_type\x18\n" +
	" \x01(\tR\tstackType\x12!\n" +
	"\fstack_number\x18\v \x01(\x05R\vstackNumber\x12$\n" +
	"\x0ethree_d_format\x18\f \x01(\tR\fthreeDFormat\x12\x1d\n" +
	"\n" +
	"extra_type\x18\r \x01(\tR\textraType\x12!\n" +
	"\fextra_source\x18\x0e \x01(\tR\vextraSourceB\x10\n" +
	"\x0e_season_number\"\x9e\t\n" +
	"\bMetadata\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12(\n" +
	"\x10target_base_name\x18\x02 \x01(\tR\x0etargetBaseName\x126\n" +
	"\x0eexternal_links\x18\x03 \x03(\v2\x0f.metarr.v1.LinkR\rexternalLinks\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12%\n" +
	"\x0eoriginal_title\x18\x06 \x01(\tR\roriginalTitle\x12,\n" +
	"\aratings\x18\a \x01(\v2\x12.metarr.v1.RatingsR\aratings\x12\x1f\n" +
	"\vuser_rating\x18\b \x01(\tR\n" +
	"userRating\x12\x16\n" +
	"\x06top250\x18\t \x01(\tR\x06top250\x12\x18\n" +
	"\aoutline\x18\n" +
	" \x01(\tR\aoutline\x12\x12\n" +
	"\x04plot\x18\v \x01(\tR\x04plot\x12\x18\n" +
	"\atagline\x18\f \x01(\tR\atagline\x12\x18\n" +
	"\aruntime\x18\r \x01(\tR\aruntime\x12(\n" +
	"\x06thumbs\x18\x0e \x03(\v2\x10.metarr.v1.ThumbR\x06thumbs\x12\x12\n" +
	"\x04mpaa\x18\x0f \x01(\tR\x04mpaa\x12\x1d\n" +
	"\n" +
	"play_count\x18\x10 \x01(\x05R\tplayCount\x12\x1f\n" +
	"\vlast_played\x18\x11 \x01(\tR\n" +
	"lastPlayed\x12\x0e\n" +
	"\x02id\x18\x12 \x01(\tR\x02id\x12\x16\n" +
	"\x06genres\x18\x13 \x03(\tR\x06genres\x12\x12\n" +
	"\x04tags\x18\x14 \x03(\tR\x04tags\x12\x1c\n" +
	"\tpremiered\x18\x15 \x01(\tR\tpremiered\x12\x12\n" +
	"\x04year\x18\x16 \x01(\x05R\x04year\x12\x16\n" +
	"\x06status\x18\x17 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x18 \x01(\tR\x04code\x12\x14\n" +
	"\x05aired\x18\x19 \x01(\tR\x05aired\x12\x18\n" +
	"\astudios\x18\x1a \x03(\tR\astudios\x12\x18\n" +
	"\atrailer\x18\x1b \x01(\tR\atrailer\x12)\n" +
	"\x06resume\x18\x1c \x01(\v2\x11.metarr.v1.ResumeR\x06resume\x12\x1d\n" +
	"\n" +
	"date_added\x18\x1d \x01(\tR\tdateAdded\x12/\n" +
	"\x05extra\x18\x1e \x03(\v2\x19.metarr.v1.UnknownElementR\x05extra\x12,\n" +
	"\x05movie\x18\x1f \x01(\v2\x16.metarr.v1.MovieFieldsR\x05movie\x122\n" +
	"\aepisode\x18  \x01(\v2\x18.metarr.v1.EpisodeFieldsR\aepisode\x12<\n" +
	"\vmusic_video\x18! \x01(\v2\x1b.metarr.v1.MusicVideoFieldsR\n" +
	"musicVideo\x120\n" +
	"\atv_show\x18\" \x01(\v2\x17.metarr.v1.TVShowFieldsR\x06tvShow\x120\n" +
	"\tcast_crew\x18# \x01(\v2\x13.metarr.v1.CastCrewR\bcastCrew\x12\x1f\n" +
	"\vparse_error\x18$ \x01(\tR\n" +
	"parseErrorB-Z+Metarr/internal/genproto/metarr/v1;metarrv1b\x06proto3"

var (
	file_metarr_v1_metadata_proto_rawDescOnce sync.Once
	file_metarr_v1_metadata_proto_rawDescData []byte
)

func file_metarr_v1_metadata_proto_rawDescGZIP() []byte {
	file_metarr_v1_metadata_proto_rawDescOnce.Do(func() {
		file_metarr_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metarr_v1_metadata_proto_rawDesc), len(file_metarr_v1_metadata_proto_rawDesc)))
	})
	return file_metarr_v1_metadata_proto_rawDescData
}

var file_metarr_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_metarr_v1_metadata_proto_goTypes = []any{
	(*Link)(nil),             // 0: metarr.v1.Link
	(*UniqueId)(nil),         // 1: metarr.v1.UniqueId
	(*Rating)(nil),           // 2: metarr.v1.Rating
	(*Ratings)(nil),          // 3: metarr.v1.Ratings
	(*Thumb)(nil),            // 4: metarr.v1.Thumb
	(*Fanart)(nil),           // 5: metarr.v1.Fanart
	(*Actor)(nil),            // 6: metarr.v1.Actor
	(*Resume)(nil),           // 7: metarr.v1.Resume
	(*EpisodeBookmark)(nil),  // 8: metarr.v1.EpisodeBookmark
	(*MovieSet)(nil),         // 9: metarr.v1.MovieSet
	(*XmlAttr)(nil),          // 10: metarr.v1.XmlAttr
	(*UnknownElement)(nil),   // 11: metarr.v1.UnknownElement
	(*CastCrew)(nil),         // 12: metarr.v1.CastCrew
	(*SeasonSummary)(nil),    // 13: metarr.v1.SeasonSummary
	(*MovieFields)(nil),      // 14: metarr.v1.MovieFields
	(*TVShowFields)(nil),     // 15: metarr.v1.TVShowFields
	(*EpisodeFields)(nil),    // 16: metarr.v1.EpisodeFields
	(*MusicVideoFields)(nil), // 17: metarr.v1.MusicVideoFields
	(*VideoAttributes)(nil),  // 18: metarr.v1.VideoAttributes
	(*Metadata)(nil),         // 19: metarr.v1.Metadata
}
var file_metarr_v1_metadata_proto_depIdxs = []int32{
	2,  // 0: metarr.v1.Ratings.rating:type_name -> metarr.v1.Rating
	4,  // 1: metarr.v1.Fanart.thumbs:type_name -> metarr.v1.Thumb
	10, // 2: metarr.v1.UnknownElement.attrs:type_name -> metarr.v1.XmlAttr
	6,  // 3: metarr.v1.CastCrew.actors:type_name -> metarr.v1.Actor
	5,  // 4: metarr.v1.MovieFields.fanart:type_name -> metarr.v1.Fanart
	9,  // 5: metarr.v1.MovieFields.set:type_name -> metarr.v1.MovieSet
	13, // 6: metarr.v1.TVShowFields.seasons:type_name -> metarr.v1.SeasonSummary
	8,  // 7: metarr.v1.EpisodeFields.episode_bookmark:type_name -> metarr.v1.EpisodeBookmark
	0,  // 8: metarr.v1.Metadata.external_links:type_name -> metarr.v1.Link
	3,  // 9: metarr.v1.Metadata.ratings:type_name -> metarr.v1.Ratings
	4,  // 10: metarr.v1.Metadata.thumbs:type_name -> metarr.v1.Thumb
	7,  // 11: metarr.v1.Metadata.resume:type_name -> metarr.v1.Resume
	11, // 12: metarr.v1.Metadata.extra:type_name -> metarr.v1.UnknownElement
	14, // 13: metarr.v1.Metadata.movie:type_name -> metarr.v1.MovieFields
	16, // 14: metarr.v1.Metadata.episode:type_name -> metarr.v1.EpisodeFields
	17, // 15: metarr.v1.Metadata.music_video:type_name -> metarr.v1.MusicVideoFields
	15, // 16: metarr.v1.Metadata.tv_show:type_name -> metarr.v1.TVShowFields
	12, // 17: metarr.v1.Metadata.cast_crew:type_name -> metarr.v1.CastCrew
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_metarr_v1_metadata_proto_init() }
func file_metarr_v1_metadata_proto_init() {
	if File_metarr_v1_metadata_proto != nil {
		return
	}
	file_metarr_v1_metadata_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metarr_v1_metadata_proto_rawDesc), len(file_metarr_v1_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metarr_v1_metadata_proto_goTypes,
		DependencyIndexes: file_metarr_v1_metadata_proto_depIdxs,
		MessageInfos:      file_metarr_v1_metadata_proto_msgTypes,
	}.Build()
	File_metarr_v1_metadata_proto = out.File
	file_metarr_v1_metadata_proto_goTypes = nil
	file_metarr_v1_metadata_proto_depIdxs = nil
}
