// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: metarr/v1/operations.proto

package metarrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operation is Metarr's AIP-151 long-running-operation handle for the config
// API. Every config write returns one instead of the resource: the config
// store is event-sourced and eventually consistent (ADR-0002), so the durable
// write happens after the RPC returns, in the system_config_update listener.
//
// name is `operations/{correlation_id}` — the same correlation id the write
// stamps on its fired event, so no new identifier is minted. The operation
// starts done:false; the listener sets done:true once it has persisted, with
// `error` set on a persistence or late cross-entry-validation failure, or
// `response` set to the created resource's name for a minted-id Create (an
// Update or Delete leaves `response` empty).
//
// The shape mirrors google.longrunning.Operation but does not import it: that
// proto's Go binding pulls in google.golang.org/grpc and cloud.google.com/go,
// which this Connect-only codebase has no other use for, and its
// google.rpc.Status / google.protobuf.Any fields have no generated TypeScript
// unless the googleapis module is added to the generation target. `error` is a
// reduced {code, message} — the config API never fills google.rpc.Status
// details — and `response` is a resource name rather than a packed Any, which
// is all a minted-id Create client needs (it then reads the resource).
// `metadata` is omitted: the one first-party UI client polls to completion and
// never reads progress.
type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Done  bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*Operation_Error
	//	*Operation_Response
	Result        isOperation_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_metarr_v1_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_metarr_v1_operations_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Operation) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Operation) GetResult() isOperation_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Operation) GetError() *OperationError {
	if x != nil {
		if x, ok := x.Result.(*Operation_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Operation) GetResponse() string {
	if x != nil {
		if x, ok := x.Result.(*Operation_Response); ok {
			return x.Response
		}
	}
	return ""
}

type isOperation_Result interface {
	isOperation_Result()
}

type Operation_Error struct {
	Error *OperationError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type Operation_Response struct {
	Response string `protobuf:"bytes,4,opt,name=response,proto3,oneof"`
}

func (*Operation_Error) isOperation_Result() {}

func (*Operation_Response) isOperation_Result() {}

// OperationError is the failure of a completed Operation. code is a
// connect.Code / google.rpc.Code integer; message is safe to show an operator.
type OperationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationError) Reset() {
	*x = OperationError{}
	mi := &file_metarr_v1_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationError) ProtoMessage() {}

func (x *OperationError) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationError.ProtoReflect.Descriptor instead.
func (*OperationError) Descriptor() ([]byte, []int) {
	return file_metarr_v1_operations_proto_rawDescGZIP(), []int{1}
}

func (x *OperationError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OperationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetOperationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is `operations/{correlation_id}`.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_metarr_v1_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_operations_proto_rawDescGZIP(), []int{2}
}

func (x *GetOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListOperationsRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PageSize  int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// filter is an AIP-160 expression; today only `done = true` / `done = false`
	// is honoured.
	Filter        string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsRequest) Reset() {
	*x = ListOperationsRequest{}
	mi := &file_metarr_v1_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsRequest) ProtoMessage() {}

func (x *ListOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListOperationsRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_operations_proto_rawDescGZIP(), []int{3}
}

func (x *ListOperationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOperationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListOperationsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*Operation           `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsResponse) Reset() {
	*x = ListOperationsResponse{}
	mi := &file_metarr_v1_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsResponse) ProtoMessage() {}

func (x *ListOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_operations_proto_rawDescGZIP(), []int{4}
}

func (x *ListOperationsResponse) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ListOperationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_metarr_v1_operations_proto protoreflect.FileDescriptor

const file_metarr_v1_operations_proto_rawDesc = "" +
	"\n" +
	"\x1ametarr/v1/operations.proto\x12\tmetarr.v1\"\x8e\x01\n" +
	"\tOperation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x121\n" +
	"\x05error\x18\x03 \x01(\v2\x19.metarr.v1.OperationErrorH\x00R\x05error\x12\x1c\n" +
	"\bresponse\x18\x04 \x01(\tH\x00R\bresponseB\b\n" +
	"\x06result\">\n" +
	"\x0eOperationError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\")\n" +
	"\x13GetOperationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"k\n" +
	"\x15ListOperationsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"v\n" +
	"\x16ListOperationsResponse\x124\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x14.metarr.v1.OperationR\n" +
	"operations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xb0\x01\n" +
	"\x11OperationsService\x12D\n" +
	"\fGetOperation\x12\x1e.metarr.v1.GetOperationRequest\x1a\x14.metarr.v1.Operation\x12U\n" +
	"\x0eListOperations\x12 .metarr.v1.ListOperationsRequest\x1a!.metarr.v1.ListOperationsResponseB-Z+Metarr/internal/genproto/metarr/v1;metarrv1b\x06proto3"

var (
	file_metarr_v1_operations_proto_rawDescOnce sync.Once
	file_metarr_v1_operations_proto_rawDescData []byte
)

func file_metarr_v1_operations_proto_rawDescGZIP() []byte {
	file_metarr_v1_operations_proto_rawDescOnce.Do(func() {
		file_metarr_v1_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metarr_v1_operations_proto_rawDesc), len(file_metarr_v1_operations_proto_rawDesc)))
	})
	return file_metarr_v1_operations_proto_rawDescData
}

var file_metarr_v1_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_metarr_v1_operations_proto_goTypes = []any{
	(*Operation)(nil),              // 0: metarr.v1.Operation
	(*OperationError)(nil),         // 1: metarr.v1.OperationError
	(*GetOperationRequest)(nil),    // 2: metarr.v1.GetOperationRequest
	(*ListOperationsRequest)(nil),  // 3: metarr.v1.ListOperationsRequest
	(*ListOperationsResponse)(nil), // 4: metarr.v1.ListOperationsResponse
}
var file_metarr_v1_operations_proto_depIdxs = []int32{
	1, // 0: metarr.v1.Operation.error:type_name -> metarr.v1.OperationError
	0, // 1: metarr.v1.ListOperationsResponse.operations:type_name -> metarr.v1.Operation
	2, // 2: metarr.v1.OperationsService.GetOperation:input_type -> metarr.v1.GetOperationRequest
	3, // 3: metarr.v1.OperationsService.ListOperations:input_type -> metarr.v1.ListOperationsRequest
	0, // 4: metarr.v1.OperationsService.GetOperation:output_type -> metarr.v1.Operation
	4, // 5: metarr.v1.OperationsService.ListOperations:output_type -> metarr.v1.ListOperationsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metarr_v1_operations_proto_init() }
func file_metarr_v1_operations_proto_init() {
	if File_metarr_v1_operations_proto != nil {
		return
	}
	file_metarr_v1_operations_proto_msgTypes[0].OneofWrappers = []any{
		(*Operation_Error)(nil),
		(*Operation_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metarr_v1_operations_proto_rawDesc), len(file_metarr_v1_operations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metarr_v1_operations_proto_goTypes,
		DependencyIndexes: file_metarr_v1_operations_proto_depIdxs,
		MessageInfos:      file_metarr_v1_operations_proto_msgTypes,
	}.Build()
	File_metarr_v1_operations_proto = out.File
	file_metarr_v1_operations_proto_goTypes = nil
	file_metarr_v1_operations_proto_depIdxs = nil
}
