// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: metarr/v1/tasks.proto

package metarrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskServiceRunDirectoryScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScannerSlug   string                 `protobuf:"bytes,1,opt,name=scanner_slug,json=scannerSlug,proto3" json:"scanner_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskServiceRunDirectoryScanRequest) Reset() {
	*x = TaskServiceRunDirectoryScanRequest{}
	mi := &file_metarr_v1_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskServiceRunDirectoryScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceRunDirectoryScanRequest) ProtoMessage() {}

func (x *TaskServiceRunDirectoryScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceRunDirectoryScanRequest.ProtoReflect.Descriptor instead.
func (*TaskServiceRunDirectoryScanRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *TaskServiceRunDirectoryScanRequest) GetScannerSlug() string {
	if x != nil {
		return x.ScannerSlug
	}
	return ""
}

// TaskServiceRunDirectoryScanResponse acknowledges that the scan command was
// accepted onto the event bus. The scan itself runs asynchronously in the
// agent that owns the library, and its results come back on a separate stream
// consumed by internal/server/listeners/agent_scan_result_listener.go, so
// "accepted" means "queued", not "finished". This is a genuine long-running
// task kickoff, unrelated to the synchronous config writes (docs/adr/0002).
// scan_id is the correlation id assigned to the command; the caller uses it to
// tie the scan's async results back to this request.
type TaskServiceRunDirectoryScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskServiceRunDirectoryScanResponse) Reset() {
	*x = TaskServiceRunDirectoryScanResponse{}
	mi := &file_metarr_v1_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskServiceRunDirectoryScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskServiceRunDirectoryScanResponse) ProtoMessage() {}

func (x *TaskServiceRunDirectoryScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskServiceRunDirectoryScanResponse.ProtoReflect.Descriptor instead.
func (*TaskServiceRunDirectoryScanResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *TaskServiceRunDirectoryScanResponse) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

var File_metarr_v1_tasks_proto protoreflect.FileDescriptor

const file_metarr_v1_tasks_proto_rawDesc = "" +
	"\n" +
	"\x15metarr/v1/tasks.proto\x12\tmetarr.v1\"G\n" +
	"\"TaskServiceRunDirectoryScanRequest\x12!\n" +
	"\fscanner_slug\x18\x01 \x01(\tR\vscannerSlug\">\n" +
	"#TaskServiceRunDirectoryScanResponse\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId2\x80\x01\n" +
	"\vTaskService\x12q\n" +
	"\x10RunDirectoryScan\x12-.metarr.v1.TaskServiceRunDirectoryScanRequest\x1a..metarr.v1.TaskServiceRunDirectoryScanResponseB-Z+Metarr/internal/genproto/metarr/v1;metarrv1b\x06proto3"

var (
	file_metarr_v1_tasks_proto_rawDescOnce sync.Once
	file_metarr_v1_tasks_proto_rawDescData []byte
)

func file_metarr_v1_tasks_proto_rawDescGZIP() []byte {
	file_metarr_v1_tasks_proto_rawDescOnce.Do(func() {
		file_metarr_v1_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metarr_v1_tasks_proto_rawDesc), len(file_metarr_v1_tasks_proto_rawDesc)))
	})
	return file_metarr_v1_tasks_proto_rawDescData
}

var file_metarr_v1_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metarr_v1_tasks_proto_goTypes = []any{
	(*TaskServiceRunDirectoryScanRequest)(nil),  // 0: metarr.v1.TaskServiceRunDirectoryScanRequest
	(*TaskServiceRunDirectoryScanResponse)(nil), // 1: metarr.v1.TaskServiceRunDirectoryScanResponse
}
var file_metarr_v1_tasks_proto_depIdxs = []int32{
	0, // 0: metarr.v1.TaskService.RunDirectoryScan:input_type -> metarr.v1.TaskServiceRunDirectoryScanRequest
	1, // 1: metarr.v1.TaskService.RunDirectoryScan:output_type -> metarr.v1.TaskServiceRunDirectoryScanResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metarr_v1_tasks_proto_init() }
func file_metarr_v1_tasks_proto_init() {
	if File_metarr_v1_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metarr_v1_tasks_proto_rawDesc), len(file_metarr_v1_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metarr_v1_tasks_proto_goTypes,
		DependencyIndexes: file_metarr_v1_tasks_proto_depIdxs,
		MessageInfos:      file_metarr_v1_tasks_proto_msgTypes,
	}.Build()
	File_metarr_v1_tasks_proto = out.File
	file_metarr_v1_tasks_proto_goTypes = nil
	file_metarr_v1_tasks_proto_depIdxs = nil
}
