// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: metarr/v1/workflows.proto

package metarrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Workflow is one version of a versioned workflow document, always returned as
// the latest version by the standard reads: the scalar metadata plus the
// authored graph. internal/server/mongostore.Workflow is the stored form;
// internal/shared/workflow aliases WorkflowGraph and its parts. See
// docs/adr/0005 and docs/adr/0010.
//
// id is the logical document id — the value every version shares, minted once
// when version 1 is created. It kept field number 2 across the rename from
// document_id (wire-compatible; the BSON field in the collection is
// independent of the message field name). Field 1 held the per-version raw
// object id and is retired — a version is addressed by id plus version.
//
// The graph's open content — a node's settings, and its extra field — is
// carried as structured values so a node whose type this build does not
// recognise, and settings it does not recognise, round-trip through storage
// unchanged. schema_version lives on WorkflowGraph, the canonical graph shape
// the catalog also advertises, not on this message.
type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Graph         *WorkflowGraph         `protobuf:"bytes,8,opt,name=graph,proto3" json:"graph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_metarr_v1_workflows_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_workflows_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_metarr_v1_workflows_proto_rawDescGZIP(), []int{0}
}

func (x *Workflow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workflow) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Workflow) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workflow) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Workflow) GetGraph() *WorkflowGraph {
	if x != nil {
		return x.Graph
	}
	return nil
}

// CreateWorkflowRequest carries the resource only — no id, the store mints it
// and returns the persisted workflow at version 1. name, description and at
// least one tag are required (InvalidArgument otherwise); the graph is stored
// as-is and its validity stays the client's job via the catalog validate RPC.
type CreateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowRequest) Reset() {
	*x = CreateWorkflowRequest{}
	mi := &file_metarr_v1_workflows_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowRequest) ProtoMessage() {}

func (x *CreateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_workflows_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_workflows_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkflowRequest) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_metarr_v1_workflows_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_workflows_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_workflows_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkflowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListWorkflowsRequest is the AIP-158 page window over the latest version of
// every workflow, newest first. page_size defaults to 50 and is capped at
// 100; page_token is the opaque cursor a previous response returned. A
// non-empty filter or order_by is Unimplemented — the list is storage-ordered
// and AIP-160 translation is deferred, matching the config lists.
type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_metarr_v1_workflows_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_workflows_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_workflows_proto_rawDescGZIP(), []int{3}
}

func (x *ListWorkflowsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkflowsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListWorkflowsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListWorkflowsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*Workflow            `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_metarr_v1_workflows_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_workflows_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_workflows_proto_rawDescGZIP(), []int{4}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *ListWorkflowsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// UpdateWorkflowRequest is an AIP-134 partial update: workflow.id addresses
// the document, update_mask is authoritative for which fields change. Allowed
// paths are name, description, tags and graph; graph is masked wholesale (a
// path may name graph but not a sub-path). An empty mask or an unknown path
// is InvalidArgument. The update reads the latest version, applies the mask,
// and appends the result as a new immutable version. There is no
// allow_missing — a knob that must always be false is a footgun (docs/adr/0010).
type UpdateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkflowRequest) Reset() {
	*x = UpdateWorkflowRequest{}
	mi := &file_metarr_v1_workflows_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkflowRequest) ProtoMessage() {}

func (x *UpdateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_workflows_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_workflows_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateWorkflowRequest) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *UpdateWorkflowRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// DeleteWorkflowRequest hard-removes every version of the workflow — not a
// soft delete, not a tombstone version. The one surprising call in an
// otherwise append-only store; see docs/adr/0013.
type DeleteWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkflowRequest) Reset() {
	*x = DeleteWorkflowRequest{}
	mi := &file_metarr_v1_workflows_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkflowRequest) ProtoMessage() {}

func (x *DeleteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_workflows_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_workflows_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteWorkflowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWorkflowVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowVersionRequest) Reset() {
	*x = GetWorkflowVersionRequest{}
	mi := &file_metarr_v1_workflows_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowVersionRequest) ProtoMessage() {}

func (x *GetWorkflowVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_workflows_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowVersionRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowVersionRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_workflows_proto_rawDescGZIP(), []int{7}
}

func (x *GetWorkflowVersionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetWorkflowVersionRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ListWorkflowVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowVersionsRequest) Reset() {
	*x = ListWorkflowVersionsRequest{}
	mi := &file_metarr_v1_workflows_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowVersionsRequest) ProtoMessage() {}

func (x *ListWorkflowVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_workflows_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowVersionsRequest) Descriptor() ([]byte, []int) {
	return file_metarr_v1_workflows_proto_rawDescGZIP(), []int{8}
}

func (x *ListWorkflowVersionsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListWorkflowVersionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkflowVersionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListWorkflowVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*Workflow            `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowVersionsResponse) Reset() {
	*x = ListWorkflowVersionsResponse{}
	mi := &file_metarr_v1_workflows_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowVersionsResponse) ProtoMessage() {}

func (x *ListWorkflowVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metarr_v1_workflows_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowVersionsResponse) Descriptor() ([]byte, []int) {
	return file_metarr_v1_workflows_proto_rawDescGZIP(), []int{9}
}

func (x *ListWorkflowVersionsResponse) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *ListWorkflowVersionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_metarr_v1_workflows_proto protoreflect.FileDescriptor

const file_metarr_v1_workflows_proto_rawDesc = "" +
	"\n" +
	"\x19metarr/v1/workflows.proto\x12\tmetarr.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1emetarr/v1/workflow_graph.proto\"\xef\x01\n" +
	"\bWorkflow\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12.\n" +
	"\x05graph\x18\b \x01(\v2\x18.metarr.v1.WorkflowGraphR\x05graphJ\x04\b\x01\x10\x02\"H\n" +
	"\x15CreateWorkflowRequest\x12/\n" +
	"\bworkflow\x18\x01 \x01(\v2\x13.metarr.v1.WorkflowR\bworkflow\"$\n" +
	"\x12GetWorkflowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x85\x01\n" +
	"\x14ListWorkflowsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"r\n" +
	"\x15ListWorkflowsResponse\x121\n" +
	"\tworkflows\x18\x01 \x03(\v2\x13.metarr.v1.WorkflowR\tworkflows\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x85\x01\n" +
	"\x15UpdateWorkflowRequest\x12/\n" +
	"\bworkflow\x18\x01 \x01(\v2\x13.metarr.v1.WorkflowR\bworkflow\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"'\n" +
	"\x15DeleteWorkflowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x19GetWorkflowVersionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"i\n" +
	"\x1bListWorkflowVersionsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"y\n" +
	"\x1cListWorkflowVersionsResponse\x121\n" +
	"\tworkflows\x18\x01 \x03(\v2\x13.metarr.v1.WorkflowR\tworkflows\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xc0\x04\n" +
	"\x0fWorkflowService\x12G\n" +
	"\x0eCreateWorkflow\x12 .metarr.v1.CreateWorkflowRequest\x1a\x13.metarr.v1.Workflow\x12A\n" +
	"\vGetWorkflow\x12\x1d.metarr.v1.GetWorkflowRequest\x1a\x13.metarr.v1.Workflow\x12R\n" +
	"\rListWorkflows\x12\x1f.metarr.v1.ListWorkflowsRequest\x1a .metarr.v1.ListWorkflowsResponse\x12G\n" +
	"\x0eUpdateWorkflow\x12 .metarr.v1.UpdateWorkflowRequest\x1a\x13.metarr.v1.Workflow\x12J\n" +
	"\x0eDeleteWorkflow\x12 .metarr.v1.DeleteWorkflowRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x12GetWorkflowVersion\x12$.metarr.v1.GetWorkflowVersionRequest\x1a\x13.metarr.v1.Workflow\x12g\n" +
	"\x14ListWorkflowVersions\x12&.metarr.v1.ListWorkflowVersionsRequest\x1a'.metarr.v1.ListWorkflowVersionsResponseB-Z+Metarr/internal/genproto/metarr/v1;metarrv1b\x06proto3"

var (
	file_metarr_v1_workflows_proto_rawDescOnce sync.Once
	file_metarr_v1_workflows_proto_rawDescData []byte
)

func file_metarr_v1_workflows_proto_rawDescGZIP() []byte {
	file_metarr_v1_workflows_proto_rawDescOnce.Do(func() {
		file_metarr_v1_workflows_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metarr_v1_workflows_proto_rawDesc), len(file_metarr_v1_workflows_proto_rawDesc)))
	})
	return file_metarr_v1_workflows_proto_rawDescData
}

var file_metarr_v1_workflows_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_metarr_v1_workflows_proto_goTypes = []any{
	(*Workflow)(nil),                     // 0: metarr.v1.Workflow
	(*CreateWorkflowRequest)(nil),        // 1: metarr.v1.CreateWorkflowRequest
	(*GetWorkflowRequest)(nil),           // 2: metarr.v1.GetWorkflowRequest
	(*ListWorkflowsRequest)(nil),         // 3: metarr.v1.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),        // 4: metarr.v1.ListWorkflowsResponse
	(*UpdateWorkflowRequest)(nil),        // 5: metarr.v1.UpdateWorkflowRequest
	(*DeleteWorkflowRequest)(nil),        // 6: metarr.v1.DeleteWorkflowRequest
	(*GetWorkflowVersionRequest)(nil),    // 7: metarr.v1.GetWorkflowVersionRequest
	(*ListWorkflowVersionsRequest)(nil),  // 8: metarr.v1.ListWorkflowVersionsRequest
	(*ListWorkflowVersionsResponse)(nil), // 9: metarr.v1.ListWorkflowVersionsResponse
	(*timestamppb.Timestamp)(nil),        // 10: google.protobuf.Timestamp
	(*WorkflowGraph)(nil),                // 11: metarr.v1.WorkflowGraph
	(*fieldmaskpb.FieldMask)(nil),        // 12: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                // 13: google.protobuf.Empty
}
var file_metarr_v1_workflows_proto_depIdxs = []int32{
	10, // 0: metarr.v1.Workflow.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: metarr.v1.Workflow.graph:type_name -> metarr.v1.WorkflowGraph
	0,  // 2: metarr.v1.CreateWorkflowRequest.workflow:type_name -> metarr.v1.Workflow
	0,  // 3: metarr.v1.ListWorkflowsResponse.workflows:type_name -> metarr.v1.Workflow
	0,  // 4: metarr.v1.UpdateWorkflowRequest.workflow:type_name -> metarr.v1.Workflow
	12, // 5: metarr.v1.UpdateWorkflowRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 6: metarr.v1.ListWorkflowVersionsResponse.workflows:type_name -> metarr.v1.Workflow
	1,  // 7: metarr.v1.WorkflowService.CreateWorkflow:input_type -> metarr.v1.CreateWorkflowRequest
	2,  // 8: metarr.v1.WorkflowService.GetWorkflow:input_type -> metarr.v1.GetWorkflowRequest
	3,  // 9: metarr.v1.WorkflowService.ListWorkflows:input_type -> metarr.v1.ListWorkflowsRequest
	5,  // 10: metarr.v1.WorkflowService.UpdateWorkflow:input_type -> metarr.v1.UpdateWorkflowRequest
	6,  // 11: metarr.v1.WorkflowService.DeleteWorkflow:input_type -> metarr.v1.DeleteWorkflowRequest
	7,  // 12: metarr.v1.WorkflowService.GetWorkflowVersion:input_type -> metarr.v1.GetWorkflowVersionRequest
	8,  // 13: metarr.v1.WorkflowService.ListWorkflowVersions:input_type -> metarr.v1.ListWorkflowVersionsRequest
	0,  // 14: metarr.v1.WorkflowService.CreateWorkflow:output_type -> metarr.v1.Workflow
	0,  // 15: metarr.v1.WorkflowService.GetWorkflow:output_type -> metarr.v1.Workflow
	4,  // 16: metarr.v1.WorkflowService.ListWorkflows:output_type -> metarr.v1.ListWorkflowsResponse
	0,  // 17: metarr.v1.WorkflowService.UpdateWorkflow:output_type -> metarr.v1.Workflow
	13, // 18: metarr.v1.WorkflowService.DeleteWorkflow:output_type -> google.protobuf.Empty
	0,  // 19: metarr.v1.WorkflowService.GetWorkflowVersion:output_type -> metarr.v1.Workflow
	9,  // 20: metarr.v1.WorkflowService.ListWorkflowVersions:output_type -> metarr.v1.ListWorkflowVersionsResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_metarr_v1_workflows_proto_init() }
func file_metarr_v1_workflows_proto_init() {
	if File_metarr_v1_workflows_proto != nil {
		return
	}
	file_metarr_v1_workflow_graph_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metarr_v1_workflows_proto_rawDesc), len(file_metarr_v1_workflows_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metarr_v1_workflows_proto_goTypes,
		DependencyIndexes: file_metarr_v1_workflows_proto_depIdxs,
		MessageInfos:      file_metarr_v1_workflows_proto_msgTypes,
	}.Build()
	File_metarr_v1_workflows_proto = out.File
	file_metarr_v1_workflows_proto_goTypes = nil
	file_metarr_v1_workflows_proto_depIdxs = nil
}
