// Command api runs the Metarr web API: an HTTP server backed by MongoDB for
// storage and Redis for both the Pub/Sub message queue (heartbeat) and the
// stream-based event bus (background task events).
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"connectrpc.com/grpcreflect"
	"github.com/google/uuid"

	metarrv1connect "Metarr/internal/genproto/metarr/v1/metarrv1connect"
	"Metarr/internal/server/agentregistry"
	"Metarr/internal/server/appconfigstore"
	"Metarr/internal/server/handlers"
	"Metarr/internal/server/httpserver"
	"Metarr/internal/server/listeners"
	"Metarr/internal/server/logforward"
	"Metarr/internal/server/logtail"
	"Metarr/internal/server/mongostore"
	"Metarr/internal/server/redisstats"
	"Metarr/internal/server/services"
	"Metarr/internal/server/session"
	"Metarr/internal/server/webui"
	workflowcatalog "Metarr/internal/server/workflow/catalog"
	"Metarr/internal/shared/appconfig"
	"Metarr/internal/shared/config"
	"Metarr/internal/shared/eventbus"
	"Metarr/internal/shared/logging"
	"Metarr/internal/shared/redisclient"
	"Metarr/internal/shared/scanmodel"
	"Metarr/internal/shared/version"
)

const (
	// defaultDirectoryScannerParallelCount is how many directories the
	// scanner processes concurrently when the config doesn't set its own
	// value yet.
	defaultDirectoryScannerParallelCount = 16

	// httpClientEnvFile is the JetBrains HTTP Client's per-developer
	// secrets file, kept in sync with freshly bootstrapped API keys if
	// the developer has one at the project root.
	httpClientEnvFile = "http-client.private.env.json"
)

// @title			Metarr API
// @version		1.0
// @description	Event-driven Go API backed by MongoDB and Redis. Every request carries a correlation ID (X-Correlation-ID), generated by the server if the caller doesn't supply one.
// @BasePath		/
//
// @securityDefinitions.apikey	ApiKeyHeaderAuth
// @in							header
// @name						X-Api-Key
// @description				API key via the X-Api-Key header.
//
// @securitydefinitions.apikey	ApiKeyQueryAuth
// @in							query
// @name						apikey
// @description				API key via the apikey query parameter. Either this or ApiKeyHeaderAuth satisfies auth on protected routes.
func main() {
	if err := run(); err != nil {
		slog.Error("fatal error", "error", err)
		os.Exit(1)
	}
}

func run() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	logger, logShipper := logging.New("metarr-server")

	logger.Info("server starting", "version", version.Raw)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	connectCtx, cancelConnect := context.WithTimeout(ctx, 10*time.Second)
	defer cancelConnect()

	mongoClient, err := mongostore.Connect(connectCtx, cfg.MongoURI)
	if err != nil {
		return err
	}
	defer func() { _ = mongoClient.Disconnect(context.Background()) }()

	redisClient, err := redisclient.New(connectCtx, cfg.RedisURI)
	if err != nil {
		return err
	}
	defer func() { _ = redisClient.Close() }()

	// Only now does a Redis connection exist to ship to. Everything logged
	// before this point, and anything logged if Redis later becomes
	// unreachable, still goes to stdout — Attach only adds the second
	// destination, never gates the first.
	logShipper.Attach(redisClient)

	pubsubBus := eventbus.NewPubSubBus(redisClient)
	streamBus, err := eventbus.NewStreamBus(redisClient, eventbus.NewSlogAdapter(logger))
	if err != nil {
		return err
	}
	taskEventRepo := mongostore.NewTaskEventRepo(mongoClient, cfg.MongoDatabase)
	appConfigRepo := mongostore.NewAppConfigRepo(mongoClient, cfg.MongoDatabase)
	appConfigStore := appconfigstore.New(appConfigRepo, appConfigRepo, streamBus)
	localDirectoryRepo := mongostore.NewLocalDirectoryRepo(mongoClient, cfg.MongoDatabase)
	workflowRepo := mongostore.NewWorkflowRepo(mongoClient, cfg.MongoDatabase)
	sessions := session.NewStore(redisClient)

	// The local_directory indexes include the unique index on path that makes a
	// rescan replace records rather than duplicate them, so a failure here is
	// fatal rather than merely slow.
	if err := localDirectoryRepo.EnsureIndexes(connectCtx); err != nil {
		return err
	}
	if err := workflowRepo.EnsureIndexes(connectCtx); err != nil {
		return err
	}

	// The node catalog is loaded once at startup and is fatal on failure: a
	// server that cannot read it can neither validate a workflow nor run
	// one, so starting up and failing later would only hide the problem.
	workflowCatalogLoader := workflowcatalog.NewLoader(cfg.WorkflowCatalogPath)
	workflowCatalog, err := workflowCatalogLoader.Load()
	if err != nil {
		return err
	}
	logger.Info("workflow catalog loaded",
		"path", workflowCatalogLoader.Path(),
		"node_types", workflowCatalog.Len(),
	)

	// Every block below seeds the application config through
	// appConfigStore.Bootstrap — a direct, synchronous write, not Mutate's
	// async event-fired one. Startup runs before the system_config_update
	// listener exists to persist a fired event, so bootstrap needs its own
	// contract; see docs/adr/0003. Each block reports whether it changed
	// anything, so an ordinary restart with nothing left to seed costs no
	// write.
	var bootstrappedKeys *appconfig.APIKeysConfig

	// Bootstrap the four API key categories the first time the app ever
	// starts against this database: none has been configured yet, so
	// generate one key per category. This used to be seeded by
	// mongo/init/init-mongo.js; it lives here instead so it can also sync
	// http-client.private.env.json, which only Go — not the mongo
	// container — has a normal filesystem path to.
	if err := appConfigStore.Bootstrap(connectCtx, func(cfg *appconfig.Config) (bool, error) {
		if len(cfg.APIKeys.Admin) != 0 || len(cfg.APIKeys.User) != 0 ||
			len(cfg.APIKeys.Webhook) != 0 || len(cfg.APIKeys.ReadOnly) != 0 {
			return false, nil
		}

		adminKey := uuid.NewString()
		userKey := uuid.NewString()
		webhookKey := uuid.NewString()
		readOnlyKey := uuid.NewString()

		cfg.APIKeys = appconfig.APIKeysConfig{
			Admin:    []appconfig.APIKeyEntry{{ID: uuid.NewString(), Name: "Administrator Key", Key: adminKey}},
			User:     []appconfig.APIKeyEntry{{ID: uuid.NewString(), Name: "User Key", Key: userKey}},
			Webhook:  []appconfig.APIKeyEntry{{ID: uuid.NewString(), Name: "Webhook Key", Key: webhookKey}},
			ReadOnly: []appconfig.APIKeyEntry{{ID: uuid.NewString(), Name: "Read Only Key", Key: readOnlyKey}},
		}
		bootstrappedKeys = &cfg.APIKeys

		fmt.Println("==================================================================")
		fmt.Println("Metarr: generated default API keys (shown only once, save these):")
		fmt.Println("  admin:     " + adminKey)
		fmt.Println("  user:      " + userKey)
		fmt.Println("  webhook:   " + webhookKey)
		fmt.Println("  read_only: " + readOnlyKey)
		fmt.Println("==================================================================")
		return true, nil
	}); err != nil {
		return err
	}

	// Seeds the admin account on a fresh install, or recovers one left
	// locked out by the whole-document config update bug ADR 0001 removed —
	// both cases, and the order between them, live behind this one call now
	// instead of two separate blocks. See docs/adr/0003.
	adminSeed, err := appConfigStore.SeedAdmin(connectCtx)
	if err != nil {
		return err
	}
	newAdminPassword := adminSeed.Password
	switch {
	case adminSeed.Recovered:
		fmt.Println("==================================================================")
		fmt.Println("Metarr: admin credentials were missing (a prior version could zero")
		fmt.Println("them when editing an API key) — generated a new password:")
		fmt.Println("  username: " + adminSeed.Username)
		fmt.Println("  password: " + adminSeed.Password)
		fmt.Println("==================================================================")
	case adminSeed.Password != "":
		fmt.Println("==================================================================")
		fmt.Println("Metarr: generated initial admin credentials (shown only once):")
		fmt.Println("  username: " + adminSeed.Username)
		fmt.Println("  password: " + adminSeed.Password)
		fmt.Println("==================================================================")
	}

	// Bootstrap the directory scanner config the first time the app starts
	// against this database (a fresh install, or an existing database
	// predating the directory_scanner section): default to 16 parallel
	// workers and no directories configured to scan yet.
	if err := appConfigStore.Bootstrap(connectCtx, func(cfg *appconfig.Config) (bool, error) {
		if cfg.DirectoryScanner.ParallelCount != 0 {
			return false, nil
		}
		cfg.DirectoryScanner = appconfig.DirectoryScannerConfig{
			ParallelCount:   defaultDirectoryScannerParallelCount,
			ScanDirectories: []appconfig.ScanDirectory{},
		}
		return true, nil
	}); err != nil {
		return err
	}

	// Seed the sidecar classification table the first time the app starts
	// against this database, on the same "fresh install, or a database
	// predating this section" reasoning as the block above. An empty table
	// would classify nothing, so this is what makes the built-in rules the
	// starting point a user then edits.
	if err := appConfigStore.Bootstrap(connectCtx, func(cfg *appconfig.Config) (bool, error) {
		if len(cfg.DirectoryScanner.SidecarTypes) != 0 {
			return false, nil
		}
		cfg.DirectoryScanner.SidecarTypes = appconfig.DefaultSidecarTypes()
		return true, nil
	}); err != nil {
		return err
	}

	// Agents start as an empty list rather than being seeded with anything: an
	// agent exists because someone deployed one and then said what it may see,
	// and inventing a default would mean guessing at a machine that may not be
	// there. A database predating this field decodes it as nil, so it is
	// normalised here to keep the API returning [] rather than null.
	if err := appConfigStore.Bootstrap(connectCtx, func(cfg *appconfig.Config) (bool, error) {
		if cfg.Agents != nil {
			return false, nil
		}
		cfg.Agents = []appconfig.AgentConfig{}
		return true, nil
	}); err != nil {
		return err
	}

	// A database predating the logging pipeline has no server_level at all,
	// which would leave the level threshold unset (zero value, meaning every
	// level including Debug — the opposite of the quiet default a fresh
	// install gets from appconfig.Default()).
	if err := appConfigStore.Bootstrap(connectCtx, func(cfg *appconfig.Config) (bool, error) {
		if cfg.Logging.ServerLevel != "" {
			return false, nil
		}
		cfg.Logging = appconfig.Default().Logging
		return true, nil
	}); err != nil {
		return err
	}

	// A built-in type added after this database was seeded would otherwise never
	// reach it, since the seed above only fires on an empty table. Note this
	// also means a built-in deleted through the API comes back on the next
	// restart: a deletion leaves nothing behind to tell it apart from a type the
	// table has simply never seen.
	if err := appConfigStore.Bootstrap(connectCtx, func(cfg *appconfig.Config) (bool, error) {
		merged, added := appconfig.MergeMissingSidecarTypes(cfg.DirectoryScanner.SidecarTypes)
		if added == 0 {
			return false, nil
		}
		cfg.DirectoryScanner.SidecarTypes = merged
		logger.Info("added built-in sidecar types missing from the stored table", "count", added)
		return true, nil
	}); err != nil {
		return err
	}

	// API key entries stored before the id field existed decode with an
	// empty one, which would leave them unaddressable by the scoped
	// upsert/delete operations that key on it. Minting here, once, makes
	// "every entry has an id" true everywhere downstream instead of
	// conditional on when the entry was created.
	if err := appConfigStore.Bootstrap(connectCtx, func(cfg *appconfig.Config) (bool, error) {
		minted := appconfig.BackfillAPIKeyIDs(&cfg.APIKeys)
		if minted == 0 {
			return false, nil
		}
		logger.Info("minted ids for API key entries stored before the id field existed", "count", minted)
		return true, nil
	}); err != nil {
		return err
	}

	if bootstrappedKeys != nil || newAdminPassword != "" {
		if err := syncHTTPClientEnv(bootstrappedKeys, newAdminPassword); err != nil {
			logger.Error("failed to sync http-client.private.env.json", "error", err)
		}
	}

	// Warm the in-memory config singleton from MongoDB before serving any
	// requests, so it reflects every bootstrap write above.
	startupCfg, err := appConfigStore.Read(connectCtx)
	if err != nil {
		return err
	}
	appconfig.Set(startupCfg)

	// Compile the stored sidecar table into the registry the scanner reads.
	// A bad pattern here is a stored-configuration problem, not a reason to
	// refuse to boot: log it and carry on with the built-in defaults the
	// package installed at init, which at least leaves the scanner working
	// while someone fixes the document.
	if registry, err := scanmodel.NewSidecarRegistry(startupCfg.DirectoryScanner.SidecarTypes); err != nil {
		logger.Error("stored sidecar type table is invalid; using built-in defaults", "error", err)
	} else {
		scanmodel.SetSidecarRegistry(registry)
	}

	// Listeners run for the lifetime of the process, independent of any
	agentRegistry := agentregistry.New(redisClient, logger)

	// Publish each agent's configuration before anything else starts, so an
	// agent that is already connected picks up its mapping without waiting for
	// the first config change.
	if err := agentRegistry.PublishAll(connectCtx, startupCfg); err != nil {
		logger.Warn("could not publish agent configuration at startup", "error", err)
	}

	// single HTTP request.
	go listeners.RunHeartbeatListener(ctx, pubsubBus, logger)
	go func() {
		if err := listeners.RunSonarrCacheDataListener(ctx, streamBus, taskEventRepo, logger); err != nil && ctx.Err() == nil {
			logger.Error("sonarr_cache_data listener stopped unexpectedly", "error", err)
		}
	}()
	go func() {
		if err := listeners.RunSystemConfigUpdateListener(ctx, streamBus, appConfigRepo, agentRegistry, logShipper, logger); err != nil && ctx.Err() == nil {
			logger.Error("system_config_update listener stopped unexpectedly", "error", err)
		}
	}()
	// Scanning itself now happens on the agents; what runs here is the half
	// that persists what they report.
	go func() {
		if err := listeners.RunAgentScanResultListener(ctx, streamBus, localDirectoryRepo, logger); err != nil && ctx.Err() == nil {
			logger.Error("agent scan result listener stopped unexpectedly", "error", err)
		}
	}()

	statsCollector := redisstats.New(redisClient)

	// The live tail on the Logging screen. The buffer holds records from
	// every process publishing to eventbus.LogChannel — this server included
	// — regardless of which one is running the listener that fills it.
	logTailBuffer := logtail.NewBuffer(200)
	go listeners.RunLogTailListener(ctx, pubsubBus, logTailBuffer, logger)

	// The one hop that leaves Metarr's own infrastructure: forwarding to
	// Fluent Bit, which ships on to OpenObserve (or whatever it's configured
	// for). Optional — a deployment with no Fluent Bit set in config.yaml
	// simply skips this, and logging still works everywhere else.
	if cfg.LogForwardURL != "" {
		forwarder := logforward.New(cfg.LogForwardURL)
		go forwarder.Run(ctx)
		go listeners.RunLogForwardListener(ctx, pubsubBus, forwarder, logger)
	}

	// The streaming layer: stats.redis, agents.presence and logging.tail all
	// migrated to their own server-streaming gRPC-Web RPCs — see
	// metarr.v1.StatsService.Stream, metarr.v1.AgentService.StreamPresence,
	// metarr.v1.LoggingService.StreamTail (internal/server/services), mounted
	// via connectServices below. wsbus.Hub and GET /api/ws are retired.

	apiHandlers := handlers.New(pubsubBus, streamBus, appConfigRepo, appConfigStore, localDirectoryRepo, workflowRepo, workflowCatalog, sessions, statsCollector, agentRegistry, logTailBuffer, logger, cfg.HeartbeatTimeout)
	uiFS, uiEmbedded := webui.FS()
	if uiEmbedded {
		logger.Info("ui embed", "enabled", true)
	}

	// gRPC-Web (Connect) services, migrated off internal/server/handlers one
	// domain at a time — see the REST->gRPC-Web migration plan. Each entry's
	// path comes from its generated NewXServiceHandler; router.go just mounts
	// whatever's in this slice, so a new domain never touches router.go.
	connectServices := []httpserver.ConnectService{
		newConnectService[metarrv1connect.SonarrInterfaceServiceHandler](
			metarrv1connect.NewSonarrInterfaceServiceHandler,
			&services.SonarrInterfaceServer{Handlers: apiHandlers},
			sessions,
			services.SonarrInterfaceAuthPolicies,
		),
		newConnectService[metarrv1connect.AuthServiceHandler](
			metarrv1connect.NewAuthServiceHandler,
			&services.AuthServer{Handlers: apiHandlers},
			sessions,
			services.AuthAuthPolicies,
			httpserver.NewConnectRateLimitInterceptor(map[string]time.Duration{
				"Login":  httpserver.ThrottledInterval,
				"Logout": httpserver.ThrottledInterval,
			}),
		),
		newConnectService[metarrv1connect.ConfigServiceHandler](
			metarrv1connect.NewConfigServiceHandler,
			&services.ConfigServer{Handlers: apiHandlers},
			sessions,
			services.ConfigAuthPolicies,
		),
		newConnectService[metarrv1connect.AgentServiceHandler](
			metarrv1connect.NewAgentServiceHandler,
			&services.AgentServer{Handlers: apiHandlers},
			sessions,
			services.AgentAuthPolicies,
		),
		newConnectService[metarrv1connect.DirectoryScannerServiceHandler](
			metarrv1connect.NewDirectoryScannerServiceHandler,
			&services.DirectoryScannerServer{Handlers: apiHandlers},
			sessions,
			services.DirectoryScannerAuthPolicies,
		),
		newConnectService[metarrv1connect.LoggingServiceHandler](
			metarrv1connect.NewLoggingServiceHandler,
			&services.LoggingServer{Handlers: apiHandlers},
			sessions,
			services.LoggingAuthPolicies,
		),
		newConnectService[metarrv1connect.TaskServiceHandler](
			metarrv1connect.NewTaskServiceHandler,
			&services.TaskServer{Handlers: apiHandlers},
			sessions,
			services.TaskAuthPolicies,
		),
		newConnectService[metarrv1connect.WorkflowCatalogServiceHandler](
			metarrv1connect.NewWorkflowCatalogServiceHandler,
			&services.WorkflowCatalogServer{Handlers: apiHandlers},
			sessions,
			services.WorkflowCatalogAuthPolicies,
		),
		newConnectService[metarrv1connect.LocalDirectoryServiceHandler](
			metarrv1connect.NewLocalDirectoryServiceHandler,
			&services.LocalDirectoryServer{Handlers: apiHandlers},
			sessions,
			services.LocalDirectoryAuthPolicies,
		),
		newConnectService[metarrv1connect.WorkflowServiceHandler](
			metarrv1connect.NewWorkflowServiceHandler,
			&services.WorkflowServer{Handlers: apiHandlers},
			sessions,
			services.WorkflowAuthPolicies,
		),
		newConnectService[metarrv1connect.StatsServiceHandler](
			metarrv1connect.NewStatsServiceHandler,
			&services.StatsServer{Handlers: apiHandlers},
			sessions,
			services.StatsAuthPolicies,
		),
	}

	// gRPC server reflection — lets grpcurl/grpcui/Postman introspect and call
	// any migrated service without needing the .proto files locally. One
	// name per service registered above; grows the same way connectServices
	// does as domains migrate. Both v1 and v1alpha are mounted since not
	// every client has caught up to the finalized v1 reflection API yet.
	reflector := grpcreflect.NewStaticReflector(
		metarrv1connect.SonarrInterfaceServiceName,
		metarrv1connect.AuthServiceName,
		metarrv1connect.ConfigServiceName,
		metarrv1connect.AgentServiceName,
		metarrv1connect.DirectoryScannerServiceName,
		metarrv1connect.LoggingServiceName,
		metarrv1connect.TaskServiceName,
		metarrv1connect.WorkflowCatalogServiceName,
		metarrv1connect.LocalDirectoryServiceName,
		metarrv1connect.WorkflowServiceName,
		metarrv1connect.StatsServiceName,
	)
	reflectPathV1, reflectHandlerV1 := grpcreflect.NewHandlerV1(reflector)
	reflectPathV1Alpha, reflectHandlerV1Alpha := grpcreflect.NewHandlerV1Alpha(reflector)
	connectServices = append(connectServices,
		httpserver.ConnectService{Path: reflectPathV1, Handler: reflectHandlerV1},
		httpserver.ConnectService{Path: reflectPathV1Alpha, Handler: reflectHandlerV1Alpha},
	)

	router := httpserver.NewRouter(apiHandlers, sessions, logger, uiFS, connectServices)
	server := httpserver.New(cfg.Host, cfg.Port, router)

	serverErr := make(chan error, 1)
	go func() {
		logger.Info("server starting", "host", cfg.Host, "port", cfg.Port)
		if err := server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			serverErr <- err
			return
		}
		serverErr <- nil
	}()

	select {
	case <-ctx.Done():
		logger.Info("shutdown signal received")
	case err := <-serverErr:
		if err != nil {
			return err
		}
	}

	shutdownCtx, cancelShutdown := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancelShutdown()
	return server.Shutdown(shutdownCtx)
}

// syncHTTPClientEnv updates the JetBrains HTTP Client's per-developer
// secrets file with whichever of the freshly bootstrapped API keys or
// admin password apply this run — apiKeys is nil, or adminPassword is "",
// when that part wasn't (re)generated — if the developer has one at the
// project root; it's a no-op, not an error, if the file doesn't exist.
// One read and one write handle both fields together, rather than the
// caller sync-ing each separately. The file is read as a generic map
// rather than a typed struct because it's IDE-managed and carries fields
// Go doesn't own — a generic round-trip only touches the fields this call
// was asked to set and leaves everything else exactly as it was.
func syncHTTPClientEnv(apiKeys *appconfig.APIKeysConfig, adminPassword string) error {
	data, err := os.ReadFile(httpClientEnvFile)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("reading %s: %w", httpClientEnvFile, err)
	}

	var envFile map[string]any
	if err := json.Unmarshal(data, &envFile); err != nil {
		return fmt.Errorf("parsing %s: %w", httpClientEnvFile, err)
	}

	local, _ := envFile["local"].(map[string]any)
	if local == nil {
		local = map[string]any{}
	}
	if apiKeys != nil {
		local["api_key_admin"] = apiKeys.Admin[0].Key
		local["api_key_user"] = apiKeys.User[0].Key
		local["api_key_webhook"] = apiKeys.Webhook[0].Key
		local["api_key_read_only"] = apiKeys.ReadOnly[0].Key
	}
	if adminPassword != "" {
		local["admin_pass"] = adminPassword
	}
	envFile["local"] = local

	updated, err := json.MarshalIndent(envFile, "", "  ")
	if err != nil {
		return fmt.Errorf("encoding %s: %w", httpClientEnvFile, err)
	}
	if err := os.WriteFile(httpClientEnvFile, append(updated, '\n'), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", httpClientEnvFile, err)
	}

	fmt.Println("Metarr: synced " + httpClientEnvFile + ".")
	return nil
}
