// Command api runs the Metarr web API: an HTTP server backed by MongoDB for
// storage and Redis for both the Pub/Sub message queue (heartbeat) and the
// stream-based event bus (background task events).
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"connectrpc.com/grpcreflect"

	metarrv1connect "Metarr/internal/genproto/metarr/v1/metarrv1connect"
	"Metarr/internal/server/agentregistry"
	"Metarr/internal/server/appconfigstore"
	"Metarr/internal/server/bootstrap"
	"Metarr/internal/server/handlers"
	"Metarr/internal/server/httpserver"
	"Metarr/internal/server/listeners"
	"Metarr/internal/server/logforward"
	"Metarr/internal/server/logtail"
	"Metarr/internal/server/mongostore"
	"Metarr/internal/server/redisstats"
	"Metarr/internal/server/services"
	"Metarr/internal/server/session"
	"Metarr/internal/server/webui"
	workflowcatalog "Metarr/internal/server/workflow/catalog"
	"Metarr/internal/shared/appconfig"
	"Metarr/internal/shared/config"
	"Metarr/internal/shared/eventbus"
	"Metarr/internal/shared/logging"
	"Metarr/internal/shared/redisclient"
	"Metarr/internal/shared/scanmodel"
	"Metarr/internal/shared/version"
)

// httpClientEnvFile is the JetBrains HTTP Client's per-developer secrets
// file, kept in sync with freshly bootstrapped API keys if the developer
// has one at the project root.
const httpClientEnvFile = "http-client.private.env.json"

// @title			Metarr API
// @version		1.0
// @description	Event-driven Go API backed by MongoDB and Redis. Every request carries a correlation ID (X-Correlation-ID), generated by the server if the caller doesn't supply one.
// @BasePath		/
//
// @securityDefinitions.apikey	ApiKeyHeaderAuth
// @in							header
// @name						X-Api-Key
// @description				API key via the X-Api-Key header.
//
// @securitydefinitions.apikey	ApiKeyQueryAuth
// @in							query
// @name						apikey
// @description				API key via the apikey query parameter. Either this or ApiKeyHeaderAuth satisfies auth on protected routes.
func main() {
	if err := run(); err != nil {
		slog.Error("fatal error", "error", err)
		os.Exit(1)
	}
}

func run() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	logger, logShipper := logging.New("metarr-server")

	logger.Info("server starting", "version", version.Raw)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	connectCtx, cancelConnect := context.WithTimeout(ctx, 10*time.Second)
	defer cancelConnect()

	mongoClient, err := mongostore.Connect(connectCtx, cfg.MongoURI)
	if err != nil {
		return err
	}
	defer func() { _ = mongoClient.Disconnect(context.Background()) }()

	redisClient, err := redisclient.New(connectCtx, cfg.RedisURI)
	if err != nil {
		return err
	}
	defer func() { _ = redisClient.Close() }()

	// Only now does a Redis connection exist to ship to. Everything logged
	// before this point, and anything logged if Redis later becomes
	// unreachable, still goes to stdout — Attach only adds the second
	// destination, never gates the first.
	logShipper.Attach(redisClient)

	pubsubBus := eventbus.NewPubSubBus(redisClient)
	streamBus, err := eventbus.NewStreamBus(redisClient, eventbus.NewSlogAdapter(logger))
	if err != nil {
		return err
	}
	appConfigRepo := mongostore.NewAppConfigRepo(mongoClient, cfg.MongoDatabase)
	appConfigStore := appconfigstore.New(appConfigRepo, appConfigRepo, streamBus)
	localDirectoryRepo := mongostore.NewLocalDirectoryRepo(mongoClient, cfg.MongoDatabase)
	workflowRepo := mongostore.NewWorkflowRepo(mongoClient, cfg.MongoDatabase)
	sessions := session.NewStore(redisClient)

	// The local_directory indexes include the unique index on path that makes a
	// rescan replace records rather than duplicate them, so a failure here is
	// fatal rather than merely slow.
	if err := localDirectoryRepo.EnsureIndexes(connectCtx); err != nil {
		return err
	}
	if err := workflowRepo.EnsureIndexes(connectCtx); err != nil {
		return err
	}

	// The node catalog is loaded once at startup and is fatal on failure: a
	// server that cannot read it can neither validate a workflow nor run
	// one, so starting up and failing later would only hide the problem.
	workflowCatalogLoader := workflowcatalog.NewLoader(cfg.WorkflowCatalogPath)
	workflowCatalog, err := workflowCatalogLoader.Load()
	if err != nil {
		return err
	}
	logger.Info("workflow catalog loaded",
		"path", workflowCatalogLoader.Path(),
		"node_types", workflowCatalog.Len(),
	)

	// Seeds the application config — API keys, the admin account,
	// directory-scanner defaults, the sidecar classification table, and the
	// one-time backfills earlier releases needed. Runs synchronously,
	// straight to storage, before the system_config_update listener exists
	// to persist a fired event; see docs/adr/0003 and docs/adr/0004. An
	// ordinary restart with nothing left to seed costs no write.
	bootstrapReport, err := bootstrap.Run(connectCtx, appConfigStore)
	if err != nil {
		return err
	}

	if bootstrapReport.APIKeys != nil {
		fmt.Println("==================================================================")
		fmt.Println("Metarr: generated default API keys (shown only once, save these):")
		fmt.Println("  admin:     " + bootstrapReport.APIKeys.Admin[0].ApiKey)
		fmt.Println("  user:      " + bootstrapReport.APIKeys.User[0].ApiKey)
		fmt.Println("  webhook:   " + bootstrapReport.APIKeys.Webhook[0].ApiKey)
		fmt.Println("  read_only: " + bootstrapReport.APIKeys.ReadOnly[0].ApiKey)
		fmt.Println("==================================================================")
	}
	switch {
	case bootstrapReport.Admin.Recovered:
		fmt.Println("==================================================================")
		fmt.Println("Metarr: admin credentials were missing (a prior version could zero")
		fmt.Println("them when editing an API key) — generated a new password:")
		fmt.Println("  username: " + bootstrapReport.Admin.Username)
		fmt.Println("  password: " + bootstrapReport.Admin.Password)
		fmt.Println("==================================================================")
	case bootstrapReport.Admin.Password != "":
		fmt.Println("==================================================================")
		fmt.Println("Metarr: generated initial admin credentials (shown only once):")
		fmt.Println("  username: " + bootstrapReport.Admin.Username)
		fmt.Println("  password: " + bootstrapReport.Admin.Password)
		fmt.Println("==================================================================")
	}
	if bootstrapReport.SidecarTypesAdded > 0 {
		logger.Info("added built-in sidecar types missing from the stored table", "count", bootstrapReport.SidecarTypesAdded)
	}
	if bootstrapReport.APIKeyIDsBackfilled > 0 {
		logger.Info("minted ids for API key entries stored before the id field existed", "count", bootstrapReport.APIKeyIDsBackfilled)
	}

	if bootstrapReport.APIKeys != nil || bootstrapReport.Admin.Password != "" {
		if err := syncHTTPClientEnv(bootstrapReport.APIKeys, bootstrapReport.Admin.Password); err != nil {
			logger.Error("failed to sync http-client.private.env.json", "error", err)
		}
	}

	// Warm the in-memory config singleton from bootstrapReport.FinalConfig,
	// not a fresh Read — bootstrap.Run already read this exact document
	// from Mongo while seeding it, so re-reading it here would just be a
	// second round trip to reconstruct state already in hand.
	startupCfg := bootstrapReport.FinalConfig
	appconfig.Set(startupCfg)

	// Compile the stored sidecar table into the registry the scanner reads.
	// A bad pattern here is a stored-configuration problem, not a reason to
	// refuse to boot: log it and carry on with the built-in defaults the
	// package installed at init, which at least leaves the scanner working
	// while someone fixes the document.
	if registry, err := scanmodel.NewSidecarRegistry(startupCfg.DirectoryScanner.SidecarTypes); err != nil {
		logger.Error("stored sidecar type table is invalid; using built-in defaults", "error", err)
	} else {
		scanmodel.SetSidecarRegistry(registry)
	}

	// Listeners run for the lifetime of the process, independent of any
	agentRegistry := agentregistry.New(redisClient, logger)

	// Publish each agent's configuration before anything else starts, so an
	// agent that is already connected picks up its mapping without waiting for
	// the first config change.
	if err := agentRegistry.PublishAll(connectCtx, startupCfg); err != nil {
		logger.Warn("could not publish agent configuration at startup", "error", err)
	}

	// single HTTP request.
	go listeners.RunHeartbeatListener(ctx, pubsubBus, logger)

	// Every durable stream this process consumes runs under one Watermill
	// Router with the Recoverer/PoisonQueue/Retry middleware stack: a handler
	// that errors past the retry cap is parked on events.dead_letter and
	// acked, instead of redelivering forever (docs/adr/0006). Scanning itself
	// now happens on the agents; the scan-result listener is the half that
	// persists what they report.
	eventRouter, err := eventbus.NewRedisRouter(redisClient, eventbus.DefaultRetryPolicy(), eventbus.NewSlogAdapter(logger))
	if err != nil {
		return err
	}
	if err := listeners.RegisterSystemConfigUpdateListener(eventRouter, appConfigRepo, agentRegistry, logShipper, logger); err != nil {
		return err
	}
	if err := listeners.RegisterAgentScanResultListener(eventRouter, localDirectoryRepo, logger); err != nil {
		return err
	}
	go func() {
		if err := eventRouter.Run(ctx); err != nil && ctx.Err() == nil {
			logger.Error("event router stopped unexpectedly", "error", err)
		}
	}()

	statsCollector := redisstats.New(redisClient)

	// The live tail on the Logging screen. The buffer holds records from
	// every process publishing to eventbus.LogChannel — this server included
	// — regardless of which one is running the listener that fills it.
	logTailBuffer := logtail.NewBuffer(200)
	go listeners.RunLogTailListener(ctx, pubsubBus, logTailBuffer, logger)

	// The one hop that leaves Metarr's own infrastructure: forwarding to
	// Fluent Bit, which ships on to OpenObserve (or whatever it's configured
	// for). Optional — a deployment with no Fluent Bit set in config.yaml
	// simply skips this, and logging still works everywhere else.
	if cfg.LogForwardURL != "" {
		forwarder := logforward.New(cfg.LogForwardURL)
		go forwarder.Run(ctx)
		go listeners.RunLogForwardListener(ctx, pubsubBus, forwarder, logger)
	}

	// The streaming layer: stats.redis, agents.presence and logging.tail all
	// migrated to their own server-streaming gRPC-Web RPCs — see
	// metarr.v1.StatsService.Stream, metarr.v1.AgentService.StreamPresence,
	// metarr.v1.LoggingService.StreamTail (internal/server/services), mounted
	// via connectServices below. wsbus.Hub and GET /api/ws are retired.

	apiHandlers := handlers.New(pubsubBus, streamBus, appConfigStore, localDirectoryRepo, workflowRepo, workflowCatalog, sessions, statsCollector, agentRegistry, logTailBuffer, logger, cfg.HeartbeatTimeout)
	uiFS, uiEmbedded := webui.FS()
	if uiEmbedded {
		logger.Info("ui embed", "enabled", true)
	}

	// gRPC-Web (Connect) services, migrated off internal/server/handlers one
	// domain at a time — see the REST->gRPC-Web migration plan. Each entry's
	// path comes from its generated NewXServiceHandler; router.go just mounts
	// whatever's in this slice, so a new domain never touches router.go.
	connectServices := []httpserver.ConnectService{
		newConnectService[metarrv1connect.SonarrInterfaceServiceHandler](
			metarrv1connect.NewSonarrInterfaceServiceHandler,
			&services.SonarrInterfaceServer{Handlers: apiHandlers},
			sessions,
			services.SonarrInterfaceAuthPolicies,
		),
		newConnectService[metarrv1connect.AuthServiceHandler](
			metarrv1connect.NewAuthServiceHandler,
			&services.AuthServer{Handlers: apiHandlers},
			sessions,
			services.AuthAuthPolicies,
			httpserver.NewConnectRateLimitInterceptor(map[string]time.Duration{
				"Login":  httpserver.ThrottledInterval,
				"Logout": httpserver.ThrottledInterval,
			}),
		),
		newConnectService[metarrv1connect.ConfigServiceHandler](
			metarrv1connect.NewConfigServiceHandler,
			&services.ConfigServer{Handlers: apiHandlers},
			sessions,
			services.ConfigAuthPolicies,
		),
		newConnectService[metarrv1connect.AgentServiceHandler](
			metarrv1connect.NewAgentServiceHandler,
			&services.AgentServer{Handlers: apiHandlers},
			sessions,
			services.AgentAuthPolicies,
		),
		newConnectService[metarrv1connect.DirectoryScannerServiceHandler](
			metarrv1connect.NewDirectoryScannerServiceHandler,
			&services.DirectoryScannerServer{Handlers: apiHandlers},
			sessions,
			services.DirectoryScannerAuthPolicies,
		),
		newConnectService[metarrv1connect.LoggingServiceHandler](
			metarrv1connect.NewLoggingServiceHandler,
			&services.LoggingServer{Handlers: apiHandlers},
			sessions,
			services.LoggingAuthPolicies,
		),
		newConnectService[metarrv1connect.TaskServiceHandler](
			metarrv1connect.NewTaskServiceHandler,
			&services.TaskServer{Handlers: apiHandlers},
			sessions,
			services.TaskAuthPolicies,
		),
		newConnectService[metarrv1connect.WorkflowCatalogServiceHandler](
			metarrv1connect.NewWorkflowCatalogServiceHandler,
			&services.WorkflowCatalogServer{Handlers: apiHandlers},
			sessions,
			services.WorkflowCatalogAuthPolicies,
		),
		newConnectService[metarrv1connect.LocalDirectoryServiceHandler](
			metarrv1connect.NewLocalDirectoryServiceHandler,
			&services.LocalDirectoryServer{Handlers: apiHandlers},
			sessions,
			services.LocalDirectoryAuthPolicies,
		),
		newConnectService[metarrv1connect.WorkflowServiceHandler](
			metarrv1connect.NewWorkflowServiceHandler,
			&services.WorkflowServer{Handlers: apiHandlers},
			sessions,
			services.WorkflowAuthPolicies,
		),
		newConnectService[metarrv1connect.StatsServiceHandler](
			metarrv1connect.NewStatsServiceHandler,
			&services.StatsServer{Handlers: apiHandlers},
			sessions,
			services.StatsAuthPolicies,
		),
	}

	// gRPC server reflection — lets grpcurl/grpcui/Postman introspect and call
	// any migrated service without needing the .proto files locally. One
	// name per service registered above; grows the same way connectServices
	// does as domains migrate. Both v1 and v1alpha are mounted since not
	// every client has caught up to the finalized v1 reflection API yet.
	reflector := grpcreflect.NewStaticReflector(
		metarrv1connect.SonarrInterfaceServiceName,
		metarrv1connect.AuthServiceName,
		metarrv1connect.ConfigServiceName,
		metarrv1connect.AgentServiceName,
		metarrv1connect.DirectoryScannerServiceName,
		metarrv1connect.LoggingServiceName,
		metarrv1connect.TaskServiceName,
		metarrv1connect.WorkflowCatalogServiceName,
		metarrv1connect.LocalDirectoryServiceName,
		metarrv1connect.WorkflowServiceName,
		metarrv1connect.StatsServiceName,
	)
	reflectPathV1, reflectHandlerV1 := grpcreflect.NewHandlerV1(reflector)
	reflectPathV1Alpha, reflectHandlerV1Alpha := grpcreflect.NewHandlerV1Alpha(reflector)
	connectServices = append(connectServices,
		httpserver.ConnectService{Path: reflectPathV1, Handler: reflectHandlerV1},
		httpserver.ConnectService{Path: reflectPathV1Alpha, Handler: reflectHandlerV1Alpha},
	)

	router := httpserver.NewRouter(apiHandlers, sessions, logger, uiFS, connectServices)
	server := httpserver.New(cfg.Host, cfg.Port, router)

	serverErr := make(chan error, 1)
	go func() {
		logger.Info("server starting", "host", cfg.Host, "port", cfg.Port)
		if err := server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			serverErr <- err
			return
		}
		serverErr <- nil
	}()

	select {
	case <-ctx.Done():
		logger.Info("shutdown signal received")
	case err := <-serverErr:
		if err != nil {
			return err
		}
	}

	shutdownCtx, cancelShutdown := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancelShutdown()
	return server.Shutdown(shutdownCtx)
}

// syncHTTPClientEnv updates the JetBrains HTTP Client's per-developer
// secrets file with whichever of the freshly bootstrapped API keys or
// admin password apply this run — apiKeys is nil, or adminPassword is "",
// when that part wasn't (re)generated — if the developer has one at the
// project root; it's a no-op, not an error, if the file doesn't exist.
// One read and one write handle both fields together, rather than the
// caller sync-ing each separately. The file is read as a generic map
// rather than a typed struct because it's IDE-managed and carries fields
// Go doesn't own — a generic round-trip only touches the fields this call
// was asked to set and leaves everything else exactly as it was.
func syncHTTPClientEnv(apiKeys *appconfig.APIKeysConfig, adminPassword string) error {
	data, err := os.ReadFile(httpClientEnvFile)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("reading %s: %w", httpClientEnvFile, err)
	}

	var envFile map[string]any
	if err := json.Unmarshal(data, &envFile); err != nil {
		return fmt.Errorf("parsing %s: %w", httpClientEnvFile, err)
	}

	local, _ := envFile["local"].(map[string]any)
	if local == nil {
		local = map[string]any{}
	}
	if apiKeys != nil {
		local["api_key_admin"] = apiKeys.Admin[0].ApiKey
		local["api_key_user"] = apiKeys.User[0].ApiKey
		local["api_key_webhook"] = apiKeys.Webhook[0].ApiKey
		local["api_key_read_only"] = apiKeys.ReadOnly[0].ApiKey
	}
	if adminPassword != "" {
		local["admin_pass"] = adminPassword
	}
	envFile["local"] = local

	updated, err := json.MarshalIndent(envFile, "", "  ")
	if err != nil {
		return fmt.Errorf("encoding %s: %w", httpClientEnvFile, err)
	}
	if err := os.WriteFile(httpClientEnvFile, append(updated, '\n'), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", httpClientEnvFile, err)
	}

	fmt.Println("Metarr: synced " + httpClientEnvFile + ".")
	return nil
}
