// Command api runs the Metarr web API: an HTTP server backed by MongoDB for
// storage and Redis for both the Pub/Sub message queue (heartbeat) and the
// stream-based event bus (background task events).
package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/google/uuid"

	"Metarr/internal/appconfig"
	"Metarr/internal/config"
	"Metarr/internal/eventbus"
	"Metarr/internal/handlers"
	"Metarr/internal/httpserver"
	"Metarr/internal/listeners"
	"Metarr/internal/logging"
	"Metarr/internal/mediascan"
	"Metarr/internal/mongostore"
	"Metarr/internal/passwordhash"
	"Metarr/internal/redisclient"
	"Metarr/internal/session"
)

const (
	defaultAdminUsername      = "admin"
	defaultAdminEmail         = "admin@example.com"
	defaultAdminPasswordChars = 12

	// defaultDirectoryScannerParallelCount is how many directories the
	// scanner processes concurrently when the config doesn't set its own
	// value yet.
	defaultDirectoryScannerParallelCount = 16

	// httpClientEnvFile is the JetBrains HTTP Client's per-developer
	// secrets file, kept in sync with freshly bootstrapped API keys if
	// the developer has one at the project root.
	httpClientEnvFile = "http-client.private.env.json"
)

// @title			Metarr API
// @version		1.0
// @description	Event-driven Go API backed by MongoDB and Redis. Every request carries a correlation ID (X-Correlation-ID), generated by the server if the caller doesn't supply one.
// @BasePath		/
//
// @securityDefinitions.apikey	ApiKeyHeaderAuth
// @in							header
// @name						X-Api-Key
// @description				API key via the X-Api-Key header.
//
// @securitydefinitions.apikey	ApiKeyQueryAuth
// @in							query
// @name						apikey
// @description				API key via the apikey query parameter. Either this or ApiKeyHeaderAuth satisfies auth on protected routes.
func main() {
	if err := run(); err != nil {
		slog.Error("fatal error", "error", err)
		os.Exit(1)
	}
}

func run() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	logger, err := logging.New(cfg.LogFilePath)
	if err != nil {
		return err
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	connectCtx, cancelConnect := context.WithTimeout(ctx, 10*time.Second)
	defer cancelConnect()

	mongoClient, err := mongostore.Connect(connectCtx, cfg.MongoURI)
	if err != nil {
		return err
	}
	defer mongoClient.Disconnect(context.Background())

	redisClient, err := redisclient.New(connectCtx, cfg.RedisURI)
	if err != nil {
		return err
	}
	defer redisClient.Close()

	pubsubBus := eventbus.NewPubSubBus(redisClient)
	streamBus, err := eventbus.NewStreamBus(redisClient, eventbus.NewSlogAdapter(logger))
	if err != nil {
		return err
	}
	taskEventRepo := mongostore.NewTaskEventRepo(mongoClient, cfg.MongoDatabase)
	appConfigRepo := appconfig.NewRepo(mongoClient, cfg.MongoDatabase)
	localDirectoryRepo := mongostore.NewLocalDirectoryRepo(mongoClient, cfg.MongoDatabase)
	sessions := session.NewStore(redisClient)

	// The local_directory indexes include the unique index on path that makes a
	// rescan replace records rather than duplicate them, so a failure here is
	// fatal rather than merely slow.
	if err := localDirectoryRepo.EnsureIndexes(connectCtx); err != nil {
		return err
	}

	// Warm the in-memory config singleton from MongoDB before serving any
	// requests, so it reflects the persisted config from process start.
	startupCfg, err := appConfigRepo.Get(connectCtx)
	if err != nil {
		return err
	}

	// The two bootstrap checks below only mutate startupCfg in memory and
	// record what changed; the Mongo write and the
	// http-client.private.env.json sync each happen at most once, after
	// both checks, regardless of whether one or both fired — a fresh
	// install needing both doesn't pay for either round trip twice.
	var (
		bootstrapped     bool
		bootstrappedKeys *appconfig.APIKeysConfig
		newAdminPassword string
	)

	// Bootstrap the four API key categories the first time the app ever
	// starts against this database: none has been configured yet, so
	// generate one key per category. This used to be seeded by
	// mongo/init/init-mongo.js; it lives here instead so it can also sync
	// http-client.private.env.json, which only Go — not the mongo
	// container — has a normal filesystem path to.
	if len(startupCfg.APIKeys.Admin) == 0 && len(startupCfg.APIKeys.User) == 0 &&
		len(startupCfg.APIKeys.Webhook) == 0 && len(startupCfg.APIKeys.ReadOnly) == 0 {
		adminKey := uuid.NewString()
		userKey := uuid.NewString()
		webhookKey := uuid.NewString()
		readOnlyKey := uuid.NewString()

		startupCfg.APIKeys = appconfig.APIKeysConfig{
			Admin:    []appconfig.APIKeyEntry{{Name: "Administrator Key", Key: adminKey}},
			User:     []appconfig.APIKeyEntry{{Name: "User Key", Key: userKey}},
			Webhook:  []appconfig.APIKeyEntry{{Name: "Webhook Key", Key: webhookKey}},
			ReadOnly: []appconfig.APIKeyEntry{{Name: "Read Only Key", Key: readOnlyKey}},
		}
		bootstrapped = true
		bootstrappedKeys = &startupCfg.APIKeys

		fmt.Println("==================================================================")
		fmt.Println("Metarr: generated default API keys (shown only once, save these):")
		fmt.Println("  admin:     " + adminKey)
		fmt.Println("  user:      " + userKey)
		fmt.Println("  webhook:   " + webhookKey)
		fmt.Println("  read_only: " + readOnlyKey)
		fmt.Println("==================================================================")
	}

	// Bootstrap the admin user the first time the app ever starts against
	// this database: no admin has been configured yet, so generate a
	// random password and hash it. The plaintext is printed directly to
	// stdout (not through logger) so it's never written to logs/app.log —
	// shown once, same treatment as the API keys above.
	if startupCfg.Admin.Username == "" {
		plaintextPassword, err := passwordhash.GenerateRandomPassword(defaultAdminPasswordChars)
		if err != nil {
			return err
		}
		salt, hash, err := passwordhash.Hash(plaintextPassword)
		if err != nil {
			return err
		}
		startupCfg.Admin = appconfig.AdminUser{
			Username:     defaultAdminUsername,
			Email:        defaultAdminEmail,
			PasswordSalt: salt,
			PasswordHash: hash,
		}
		bootstrapped = true
		newAdminPassword = plaintextPassword

		fmt.Println("==================================================================")
		fmt.Println("Metarr: generated initial admin credentials (shown only once):")
		fmt.Println("  username: " + defaultAdminUsername)
		fmt.Println("  password: " + plaintextPassword)
		fmt.Println("==================================================================")
	}

	// Bootstrap the directory scanner config the first time the app starts
	// against this database (a fresh install, or an existing database
	// predating the directory_scanner section): default to 16 parallel
	// workers and no directories configured to scan yet.
	if startupCfg.DirectoryScanner.ParallelCount == 0 {
		startupCfg.DirectoryScanner = appconfig.DirectoryScannerConfig{
			ParallelCount:   defaultDirectoryScannerParallelCount,
			ScanDirectories: []appconfig.ScanDirectory{},
		}
		bootstrapped = true
	}

	// Seed the sidecar classification table the first time the app starts
	// against this database, on the same "fresh install, or a database
	// predating this section" reasoning as the block above. An empty table
	// would classify nothing, so this is what makes the built-in rules the
	// starting point a user then edits.
	if len(startupCfg.DirectoryScanner.SidecarTypes) == 0 {
		startupCfg.DirectoryScanner.SidecarTypes = appconfig.DefaultSidecarTypes()
		bootstrapped = true
	}

	// A built-in type added after this database was seeded would otherwise never
	// reach it, since the seed above only fires on an empty table. Note this
	// also means a built-in deleted through the API comes back on the next
	// restart: a deletion leaves nothing behind to tell it apart from a type the
	// table has simply never seen.
	if merged, added := appconfig.MergeMissingSidecarTypes(startupCfg.DirectoryScanner.SidecarTypes); added > 0 {
		startupCfg.DirectoryScanner.SidecarTypes = merged
		bootstrapped = true
		logger.Info("added built-in sidecar types missing from the stored table", "count", added)
	}

	if bootstrapped {
		if err := appConfigRepo.Upsert(connectCtx, startupCfg); err != nil {
			return err
		}
		if err := syncHTTPClientEnv(bootstrappedKeys, newAdminPassword); err != nil {
			logger.Error("failed to sync http-client.private.env.json", "error", err)
		}
	}

	appconfig.Set(startupCfg)

	// Compile the stored sidecar table into the registry the scanner reads.
	// A bad pattern here is a stored-configuration problem, not a reason to
	// refuse to boot: log it and carry on with the built-in defaults the
	// package installed at init, which at least leaves the scanner working
	// while someone fixes the document.
	if registry, err := mediascan.NewSidecarRegistry(startupCfg.DirectoryScanner.SidecarTypes); err != nil {
		logger.Error("stored sidecar type table is invalid; using built-in defaults", "error", err)
	} else {
		mediascan.SetSidecarRegistry(registry)
	}

	// Listeners run for the lifetime of the process, independent of any
	// single HTTP request.
	go listeners.RunHeartbeatListener(ctx, pubsubBus, logger)
	go func() {
		if err := listeners.RunSonarrCacheDataListener(ctx, streamBus, taskEventRepo, logger); err != nil && ctx.Err() == nil {
			logger.Error("sonarr_cache_data listener stopped unexpectedly", "error", err)
		}
	}()
	go func() {
		if err := listeners.RunSystemConfigUpdateListener(ctx, streamBus, appConfigRepo, logger); err != nil && ctx.Err() == nil {
			logger.Error("system_config_update listener stopped unexpectedly", "error", err)
		}
	}()
	go func() {
		if err := listeners.RunDirectoryScanListener(ctx, streamBus, localDirectoryRepo, logger); err != nil && ctx.Err() == nil {
			logger.Error("directory_scan listener stopped unexpectedly", "error", err)
		}
	}()

	apiHandlers := handlers.New(pubsubBus, streamBus, appConfigRepo, localDirectoryRepo, sessions, logger, cfg.HeartbeatTimeout)
	router := httpserver.NewRouter(apiHandlers, sessions, logger)
	server := httpserver.New(cfg.Host, cfg.Port, router)

	serverErr := make(chan error, 1)
	go func() {
		logger.Info("server starting", "host", cfg.Host, "port", cfg.Port)
		if err := server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			serverErr <- err
			return
		}
		serverErr <- nil
	}()

	select {
	case <-ctx.Done():
		logger.Info("shutdown signal received")
	case err := <-serverErr:
		if err != nil {
			return err
		}
	}

	shutdownCtx, cancelShutdown := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancelShutdown()
	return server.Shutdown(shutdownCtx)
}

// syncHTTPClientEnv updates the JetBrains HTTP Client's per-developer
// secrets file with whichever of the freshly bootstrapped API keys or
// admin password apply this run — apiKeys is nil, or adminPassword is "",
// when that part wasn't (re)generated — if the developer has one at the
// project root; it's a no-op, not an error, if the file doesn't exist.
// One read and one write handle both fields together, rather than the
// caller sync-ing each separately. The file is read as a generic map
// rather than a typed struct because it's IDE-managed and carries fields
// Go doesn't own — a generic round-trip only touches the fields this call
// was asked to set and leaves everything else exactly as it was.
func syncHTTPClientEnv(apiKeys *appconfig.APIKeysConfig, adminPassword string) error {
	data, err := os.ReadFile(httpClientEnvFile)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("reading %s: %w", httpClientEnvFile, err)
	}

	var envFile map[string]any
	if err := json.Unmarshal(data, &envFile); err != nil {
		return fmt.Errorf("parsing %s: %w", httpClientEnvFile, err)
	}

	local, _ := envFile["local"].(map[string]any)
	if local == nil {
		local = map[string]any{}
	}
	if apiKeys != nil {
		local["api_key_admin"] = apiKeys.Admin[0].Key
		local["api_key_user"] = apiKeys.User[0].Key
		local["api_key_webhook"] = apiKeys.Webhook[0].Key
		local["api_key_read_only"] = apiKeys.ReadOnly[0].Key
	}
	if adminPassword != "" {
		local["admin_pass"] = adminPassword
	}
	envFile["local"] = local

	updated, err := json.MarshalIndent(envFile, "", "  ")
	if err != nil {
		return fmt.Errorf("encoding %s: %w", httpClientEnvFile, err)
	}
	if err := os.WriteFile(httpClientEnvFile, append(updated, '\n'), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", httpClientEnvFile, err)
	}

	fmt.Println("Metarr: synced " + httpClientEnvFile + ".")
	return nil
}
