// Command api runs the Metarr web API: an HTTP server backed by MongoDB for
// storage and Redis for both the Pub/Sub message queue (heartbeat) and the
// stream-based event bus (background task events).
package main

import (
	"context"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"Metarr/internal/appconfig"
	"Metarr/internal/config"
	"Metarr/internal/eventbus"
	"Metarr/internal/handlers"
	"Metarr/internal/httpserver"
	"Metarr/internal/listeners"
	"Metarr/internal/logging"
	"Metarr/internal/mongostore"
	"Metarr/internal/redisclient"
)

// @title			Metarr API
// @version		1.0
// @description	Event-driven Go API backed by MongoDB and Redis. Every request carries a correlation ID (X-Correlation-ID), generated by the server if the caller doesn't supply one.
// @BasePath		/
func main() {
	if err := run(); err != nil {
		slog.Error("fatal error", "error", err)
		os.Exit(1)
	}
}

func run() error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}

	logger, err := logging.New(cfg.LogFilePath)
	if err != nil {
		return err
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	connectCtx, cancelConnect := context.WithTimeout(ctx, 10*time.Second)
	defer cancelConnect()

	mongoClient, err := mongostore.Connect(connectCtx, cfg.MongoURI)
	if err != nil {
		return err
	}
	defer mongoClient.Disconnect(context.Background())

	redisClient, err := redisclient.New(connectCtx, cfg.RedisURI)
	if err != nil {
		return err
	}
	defer redisClient.Close()

	pubsubBus := eventbus.NewPubSubBus(redisClient)
	streamBus, err := eventbus.NewStreamBus(redisClient, eventbus.NewSlogAdapter(logger))
	if err != nil {
		return err
	}
	taskEventRepo := mongostore.NewTaskEventRepo(mongoClient, cfg.MongoDatabase)
	appConfigRepo := appconfig.NewRepo(mongoClient, cfg.MongoDatabase)

	// Warm the in-memory config singleton from MongoDB before serving any
	// requests, so it reflects the persisted config from process start.
	startupCfg, err := appConfigRepo.Get(connectCtx)
	if err != nil {
		return err
	}
	appconfig.Set(startupCfg)

	// Listeners run for the lifetime of the process, independent of any
	// single HTTP request.
	go listeners.RunHeartbeatListener(ctx, pubsubBus, logger)
	go func() {
		if err := listeners.RunSonarrCacheDataListener(ctx, streamBus, taskEventRepo, logger); err != nil && ctx.Err() == nil {
			logger.Error("sonarr_cache_data listener stopped unexpectedly", "error", err)
		}
	}()
	go func() {
		if err := listeners.RunSystemConfigUpdateListener(ctx, streamBus, appConfigRepo, logger); err != nil && ctx.Err() == nil {
			logger.Error("system_config_update listener stopped unexpectedly", "error", err)
		}
	}()

	h := handlers.New(pubsubBus, streamBus, appConfigRepo, logger, cfg.HeartbeatTimeout)
	router := httpserver.NewRouter(h, logger)
	server := httpserver.New(cfg.Host, cfg.Port, router)

	serverErr := make(chan error, 1)
	go func() {
		logger.Info("server starting", "host", cfg.Host, "port", cfg.Port)
		if err := server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			serverErr <- err
			return
		}
		serverErr <- nil
	}()

	select {
	case <-ctx.Done():
		logger.Info("shutdown signal received")
	case err := <-serverErr:
		if err != nil {
			return err
		}
	}

	shutdownCtx, cancelShutdown := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancelShutdown()
	return server.Shutdown(shutdownCtx)
}
