// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: metarr/v1/admin.proto

package metarrv1connect

import (
	v1 "Metarr/internal/genproto/metarr/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "metarr.v1.AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminServiceGetAdminUserProcedure is the fully-qualified name of the AdminService's GetAdminUser
	// RPC.
	AdminServiceGetAdminUserProcedure = "/metarr.v1.AdminService/GetAdminUser"
	// AdminServiceUpdateAdminUserProcedure is the fully-qualified name of the AdminService's
	// UpdateAdminUser RPC.
	AdminServiceUpdateAdminUserProcedure = "/metarr.v1.AdminService/UpdateAdminUser"
)

// AdminServiceClient is a client for the metarr.v1.AdminService service.
type AdminServiceClient interface {
	GetAdminUser(context.Context, *connect.Request[v1.GetAdminUserRequest]) (*connect.Response[v1.AdminUser], error)
	// UpdateAdminUser returns the stored account (credential fields blanked)
	// after the synchronous write has landed (AIP-134).
	UpdateAdminUser(context.Context, *connect.Request[v1.UpdateAdminUserRequest]) (*connect.Response[v1.AdminUser], error)
}

// NewAdminServiceClient constructs a client for the metarr.v1.AdminService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := v1.File_metarr_v1_admin_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		getAdminUser: connect.NewClient[v1.GetAdminUserRequest, v1.AdminUser](
			httpClient,
			baseURL+AdminServiceGetAdminUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("GetAdminUser")),
			connect.WithClientOptions(opts...),
		),
		updateAdminUser: connect.NewClient[v1.UpdateAdminUserRequest, v1.AdminUser](
			httpClient,
			baseURL+AdminServiceUpdateAdminUserProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateAdminUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	getAdminUser    *connect.Client[v1.GetAdminUserRequest, v1.AdminUser]
	updateAdminUser *connect.Client[v1.UpdateAdminUserRequest, v1.AdminUser]
}

// GetAdminUser calls metarr.v1.AdminService.GetAdminUser.
func (c *adminServiceClient) GetAdminUser(ctx context.Context, req *connect.Request[v1.GetAdminUserRequest]) (*connect.Response[v1.AdminUser], error) {
	return c.getAdminUser.CallUnary(ctx, req)
}

// UpdateAdminUser calls metarr.v1.AdminService.UpdateAdminUser.
func (c *adminServiceClient) UpdateAdminUser(ctx context.Context, req *connect.Request[v1.UpdateAdminUserRequest]) (*connect.Response[v1.AdminUser], error) {
	return c.updateAdminUser.CallUnary(ctx, req)
}

// AdminServiceHandler is an implementation of the metarr.v1.AdminService service.
type AdminServiceHandler interface {
	GetAdminUser(context.Context, *connect.Request[v1.GetAdminUserRequest]) (*connect.Response[v1.AdminUser], error)
	// UpdateAdminUser returns the stored account (credential fields blanked)
	// after the synchronous write has landed (AIP-134).
	UpdateAdminUser(context.Context, *connect.Request[v1.UpdateAdminUserRequest]) (*connect.Response[v1.AdminUser], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := v1.File_metarr_v1_admin_proto.Services().ByName("AdminService").Methods()
	adminServiceGetAdminUserHandler := connect.NewUnaryHandler(
		AdminServiceGetAdminUserProcedure,
		svc.GetAdminUser,
		connect.WithSchema(adminServiceMethods.ByName("GetAdminUser")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateAdminUserHandler := connect.NewUnaryHandler(
		AdminServiceUpdateAdminUserProcedure,
		svc.UpdateAdminUser,
		connect.WithSchema(adminServiceMethods.ByName("UpdateAdminUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/metarr.v1.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceGetAdminUserProcedure:
			adminServiceGetAdminUserHandler.ServeHTTP(w, r)
		case AdminServiceUpdateAdminUserProcedure:
			adminServiceUpdateAdminUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) GetAdminUser(context.Context, *connect.Request[v1.GetAdminUserRequest]) (*connect.Response[v1.AdminUser], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AdminService.GetAdminUser is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateAdminUser(context.Context, *connect.Request[v1.UpdateAdminUserRequest]) (*connect.Response[v1.AdminUser], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AdminService.UpdateAdminUser is not implemented"))
}
