// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: metarr/v1/agents.proto

package metarrv1connect

import (
	v1 "Metarr/internal/genproto/metarr/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "metarr.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceCreateAgentProcedure is the fully-qualified name of the AgentService's CreateAgent
	// RPC.
	AgentServiceCreateAgentProcedure = "/metarr.v1.AgentService/CreateAgent"
	// AgentServiceGetAgentProcedure is the fully-qualified name of the AgentService's GetAgent RPC.
	AgentServiceGetAgentProcedure = "/metarr.v1.AgentService/GetAgent"
	// AgentServiceListAgentsProcedure is the fully-qualified name of the AgentService's ListAgents RPC.
	AgentServiceListAgentsProcedure = "/metarr.v1.AgentService/ListAgents"
	// AgentServiceUpdateAgentProcedure is the fully-qualified name of the AgentService's UpdateAgent
	// RPC.
	AgentServiceUpdateAgentProcedure = "/metarr.v1.AgentService/UpdateAgent"
	// AgentServiceDeleteAgentProcedure is the fully-qualified name of the AgentService's DeleteAgent
	// RPC.
	AgentServiceDeleteAgentProcedure = "/metarr.v1.AgentService/DeleteAgent"
	// AgentServiceSetLogLevelProcedure is the fully-qualified name of the AgentService's SetLogLevel
	// RPC.
	AgentServiceSetLogLevelProcedure = "/metarr.v1.AgentService/SetLogLevel"
	// AgentServiceStreamPresenceProcedure is the fully-qualified name of the AgentService's
	// StreamPresence RPC.
	AgentServiceStreamPresenceProcedure = "/metarr.v1.AgentService/StreamPresence"
)

// AgentServiceClient is a client for the metarr.v1.AgentService service.
type AgentServiceClient interface {
	CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.Agent], error)
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.Agent], error)
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// UpdateAgent returns the stored agent after the synchronous write has
	// landed (AIP-134).
	UpdateAgent(context.Context, *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.Agent], error)
	DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[emptypb.Empty], error)
	SetLogLevel(context.Context, *connect.Request[v1.SetLogLevelRequest]) (*connect.Response[v1.Agent], error)
	StreamPresence(context.Context, *connect.Request[v1.StreamPresenceRequest]) (*connect.ServerStreamForClient[v1.StreamPresenceResponse], error)
}

// NewAgentServiceClient constructs a client for the metarr.v1.AgentService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1.File_metarr_v1_agents_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		createAgent: connect.NewClient[v1.CreateAgentRequest, v1.Agent](
			httpClient,
			baseURL+AgentServiceCreateAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("CreateAgent")),
			connect.WithClientOptions(opts...),
		),
		getAgent: connect.NewClient[v1.GetAgentRequest, v1.Agent](
			httpClient,
			baseURL+AgentServiceGetAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("GetAgent")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[v1.ListAgentsRequest, v1.ListAgentsResponse](
			httpClient,
			baseURL+AgentServiceListAgentsProcedure,
			connect.WithSchema(agentServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		updateAgent: connect.NewClient[v1.UpdateAgentRequest, v1.Agent](
			httpClient,
			baseURL+AgentServiceUpdateAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("UpdateAgent")),
			connect.WithClientOptions(opts...),
		),
		deleteAgent: connect.NewClient[v1.DeleteAgentRequest, emptypb.Empty](
			httpClient,
			baseURL+AgentServiceDeleteAgentProcedure,
			connect.WithSchema(agentServiceMethods.ByName("DeleteAgent")),
			connect.WithClientOptions(opts...),
		),
		setLogLevel: connect.NewClient[v1.SetLogLevelRequest, v1.Agent](
			httpClient,
			baseURL+AgentServiceSetLogLevelProcedure,
			connect.WithSchema(agentServiceMethods.ByName("SetLogLevel")),
			connect.WithClientOptions(opts...),
		),
		streamPresence: connect.NewClient[v1.StreamPresenceRequest, v1.StreamPresenceResponse](
			httpClient,
			baseURL+AgentServiceStreamPresenceProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StreamPresence")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	createAgent    *connect.Client[v1.CreateAgentRequest, v1.Agent]
	getAgent       *connect.Client[v1.GetAgentRequest, v1.Agent]
	listAgents     *connect.Client[v1.ListAgentsRequest, v1.ListAgentsResponse]
	updateAgent    *connect.Client[v1.UpdateAgentRequest, v1.Agent]
	deleteAgent    *connect.Client[v1.DeleteAgentRequest, emptypb.Empty]
	setLogLevel    *connect.Client[v1.SetLogLevelRequest, v1.Agent]
	streamPresence *connect.Client[v1.StreamPresenceRequest, v1.StreamPresenceResponse]
}

// CreateAgent calls metarr.v1.AgentService.CreateAgent.
func (c *agentServiceClient) CreateAgent(ctx context.Context, req *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.Agent], error) {
	return c.createAgent.CallUnary(ctx, req)
}

// GetAgent calls metarr.v1.AgentService.GetAgent.
func (c *agentServiceClient) GetAgent(ctx context.Context, req *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.Agent], error) {
	return c.getAgent.CallUnary(ctx, req)
}

// ListAgents calls metarr.v1.AgentService.ListAgents.
func (c *agentServiceClient) ListAgents(ctx context.Context, req *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// UpdateAgent calls metarr.v1.AgentService.UpdateAgent.
func (c *agentServiceClient) UpdateAgent(ctx context.Context, req *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.Agent], error) {
	return c.updateAgent.CallUnary(ctx, req)
}

// DeleteAgent calls metarr.v1.AgentService.DeleteAgent.
func (c *agentServiceClient) DeleteAgent(ctx context.Context, req *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteAgent.CallUnary(ctx, req)
}

// SetLogLevel calls metarr.v1.AgentService.SetLogLevel.
func (c *agentServiceClient) SetLogLevel(ctx context.Context, req *connect.Request[v1.SetLogLevelRequest]) (*connect.Response[v1.Agent], error) {
	return c.setLogLevel.CallUnary(ctx, req)
}

// StreamPresence calls metarr.v1.AgentService.StreamPresence.
func (c *agentServiceClient) StreamPresence(ctx context.Context, req *connect.Request[v1.StreamPresenceRequest]) (*connect.ServerStreamForClient[v1.StreamPresenceResponse], error) {
	return c.streamPresence.CallServerStream(ctx, req)
}

// AgentServiceHandler is an implementation of the metarr.v1.AgentService service.
type AgentServiceHandler interface {
	CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.Agent], error)
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.Agent], error)
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// UpdateAgent returns the stored agent after the synchronous write has
	// landed (AIP-134).
	UpdateAgent(context.Context, *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.Agent], error)
	DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[emptypb.Empty], error)
	SetLogLevel(context.Context, *connect.Request[v1.SetLogLevelRequest]) (*connect.Response[v1.Agent], error)
	StreamPresence(context.Context, *connect.Request[v1.StreamPresenceRequest], *connect.ServerStream[v1.StreamPresenceResponse]) error
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1.File_metarr_v1_agents_proto.Services().ByName("AgentService").Methods()
	agentServiceCreateAgentHandler := connect.NewUnaryHandler(
		AgentServiceCreateAgentProcedure,
		svc.CreateAgent,
		connect.WithSchema(agentServiceMethods.ByName("CreateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceGetAgentHandler := connect.NewUnaryHandler(
		AgentServiceGetAgentProcedure,
		svc.GetAgent,
		connect.WithSchema(agentServiceMethods.ByName("GetAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceListAgentsHandler := connect.NewUnaryHandler(
		AgentServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(agentServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUpdateAgentHandler := connect.NewUnaryHandler(
		AgentServiceUpdateAgentProcedure,
		svc.UpdateAgent,
		connect.WithSchema(agentServiceMethods.ByName("UpdateAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDeleteAgentHandler := connect.NewUnaryHandler(
		AgentServiceDeleteAgentProcedure,
		svc.DeleteAgent,
		connect.WithSchema(agentServiceMethods.ByName("DeleteAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceSetLogLevelHandler := connect.NewUnaryHandler(
		AgentServiceSetLogLevelProcedure,
		svc.SetLogLevel,
		connect.WithSchema(agentServiceMethods.ByName("SetLogLevel")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceStreamPresenceHandler := connect.NewServerStreamHandler(
		AgentServiceStreamPresenceProcedure,
		svc.StreamPresence,
		connect.WithSchema(agentServiceMethods.ByName("StreamPresence")),
		connect.WithHandlerOptions(opts...),
	)
	return "/metarr.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceCreateAgentProcedure:
			agentServiceCreateAgentHandler.ServeHTTP(w, r)
		case AgentServiceGetAgentProcedure:
			agentServiceGetAgentHandler.ServeHTTP(w, r)
		case AgentServiceListAgentsProcedure:
			agentServiceListAgentsHandler.ServeHTTP(w, r)
		case AgentServiceUpdateAgentProcedure:
			agentServiceUpdateAgentHandler.ServeHTTP(w, r)
		case AgentServiceDeleteAgentProcedure:
			agentServiceDeleteAgentHandler.ServeHTTP(w, r)
		case AgentServiceSetLogLevelProcedure:
			agentServiceSetLogLevelHandler.ServeHTTP(w, r)
		case AgentServiceStreamPresenceProcedure:
			agentServiceStreamPresenceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) CreateAgent(context.Context, *connect.Request[v1.CreateAgentRequest]) (*connect.Response[v1.Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AgentService.CreateAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AgentService.GetAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AgentService.ListAgents is not implemented"))
}

func (UnimplementedAgentServiceHandler) UpdateAgent(context.Context, *connect.Request[v1.UpdateAgentRequest]) (*connect.Response[v1.Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AgentService.UpdateAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) DeleteAgent(context.Context, *connect.Request[v1.DeleteAgentRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AgentService.DeleteAgent is not implemented"))
}

func (UnimplementedAgentServiceHandler) SetLogLevel(context.Context, *connect.Request[v1.SetLogLevelRequest]) (*connect.Response[v1.Agent], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AgentService.SetLogLevel is not implemented"))
}

func (UnimplementedAgentServiceHandler) StreamPresence(context.Context, *connect.Request[v1.StreamPresenceRequest], *connect.ServerStream[v1.StreamPresenceResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AgentService.StreamPresence is not implemented"))
}
