// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: metarr/v1/agents.proto

package metarrv1connect

import (
	v1 "Metarr/internal/genproto/metarr/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentServiceName is the fully-qualified name of the AgentService service.
	AgentServiceName = "metarr.v1.AgentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentServiceListProcedure is the fully-qualified name of the AgentService's List RPC.
	AgentServiceListProcedure = "/metarr.v1.AgentService/List"
	// AgentServiceStreamPresenceProcedure is the fully-qualified name of the AgentService's
	// StreamPresence RPC.
	AgentServiceStreamPresenceProcedure = "/metarr.v1.AgentService/StreamPresence"
	// AgentServiceUpsertProcedure is the fully-qualified name of the AgentService's Upsert RPC.
	AgentServiceUpsertProcedure = "/metarr.v1.AgentService/Upsert"
	// AgentServiceDeleteProcedure is the fully-qualified name of the AgentService's Delete RPC.
	AgentServiceDeleteProcedure = "/metarr.v1.AgentService/Delete"
	// AgentServiceSetLogLevelProcedure is the fully-qualified name of the AgentService's SetLogLevel
	// RPC.
	AgentServiceSetLogLevelProcedure = "/metarr.v1.AgentService/SetLogLevel"
)

// AgentServiceClient is a client for the metarr.v1.AgentService service.
type AgentServiceClient interface {
	List(context.Context, *connect.Request[v1.AgentServiceListRequest]) (*connect.Response[v1.AgentServiceListResponse], error)
	StreamPresence(context.Context, *connect.Request[v1.AgentServiceStreamPresenceRequest]) (*connect.ServerStreamForClient[v1.AgentServiceStreamPresenceResponse], error)
	Upsert(context.Context, *connect.Request[v1.AgentServiceUpsertRequest]) (*connect.Response[v1.AcceptedResponse], error)
	Delete(context.Context, *connect.Request[v1.AgentServiceDeleteRequest]) (*connect.Response[v1.AcceptedResponse], error)
	SetLogLevel(context.Context, *connect.Request[v1.AgentServiceSetLogLevelRequest]) (*connect.Response[v1.AcceptedResponse], error)
}

// NewAgentServiceClient constructs a client for the metarr.v1.AgentService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentServiceMethods := v1.File_metarr_v1_agents_proto.Services().ByName("AgentService").Methods()
	return &agentServiceClient{
		list: connect.NewClient[v1.AgentServiceListRequest, v1.AgentServiceListResponse](
			httpClient,
			baseURL+AgentServiceListProcedure,
			connect.WithSchema(agentServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		streamPresence: connect.NewClient[v1.AgentServiceStreamPresenceRequest, v1.AgentServiceStreamPresenceResponse](
			httpClient,
			baseURL+AgentServiceStreamPresenceProcedure,
			connect.WithSchema(agentServiceMethods.ByName("StreamPresence")),
			connect.WithClientOptions(opts...),
		),
		upsert: connect.NewClient[v1.AgentServiceUpsertRequest, v1.AcceptedResponse](
			httpClient,
			baseURL+AgentServiceUpsertProcedure,
			connect.WithSchema(agentServiceMethods.ByName("Upsert")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.AgentServiceDeleteRequest, v1.AcceptedResponse](
			httpClient,
			baseURL+AgentServiceDeleteProcedure,
			connect.WithSchema(agentServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		setLogLevel: connect.NewClient[v1.AgentServiceSetLogLevelRequest, v1.AcceptedResponse](
			httpClient,
			baseURL+AgentServiceSetLogLevelProcedure,
			connect.WithSchema(agentServiceMethods.ByName("SetLogLevel")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentServiceClient implements AgentServiceClient.
type agentServiceClient struct {
	list           *connect.Client[v1.AgentServiceListRequest, v1.AgentServiceListResponse]
	streamPresence *connect.Client[v1.AgentServiceStreamPresenceRequest, v1.AgentServiceStreamPresenceResponse]
	upsert         *connect.Client[v1.AgentServiceUpsertRequest, v1.AcceptedResponse]
	delete         *connect.Client[v1.AgentServiceDeleteRequest, v1.AcceptedResponse]
	setLogLevel    *connect.Client[v1.AgentServiceSetLogLevelRequest, v1.AcceptedResponse]
}

// List calls metarr.v1.AgentService.List.
func (c *agentServiceClient) List(ctx context.Context, req *connect.Request[v1.AgentServiceListRequest]) (*connect.Response[v1.AgentServiceListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// StreamPresence calls metarr.v1.AgentService.StreamPresence.
func (c *agentServiceClient) StreamPresence(ctx context.Context, req *connect.Request[v1.AgentServiceStreamPresenceRequest]) (*connect.ServerStreamForClient[v1.AgentServiceStreamPresenceResponse], error) {
	return c.streamPresence.CallServerStream(ctx, req)
}

// Upsert calls metarr.v1.AgentService.Upsert.
func (c *agentServiceClient) Upsert(ctx context.Context, req *connect.Request[v1.AgentServiceUpsertRequest]) (*connect.Response[v1.AcceptedResponse], error) {
	return c.upsert.CallUnary(ctx, req)
}

// Delete calls metarr.v1.AgentService.Delete.
func (c *agentServiceClient) Delete(ctx context.Context, req *connect.Request[v1.AgentServiceDeleteRequest]) (*connect.Response[v1.AcceptedResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// SetLogLevel calls metarr.v1.AgentService.SetLogLevel.
func (c *agentServiceClient) SetLogLevel(ctx context.Context, req *connect.Request[v1.AgentServiceSetLogLevelRequest]) (*connect.Response[v1.AcceptedResponse], error) {
	return c.setLogLevel.CallUnary(ctx, req)
}

// AgentServiceHandler is an implementation of the metarr.v1.AgentService service.
type AgentServiceHandler interface {
	List(context.Context, *connect.Request[v1.AgentServiceListRequest]) (*connect.Response[v1.AgentServiceListResponse], error)
	StreamPresence(context.Context, *connect.Request[v1.AgentServiceStreamPresenceRequest], *connect.ServerStream[v1.AgentServiceStreamPresenceResponse]) error
	Upsert(context.Context, *connect.Request[v1.AgentServiceUpsertRequest]) (*connect.Response[v1.AcceptedResponse], error)
	Delete(context.Context, *connect.Request[v1.AgentServiceDeleteRequest]) (*connect.Response[v1.AcceptedResponse], error)
	SetLogLevel(context.Context, *connect.Request[v1.AgentServiceSetLogLevelRequest]) (*connect.Response[v1.AcceptedResponse], error)
}

// NewAgentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentServiceHandler(svc AgentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentServiceMethods := v1.File_metarr_v1_agents_proto.Services().ByName("AgentService").Methods()
	agentServiceListHandler := connect.NewUnaryHandler(
		AgentServiceListProcedure,
		svc.List,
		connect.WithSchema(agentServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceStreamPresenceHandler := connect.NewServerStreamHandler(
		AgentServiceStreamPresenceProcedure,
		svc.StreamPresence,
		connect.WithSchema(agentServiceMethods.ByName("StreamPresence")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceUpsertHandler := connect.NewUnaryHandler(
		AgentServiceUpsertProcedure,
		svc.Upsert,
		connect.WithSchema(agentServiceMethods.ByName("Upsert")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceDeleteHandler := connect.NewUnaryHandler(
		AgentServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(agentServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	agentServiceSetLogLevelHandler := connect.NewUnaryHandler(
		AgentServiceSetLogLevelProcedure,
		svc.SetLogLevel,
		connect.WithSchema(agentServiceMethods.ByName("SetLogLevel")),
		connect.WithHandlerOptions(opts...),
	)
	return "/metarr.v1.AgentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentServiceListProcedure:
			agentServiceListHandler.ServeHTTP(w, r)
		case AgentServiceStreamPresenceProcedure:
			agentServiceStreamPresenceHandler.ServeHTTP(w, r)
		case AgentServiceUpsertProcedure:
			agentServiceUpsertHandler.ServeHTTP(w, r)
		case AgentServiceDeleteProcedure:
			agentServiceDeleteHandler.ServeHTTP(w, r)
		case AgentServiceSetLogLevelProcedure:
			agentServiceSetLogLevelHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentServiceHandler struct{}

func (UnimplementedAgentServiceHandler) List(context.Context, *connect.Request[v1.AgentServiceListRequest]) (*connect.Response[v1.AgentServiceListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AgentService.List is not implemented"))
}

func (UnimplementedAgentServiceHandler) StreamPresence(context.Context, *connect.Request[v1.AgentServiceStreamPresenceRequest], *connect.ServerStream[v1.AgentServiceStreamPresenceResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AgentService.StreamPresence is not implemented"))
}

func (UnimplementedAgentServiceHandler) Upsert(context.Context, *connect.Request[v1.AgentServiceUpsertRequest]) (*connect.Response[v1.AcceptedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AgentService.Upsert is not implemented"))
}

func (UnimplementedAgentServiceHandler) Delete(context.Context, *connect.Request[v1.AgentServiceDeleteRequest]) (*connect.Response[v1.AcceptedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AgentService.Delete is not implemented"))
}

func (UnimplementedAgentServiceHandler) SetLogLevel(context.Context, *connect.Request[v1.AgentServiceSetLogLevelRequest]) (*connect.Response[v1.AcceptedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.AgentService.SetLogLevel is not implemented"))
}
