// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: metarr/v1/directory_scanner.proto

package metarrv1connect

import (
	v11 "Metarr/internal/genproto/metarr/bus/v1"
	v1 "Metarr/internal/genproto/metarr/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DirectoryScannerServiceName is the fully-qualified name of the DirectoryScannerService service.
	DirectoryScannerServiceName = "metarr.v1.DirectoryScannerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DirectoryScannerServiceGetDirectoryScannerConfigProcedure is the fully-qualified name of the
	// DirectoryScannerService's GetDirectoryScannerConfig RPC.
	DirectoryScannerServiceGetDirectoryScannerConfigProcedure = "/metarr.v1.DirectoryScannerService/GetDirectoryScannerConfig"
	// DirectoryScannerServiceUpdateDirectoryScannerConfigProcedure is the fully-qualified name of the
	// DirectoryScannerService's UpdateDirectoryScannerConfig RPC.
	DirectoryScannerServiceUpdateDirectoryScannerConfigProcedure = "/metarr.v1.DirectoryScannerService/UpdateDirectoryScannerConfig"
	// DirectoryScannerServiceCreateScanDirectoryProcedure is the fully-qualified name of the
	// DirectoryScannerService's CreateScanDirectory RPC.
	DirectoryScannerServiceCreateScanDirectoryProcedure = "/metarr.v1.DirectoryScannerService/CreateScanDirectory"
	// DirectoryScannerServiceGetScanDirectoryProcedure is the fully-qualified name of the
	// DirectoryScannerService's GetScanDirectory RPC.
	DirectoryScannerServiceGetScanDirectoryProcedure = "/metarr.v1.DirectoryScannerService/GetScanDirectory"
	// DirectoryScannerServiceListScanDirectoriesProcedure is the fully-qualified name of the
	// DirectoryScannerService's ListScanDirectories RPC.
	DirectoryScannerServiceListScanDirectoriesProcedure = "/metarr.v1.DirectoryScannerService/ListScanDirectories"
	// DirectoryScannerServiceUpdateScanDirectoryProcedure is the fully-qualified name of the
	// DirectoryScannerService's UpdateScanDirectory RPC.
	DirectoryScannerServiceUpdateScanDirectoryProcedure = "/metarr.v1.DirectoryScannerService/UpdateScanDirectory"
	// DirectoryScannerServiceDeleteScanDirectoryProcedure is the fully-qualified name of the
	// DirectoryScannerService's DeleteScanDirectory RPC.
	DirectoryScannerServiceDeleteScanDirectoryProcedure = "/metarr.v1.DirectoryScannerService/DeleteScanDirectory"
	// DirectoryScannerServiceCreateSidecarTypeProcedure is the fully-qualified name of the
	// DirectoryScannerService's CreateSidecarType RPC.
	DirectoryScannerServiceCreateSidecarTypeProcedure = "/metarr.v1.DirectoryScannerService/CreateSidecarType"
	// DirectoryScannerServiceGetSidecarTypeProcedure is the fully-qualified name of the
	// DirectoryScannerService's GetSidecarType RPC.
	DirectoryScannerServiceGetSidecarTypeProcedure = "/metarr.v1.DirectoryScannerService/GetSidecarType"
	// DirectoryScannerServiceListSidecarTypesProcedure is the fully-qualified name of the
	// DirectoryScannerService's ListSidecarTypes RPC.
	DirectoryScannerServiceListSidecarTypesProcedure = "/metarr.v1.DirectoryScannerService/ListSidecarTypes"
	// DirectoryScannerServiceUpdateSidecarTypeProcedure is the fully-qualified name of the
	// DirectoryScannerService's UpdateSidecarType RPC.
	DirectoryScannerServiceUpdateSidecarTypeProcedure = "/metarr.v1.DirectoryScannerService/UpdateSidecarType"
	// DirectoryScannerServiceDeleteSidecarTypeProcedure is the fully-qualified name of the
	// DirectoryScannerService's DeleteSidecarType RPC.
	DirectoryScannerServiceDeleteSidecarTypeProcedure = "/metarr.v1.DirectoryScannerService/DeleteSidecarType"
	// DirectoryScannerServiceReorderSidecarTypesProcedure is the fully-qualified name of the
	// DirectoryScannerService's ReorderSidecarTypes RPC.
	DirectoryScannerServiceReorderSidecarTypesProcedure = "/metarr.v1.DirectoryScannerService/ReorderSidecarTypes"
	// DirectoryScannerServiceResetSidecarTypesProcedure is the fully-qualified name of the
	// DirectoryScannerService's ResetSidecarTypes RPC.
	DirectoryScannerServiceResetSidecarTypesProcedure = "/metarr.v1.DirectoryScannerService/ResetSidecarTypes"
)

// DirectoryScannerServiceClient is a client for the metarr.v1.DirectoryScannerService service.
type DirectoryScannerServiceClient interface {
	GetDirectoryScannerConfig(context.Context, *connect.Request[v1.GetDirectoryScannerConfigRequest]) (*connect.Response[v1.GetDirectoryScannerConfigResponse], error)
	// UpdateDirectoryScannerConfig returns the stored section after the
	// synchronous write has landed (AIP-134).
	UpdateDirectoryScannerConfig(context.Context, *connect.Request[v1.UpdateDirectoryScannerConfigRequest]) (*connect.Response[v1.DirectoryScannerConfig], error)
	CreateScanDirectory(context.Context, *connect.Request[v1.CreateScanDirectoryRequest]) (*connect.Response[v1.ScanDirectory], error)
	GetScanDirectory(context.Context, *connect.Request[v1.GetScanDirectoryRequest]) (*connect.Response[v1.ScanDirectory], error)
	ListScanDirectories(context.Context, *connect.Request[v1.ListScanDirectoriesRequest]) (*connect.Response[v1.ListScanDirectoriesResponse], error)
	UpdateScanDirectory(context.Context, *connect.Request[v1.UpdateScanDirectoryRequest]) (*connect.Response[v1.ScanDirectory], error)
	DeleteScanDirectory(context.Context, *connect.Request[v1.DeleteScanDirectoryRequest]) (*connect.Response[emptypb.Empty], error)
	CreateSidecarType(context.Context, *connect.Request[v1.CreateSidecarTypeRequest]) (*connect.Response[v11.SidecarTypeDefinition], error)
	GetSidecarType(context.Context, *connect.Request[v1.GetSidecarTypeRequest]) (*connect.Response[v11.SidecarTypeDefinition], error)
	ListSidecarTypes(context.Context, *connect.Request[v1.ListSidecarTypesRequest]) (*connect.Response[v1.ListSidecarTypesResponse], error)
	UpdateSidecarType(context.Context, *connect.Request[v1.UpdateSidecarTypeRequest]) (*connect.Response[v11.SidecarTypeDefinition], error)
	DeleteSidecarType(context.Context, *connect.Request[v1.DeleteSidecarTypeRequest]) (*connect.Response[emptypb.Empty], error)
	// ReorderSidecarTypes and ResetSidecarTypes are custom methods (AIP-136),
	// synchronous, returning the updated list.
	ReorderSidecarTypes(context.Context, *connect.Request[v1.ReorderSidecarTypesRequest]) (*connect.Response[v1.ReorderSidecarTypesResponse], error)
	ResetSidecarTypes(context.Context, *connect.Request[v1.ResetSidecarTypesRequest]) (*connect.Response[v1.ResetSidecarTypesResponse], error)
}

// NewDirectoryScannerServiceClient constructs a client for the metarr.v1.DirectoryScannerService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDirectoryScannerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DirectoryScannerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	directoryScannerServiceMethods := v1.File_metarr_v1_directory_scanner_proto.Services().ByName("DirectoryScannerService").Methods()
	return &directoryScannerServiceClient{
		getDirectoryScannerConfig: connect.NewClient[v1.GetDirectoryScannerConfigRequest, v1.GetDirectoryScannerConfigResponse](
			httpClient,
			baseURL+DirectoryScannerServiceGetDirectoryScannerConfigProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("GetDirectoryScannerConfig")),
			connect.WithClientOptions(opts...),
		),
		updateDirectoryScannerConfig: connect.NewClient[v1.UpdateDirectoryScannerConfigRequest, v1.DirectoryScannerConfig](
			httpClient,
			baseURL+DirectoryScannerServiceUpdateDirectoryScannerConfigProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("UpdateDirectoryScannerConfig")),
			connect.WithClientOptions(opts...),
		),
		createScanDirectory: connect.NewClient[v1.CreateScanDirectoryRequest, v1.ScanDirectory](
			httpClient,
			baseURL+DirectoryScannerServiceCreateScanDirectoryProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("CreateScanDirectory")),
			connect.WithClientOptions(opts...),
		),
		getScanDirectory: connect.NewClient[v1.GetScanDirectoryRequest, v1.ScanDirectory](
			httpClient,
			baseURL+DirectoryScannerServiceGetScanDirectoryProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("GetScanDirectory")),
			connect.WithClientOptions(opts...),
		),
		listScanDirectories: connect.NewClient[v1.ListScanDirectoriesRequest, v1.ListScanDirectoriesResponse](
			httpClient,
			baseURL+DirectoryScannerServiceListScanDirectoriesProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("ListScanDirectories")),
			connect.WithClientOptions(opts...),
		),
		updateScanDirectory: connect.NewClient[v1.UpdateScanDirectoryRequest, v1.ScanDirectory](
			httpClient,
			baseURL+DirectoryScannerServiceUpdateScanDirectoryProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("UpdateScanDirectory")),
			connect.WithClientOptions(opts...),
		),
		deleteScanDirectory: connect.NewClient[v1.DeleteScanDirectoryRequest, emptypb.Empty](
			httpClient,
			baseURL+DirectoryScannerServiceDeleteScanDirectoryProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("DeleteScanDirectory")),
			connect.WithClientOptions(opts...),
		),
		createSidecarType: connect.NewClient[v1.CreateSidecarTypeRequest, v11.SidecarTypeDefinition](
			httpClient,
			baseURL+DirectoryScannerServiceCreateSidecarTypeProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("CreateSidecarType")),
			connect.WithClientOptions(opts...),
		),
		getSidecarType: connect.NewClient[v1.GetSidecarTypeRequest, v11.SidecarTypeDefinition](
			httpClient,
			baseURL+DirectoryScannerServiceGetSidecarTypeProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("GetSidecarType")),
			connect.WithClientOptions(opts...),
		),
		listSidecarTypes: connect.NewClient[v1.ListSidecarTypesRequest, v1.ListSidecarTypesResponse](
			httpClient,
			baseURL+DirectoryScannerServiceListSidecarTypesProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("ListSidecarTypes")),
			connect.WithClientOptions(opts...),
		),
		updateSidecarType: connect.NewClient[v1.UpdateSidecarTypeRequest, v11.SidecarTypeDefinition](
			httpClient,
			baseURL+DirectoryScannerServiceUpdateSidecarTypeProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("UpdateSidecarType")),
			connect.WithClientOptions(opts...),
		),
		deleteSidecarType: connect.NewClient[v1.DeleteSidecarTypeRequest, emptypb.Empty](
			httpClient,
			baseURL+DirectoryScannerServiceDeleteSidecarTypeProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("DeleteSidecarType")),
			connect.WithClientOptions(opts...),
		),
		reorderSidecarTypes: connect.NewClient[v1.ReorderSidecarTypesRequest, v1.ReorderSidecarTypesResponse](
			httpClient,
			baseURL+DirectoryScannerServiceReorderSidecarTypesProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("ReorderSidecarTypes")),
			connect.WithClientOptions(opts...),
		),
		resetSidecarTypes: connect.NewClient[v1.ResetSidecarTypesRequest, v1.ResetSidecarTypesResponse](
			httpClient,
			baseURL+DirectoryScannerServiceResetSidecarTypesProcedure,
			connect.WithSchema(directoryScannerServiceMethods.ByName("ResetSidecarTypes")),
			connect.WithClientOptions(opts...),
		),
	}
}

// directoryScannerServiceClient implements DirectoryScannerServiceClient.
type directoryScannerServiceClient struct {
	getDirectoryScannerConfig    *connect.Client[v1.GetDirectoryScannerConfigRequest, v1.GetDirectoryScannerConfigResponse]
	updateDirectoryScannerConfig *connect.Client[v1.UpdateDirectoryScannerConfigRequest, v1.DirectoryScannerConfig]
	createScanDirectory          *connect.Client[v1.CreateScanDirectoryRequest, v1.ScanDirectory]
	getScanDirectory             *connect.Client[v1.GetScanDirectoryRequest, v1.ScanDirectory]
	listScanDirectories          *connect.Client[v1.ListScanDirectoriesRequest, v1.ListScanDirectoriesResponse]
	updateScanDirectory          *connect.Client[v1.UpdateScanDirectoryRequest, v1.ScanDirectory]
	deleteScanDirectory          *connect.Client[v1.DeleteScanDirectoryRequest, emptypb.Empty]
	createSidecarType            *connect.Client[v1.CreateSidecarTypeRequest, v11.SidecarTypeDefinition]
	getSidecarType               *connect.Client[v1.GetSidecarTypeRequest, v11.SidecarTypeDefinition]
	listSidecarTypes             *connect.Client[v1.ListSidecarTypesRequest, v1.ListSidecarTypesResponse]
	updateSidecarType            *connect.Client[v1.UpdateSidecarTypeRequest, v11.SidecarTypeDefinition]
	deleteSidecarType            *connect.Client[v1.DeleteSidecarTypeRequest, emptypb.Empty]
	reorderSidecarTypes          *connect.Client[v1.ReorderSidecarTypesRequest, v1.ReorderSidecarTypesResponse]
	resetSidecarTypes            *connect.Client[v1.ResetSidecarTypesRequest, v1.ResetSidecarTypesResponse]
}

// GetDirectoryScannerConfig calls metarr.v1.DirectoryScannerService.GetDirectoryScannerConfig.
func (c *directoryScannerServiceClient) GetDirectoryScannerConfig(ctx context.Context, req *connect.Request[v1.GetDirectoryScannerConfigRequest]) (*connect.Response[v1.GetDirectoryScannerConfigResponse], error) {
	return c.getDirectoryScannerConfig.CallUnary(ctx, req)
}

// UpdateDirectoryScannerConfig calls
// metarr.v1.DirectoryScannerService.UpdateDirectoryScannerConfig.
func (c *directoryScannerServiceClient) UpdateDirectoryScannerConfig(ctx context.Context, req *connect.Request[v1.UpdateDirectoryScannerConfigRequest]) (*connect.Response[v1.DirectoryScannerConfig], error) {
	return c.updateDirectoryScannerConfig.CallUnary(ctx, req)
}

// CreateScanDirectory calls metarr.v1.DirectoryScannerService.CreateScanDirectory.
func (c *directoryScannerServiceClient) CreateScanDirectory(ctx context.Context, req *connect.Request[v1.CreateScanDirectoryRequest]) (*connect.Response[v1.ScanDirectory], error) {
	return c.createScanDirectory.CallUnary(ctx, req)
}

// GetScanDirectory calls metarr.v1.DirectoryScannerService.GetScanDirectory.
func (c *directoryScannerServiceClient) GetScanDirectory(ctx context.Context, req *connect.Request[v1.GetScanDirectoryRequest]) (*connect.Response[v1.ScanDirectory], error) {
	return c.getScanDirectory.CallUnary(ctx, req)
}

// ListScanDirectories calls metarr.v1.DirectoryScannerService.ListScanDirectories.
func (c *directoryScannerServiceClient) ListScanDirectories(ctx context.Context, req *connect.Request[v1.ListScanDirectoriesRequest]) (*connect.Response[v1.ListScanDirectoriesResponse], error) {
	return c.listScanDirectories.CallUnary(ctx, req)
}

// UpdateScanDirectory calls metarr.v1.DirectoryScannerService.UpdateScanDirectory.
func (c *directoryScannerServiceClient) UpdateScanDirectory(ctx context.Context, req *connect.Request[v1.UpdateScanDirectoryRequest]) (*connect.Response[v1.ScanDirectory], error) {
	return c.updateScanDirectory.CallUnary(ctx, req)
}

// DeleteScanDirectory calls metarr.v1.DirectoryScannerService.DeleteScanDirectory.
func (c *directoryScannerServiceClient) DeleteScanDirectory(ctx context.Context, req *connect.Request[v1.DeleteScanDirectoryRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteScanDirectory.CallUnary(ctx, req)
}

// CreateSidecarType calls metarr.v1.DirectoryScannerService.CreateSidecarType.
func (c *directoryScannerServiceClient) CreateSidecarType(ctx context.Context, req *connect.Request[v1.CreateSidecarTypeRequest]) (*connect.Response[v11.SidecarTypeDefinition], error) {
	return c.createSidecarType.CallUnary(ctx, req)
}

// GetSidecarType calls metarr.v1.DirectoryScannerService.GetSidecarType.
func (c *directoryScannerServiceClient) GetSidecarType(ctx context.Context, req *connect.Request[v1.GetSidecarTypeRequest]) (*connect.Response[v11.SidecarTypeDefinition], error) {
	return c.getSidecarType.CallUnary(ctx, req)
}

// ListSidecarTypes calls metarr.v1.DirectoryScannerService.ListSidecarTypes.
func (c *directoryScannerServiceClient) ListSidecarTypes(ctx context.Context, req *connect.Request[v1.ListSidecarTypesRequest]) (*connect.Response[v1.ListSidecarTypesResponse], error) {
	return c.listSidecarTypes.CallUnary(ctx, req)
}

// UpdateSidecarType calls metarr.v1.DirectoryScannerService.UpdateSidecarType.
func (c *directoryScannerServiceClient) UpdateSidecarType(ctx context.Context, req *connect.Request[v1.UpdateSidecarTypeRequest]) (*connect.Response[v11.SidecarTypeDefinition], error) {
	return c.updateSidecarType.CallUnary(ctx, req)
}

// DeleteSidecarType calls metarr.v1.DirectoryScannerService.DeleteSidecarType.
func (c *directoryScannerServiceClient) DeleteSidecarType(ctx context.Context, req *connect.Request[v1.DeleteSidecarTypeRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteSidecarType.CallUnary(ctx, req)
}

// ReorderSidecarTypes calls metarr.v1.DirectoryScannerService.ReorderSidecarTypes.
func (c *directoryScannerServiceClient) ReorderSidecarTypes(ctx context.Context, req *connect.Request[v1.ReorderSidecarTypesRequest]) (*connect.Response[v1.ReorderSidecarTypesResponse], error) {
	return c.reorderSidecarTypes.CallUnary(ctx, req)
}

// ResetSidecarTypes calls metarr.v1.DirectoryScannerService.ResetSidecarTypes.
func (c *directoryScannerServiceClient) ResetSidecarTypes(ctx context.Context, req *connect.Request[v1.ResetSidecarTypesRequest]) (*connect.Response[v1.ResetSidecarTypesResponse], error) {
	return c.resetSidecarTypes.CallUnary(ctx, req)
}

// DirectoryScannerServiceHandler is an implementation of the metarr.v1.DirectoryScannerService
// service.
type DirectoryScannerServiceHandler interface {
	GetDirectoryScannerConfig(context.Context, *connect.Request[v1.GetDirectoryScannerConfigRequest]) (*connect.Response[v1.GetDirectoryScannerConfigResponse], error)
	// UpdateDirectoryScannerConfig returns the stored section after the
	// synchronous write has landed (AIP-134).
	UpdateDirectoryScannerConfig(context.Context, *connect.Request[v1.UpdateDirectoryScannerConfigRequest]) (*connect.Response[v1.DirectoryScannerConfig], error)
	CreateScanDirectory(context.Context, *connect.Request[v1.CreateScanDirectoryRequest]) (*connect.Response[v1.ScanDirectory], error)
	GetScanDirectory(context.Context, *connect.Request[v1.GetScanDirectoryRequest]) (*connect.Response[v1.ScanDirectory], error)
	ListScanDirectories(context.Context, *connect.Request[v1.ListScanDirectoriesRequest]) (*connect.Response[v1.ListScanDirectoriesResponse], error)
	UpdateScanDirectory(context.Context, *connect.Request[v1.UpdateScanDirectoryRequest]) (*connect.Response[v1.ScanDirectory], error)
	DeleteScanDirectory(context.Context, *connect.Request[v1.DeleteScanDirectoryRequest]) (*connect.Response[emptypb.Empty], error)
	CreateSidecarType(context.Context, *connect.Request[v1.CreateSidecarTypeRequest]) (*connect.Response[v11.SidecarTypeDefinition], error)
	GetSidecarType(context.Context, *connect.Request[v1.GetSidecarTypeRequest]) (*connect.Response[v11.SidecarTypeDefinition], error)
	ListSidecarTypes(context.Context, *connect.Request[v1.ListSidecarTypesRequest]) (*connect.Response[v1.ListSidecarTypesResponse], error)
	UpdateSidecarType(context.Context, *connect.Request[v1.UpdateSidecarTypeRequest]) (*connect.Response[v11.SidecarTypeDefinition], error)
	DeleteSidecarType(context.Context, *connect.Request[v1.DeleteSidecarTypeRequest]) (*connect.Response[emptypb.Empty], error)
	// ReorderSidecarTypes and ResetSidecarTypes are custom methods (AIP-136),
	// synchronous, returning the updated list.
	ReorderSidecarTypes(context.Context, *connect.Request[v1.ReorderSidecarTypesRequest]) (*connect.Response[v1.ReorderSidecarTypesResponse], error)
	ResetSidecarTypes(context.Context, *connect.Request[v1.ResetSidecarTypesRequest]) (*connect.Response[v1.ResetSidecarTypesResponse], error)
}

// NewDirectoryScannerServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDirectoryScannerServiceHandler(svc DirectoryScannerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	directoryScannerServiceMethods := v1.File_metarr_v1_directory_scanner_proto.Services().ByName("DirectoryScannerService").Methods()
	directoryScannerServiceGetDirectoryScannerConfigHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceGetDirectoryScannerConfigProcedure,
		svc.GetDirectoryScannerConfig,
		connect.WithSchema(directoryScannerServiceMethods.ByName("GetDirectoryScannerConfig")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceUpdateDirectoryScannerConfigHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceUpdateDirectoryScannerConfigProcedure,
		svc.UpdateDirectoryScannerConfig,
		connect.WithSchema(directoryScannerServiceMethods.ByName("UpdateDirectoryScannerConfig")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceCreateScanDirectoryHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceCreateScanDirectoryProcedure,
		svc.CreateScanDirectory,
		connect.WithSchema(directoryScannerServiceMethods.ByName("CreateScanDirectory")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceGetScanDirectoryHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceGetScanDirectoryProcedure,
		svc.GetScanDirectory,
		connect.WithSchema(directoryScannerServiceMethods.ByName("GetScanDirectory")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceListScanDirectoriesHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceListScanDirectoriesProcedure,
		svc.ListScanDirectories,
		connect.WithSchema(directoryScannerServiceMethods.ByName("ListScanDirectories")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceUpdateScanDirectoryHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceUpdateScanDirectoryProcedure,
		svc.UpdateScanDirectory,
		connect.WithSchema(directoryScannerServiceMethods.ByName("UpdateScanDirectory")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceDeleteScanDirectoryHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceDeleteScanDirectoryProcedure,
		svc.DeleteScanDirectory,
		connect.WithSchema(directoryScannerServiceMethods.ByName("DeleteScanDirectory")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceCreateSidecarTypeHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceCreateSidecarTypeProcedure,
		svc.CreateSidecarType,
		connect.WithSchema(directoryScannerServiceMethods.ByName("CreateSidecarType")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceGetSidecarTypeHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceGetSidecarTypeProcedure,
		svc.GetSidecarType,
		connect.WithSchema(directoryScannerServiceMethods.ByName("GetSidecarType")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceListSidecarTypesHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceListSidecarTypesProcedure,
		svc.ListSidecarTypes,
		connect.WithSchema(directoryScannerServiceMethods.ByName("ListSidecarTypes")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceUpdateSidecarTypeHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceUpdateSidecarTypeProcedure,
		svc.UpdateSidecarType,
		connect.WithSchema(directoryScannerServiceMethods.ByName("UpdateSidecarType")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceDeleteSidecarTypeHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceDeleteSidecarTypeProcedure,
		svc.DeleteSidecarType,
		connect.WithSchema(directoryScannerServiceMethods.ByName("DeleteSidecarType")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceReorderSidecarTypesHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceReorderSidecarTypesProcedure,
		svc.ReorderSidecarTypes,
		connect.WithSchema(directoryScannerServiceMethods.ByName("ReorderSidecarTypes")),
		connect.WithHandlerOptions(opts...),
	)
	directoryScannerServiceResetSidecarTypesHandler := connect.NewUnaryHandler(
		DirectoryScannerServiceResetSidecarTypesProcedure,
		svc.ResetSidecarTypes,
		connect.WithSchema(directoryScannerServiceMethods.ByName("ResetSidecarTypes")),
		connect.WithHandlerOptions(opts...),
	)
	return "/metarr.v1.DirectoryScannerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DirectoryScannerServiceGetDirectoryScannerConfigProcedure:
			directoryScannerServiceGetDirectoryScannerConfigHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceUpdateDirectoryScannerConfigProcedure:
			directoryScannerServiceUpdateDirectoryScannerConfigHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceCreateScanDirectoryProcedure:
			directoryScannerServiceCreateScanDirectoryHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceGetScanDirectoryProcedure:
			directoryScannerServiceGetScanDirectoryHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceListScanDirectoriesProcedure:
			directoryScannerServiceListScanDirectoriesHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceUpdateScanDirectoryProcedure:
			directoryScannerServiceUpdateScanDirectoryHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceDeleteScanDirectoryProcedure:
			directoryScannerServiceDeleteScanDirectoryHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceCreateSidecarTypeProcedure:
			directoryScannerServiceCreateSidecarTypeHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceGetSidecarTypeProcedure:
			directoryScannerServiceGetSidecarTypeHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceListSidecarTypesProcedure:
			directoryScannerServiceListSidecarTypesHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceUpdateSidecarTypeProcedure:
			directoryScannerServiceUpdateSidecarTypeHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceDeleteSidecarTypeProcedure:
			directoryScannerServiceDeleteSidecarTypeHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceReorderSidecarTypesProcedure:
			directoryScannerServiceReorderSidecarTypesHandler.ServeHTTP(w, r)
		case DirectoryScannerServiceResetSidecarTypesProcedure:
			directoryScannerServiceResetSidecarTypesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDirectoryScannerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDirectoryScannerServiceHandler struct{}

func (UnimplementedDirectoryScannerServiceHandler) GetDirectoryScannerConfig(context.Context, *connect.Request[v1.GetDirectoryScannerConfigRequest]) (*connect.Response[v1.GetDirectoryScannerConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.GetDirectoryScannerConfig is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) UpdateDirectoryScannerConfig(context.Context, *connect.Request[v1.UpdateDirectoryScannerConfigRequest]) (*connect.Response[v1.DirectoryScannerConfig], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.UpdateDirectoryScannerConfig is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) CreateScanDirectory(context.Context, *connect.Request[v1.CreateScanDirectoryRequest]) (*connect.Response[v1.ScanDirectory], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.CreateScanDirectory is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) GetScanDirectory(context.Context, *connect.Request[v1.GetScanDirectoryRequest]) (*connect.Response[v1.ScanDirectory], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.GetScanDirectory is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) ListScanDirectories(context.Context, *connect.Request[v1.ListScanDirectoriesRequest]) (*connect.Response[v1.ListScanDirectoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.ListScanDirectories is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) UpdateScanDirectory(context.Context, *connect.Request[v1.UpdateScanDirectoryRequest]) (*connect.Response[v1.ScanDirectory], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.UpdateScanDirectory is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) DeleteScanDirectory(context.Context, *connect.Request[v1.DeleteScanDirectoryRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.DeleteScanDirectory is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) CreateSidecarType(context.Context, *connect.Request[v1.CreateSidecarTypeRequest]) (*connect.Response[v11.SidecarTypeDefinition], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.CreateSidecarType is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) GetSidecarType(context.Context, *connect.Request[v1.GetSidecarTypeRequest]) (*connect.Response[v11.SidecarTypeDefinition], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.GetSidecarType is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) ListSidecarTypes(context.Context, *connect.Request[v1.ListSidecarTypesRequest]) (*connect.Response[v1.ListSidecarTypesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.ListSidecarTypes is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) UpdateSidecarType(context.Context, *connect.Request[v1.UpdateSidecarTypeRequest]) (*connect.Response[v11.SidecarTypeDefinition], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.UpdateSidecarType is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) DeleteSidecarType(context.Context, *connect.Request[v1.DeleteSidecarTypeRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.DeleteSidecarType is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) ReorderSidecarTypes(context.Context, *connect.Request[v1.ReorderSidecarTypesRequest]) (*connect.Response[v1.ReorderSidecarTypesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.ReorderSidecarTypes is not implemented"))
}

func (UnimplementedDirectoryScannerServiceHandler) ResetSidecarTypes(context.Context, *connect.Request[v1.ResetSidecarTypesRequest]) (*connect.Response[v1.ResetSidecarTypesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.DirectoryScannerService.ResetSidecarTypes is not implemented"))
}
