// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: metarr/v1/event_bus.proto

package metarrv1connect

import (
	v1 "Metarr/internal/genproto/metarr/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EventBusServiceName is the fully-qualified name of the EventBusService service.
	EventBusServiceName = "metarr.v1.EventBusService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EventBusServiceGetEventBusConfigProcedure is the fully-qualified name of the EventBusService's
	// GetEventBusConfig RPC.
	EventBusServiceGetEventBusConfigProcedure = "/metarr.v1.EventBusService/GetEventBusConfig"
	// EventBusServiceUpdateEventBusConfigProcedure is the fully-qualified name of the EventBusService's
	// UpdateEventBusConfig RPC.
	EventBusServiceUpdateEventBusConfigProcedure = "/metarr.v1.EventBusService/UpdateEventBusConfig"
)

// EventBusServiceClient is a client for the metarr.v1.EventBusService service.
type EventBusServiceClient interface {
	GetEventBusConfig(context.Context, *connect.Request[v1.GetEventBusConfigRequest]) (*connect.Response[v1.GetEventBusConfigResponse], error)
	UpdateEventBusConfig(context.Context, *connect.Request[v1.UpdateEventBusConfigRequest]) (*connect.Response[v1.Operation], error)
}

// NewEventBusServiceClient constructs a client for the metarr.v1.EventBusService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventBusServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventBusServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventBusServiceMethods := v1.File_metarr_v1_event_bus_proto.Services().ByName("EventBusService").Methods()
	return &eventBusServiceClient{
		getEventBusConfig: connect.NewClient[v1.GetEventBusConfigRequest, v1.GetEventBusConfigResponse](
			httpClient,
			baseURL+EventBusServiceGetEventBusConfigProcedure,
			connect.WithSchema(eventBusServiceMethods.ByName("GetEventBusConfig")),
			connect.WithClientOptions(opts...),
		),
		updateEventBusConfig: connect.NewClient[v1.UpdateEventBusConfigRequest, v1.Operation](
			httpClient,
			baseURL+EventBusServiceUpdateEventBusConfigProcedure,
			connect.WithSchema(eventBusServiceMethods.ByName("UpdateEventBusConfig")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventBusServiceClient implements EventBusServiceClient.
type eventBusServiceClient struct {
	getEventBusConfig    *connect.Client[v1.GetEventBusConfigRequest, v1.GetEventBusConfigResponse]
	updateEventBusConfig *connect.Client[v1.UpdateEventBusConfigRequest, v1.Operation]
}

// GetEventBusConfig calls metarr.v1.EventBusService.GetEventBusConfig.
func (c *eventBusServiceClient) GetEventBusConfig(ctx context.Context, req *connect.Request[v1.GetEventBusConfigRequest]) (*connect.Response[v1.GetEventBusConfigResponse], error) {
	return c.getEventBusConfig.CallUnary(ctx, req)
}

// UpdateEventBusConfig calls metarr.v1.EventBusService.UpdateEventBusConfig.
func (c *eventBusServiceClient) UpdateEventBusConfig(ctx context.Context, req *connect.Request[v1.UpdateEventBusConfigRequest]) (*connect.Response[v1.Operation], error) {
	return c.updateEventBusConfig.CallUnary(ctx, req)
}

// EventBusServiceHandler is an implementation of the metarr.v1.EventBusService service.
type EventBusServiceHandler interface {
	GetEventBusConfig(context.Context, *connect.Request[v1.GetEventBusConfigRequest]) (*connect.Response[v1.GetEventBusConfigResponse], error)
	UpdateEventBusConfig(context.Context, *connect.Request[v1.UpdateEventBusConfigRequest]) (*connect.Response[v1.Operation], error)
}

// NewEventBusServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventBusServiceHandler(svc EventBusServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventBusServiceMethods := v1.File_metarr_v1_event_bus_proto.Services().ByName("EventBusService").Methods()
	eventBusServiceGetEventBusConfigHandler := connect.NewUnaryHandler(
		EventBusServiceGetEventBusConfigProcedure,
		svc.GetEventBusConfig,
		connect.WithSchema(eventBusServiceMethods.ByName("GetEventBusConfig")),
		connect.WithHandlerOptions(opts...),
	)
	eventBusServiceUpdateEventBusConfigHandler := connect.NewUnaryHandler(
		EventBusServiceUpdateEventBusConfigProcedure,
		svc.UpdateEventBusConfig,
		connect.WithSchema(eventBusServiceMethods.ByName("UpdateEventBusConfig")),
		connect.WithHandlerOptions(opts...),
	)
	return "/metarr.v1.EventBusService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventBusServiceGetEventBusConfigProcedure:
			eventBusServiceGetEventBusConfigHandler.ServeHTTP(w, r)
		case EventBusServiceUpdateEventBusConfigProcedure:
			eventBusServiceUpdateEventBusConfigHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventBusServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventBusServiceHandler struct{}

func (UnimplementedEventBusServiceHandler) GetEventBusConfig(context.Context, *connect.Request[v1.GetEventBusConfigRequest]) (*connect.Response[v1.GetEventBusConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.EventBusService.GetEventBusConfig is not implemented"))
}

func (UnimplementedEventBusServiceHandler) UpdateEventBusConfig(context.Context, *connect.Request[v1.UpdateEventBusConfigRequest]) (*connect.Response[v1.Operation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.EventBusService.UpdateEventBusConfig is not implemented"))
}
