// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: metarr/v1/operations.proto

package metarrv1connect

import (
	v1 "Metarr/internal/genproto/metarr/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OperationsServiceName is the fully-qualified name of the OperationsService service.
	OperationsServiceName = "metarr.v1.OperationsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OperationsServiceGetOperationProcedure is the fully-qualified name of the OperationsService's
	// GetOperation RPC.
	OperationsServiceGetOperationProcedure = "/metarr.v1.OperationsService/GetOperation"
	// OperationsServiceListOperationsProcedure is the fully-qualified name of the OperationsService's
	// ListOperations RPC.
	OperationsServiceListOperationsProcedure = "/metarr.v1.OperationsService/ListOperations"
)

// OperationsServiceClient is a client for the metarr.v1.OperationsService service.
type OperationsServiceClient interface {
	GetOperation(context.Context, *connect.Request[v1.GetOperationRequest]) (*connect.Response[v1.Operation], error)
	ListOperations(context.Context, *connect.Request[v1.ListOperationsRequest]) (*connect.Response[v1.ListOperationsResponse], error)
}

// NewOperationsServiceClient constructs a client for the metarr.v1.OperationsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOperationsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OperationsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	operationsServiceMethods := v1.File_metarr_v1_operations_proto.Services().ByName("OperationsService").Methods()
	return &operationsServiceClient{
		getOperation: connect.NewClient[v1.GetOperationRequest, v1.Operation](
			httpClient,
			baseURL+OperationsServiceGetOperationProcedure,
			connect.WithSchema(operationsServiceMethods.ByName("GetOperation")),
			connect.WithClientOptions(opts...),
		),
		listOperations: connect.NewClient[v1.ListOperationsRequest, v1.ListOperationsResponse](
			httpClient,
			baseURL+OperationsServiceListOperationsProcedure,
			connect.WithSchema(operationsServiceMethods.ByName("ListOperations")),
			connect.WithClientOptions(opts...),
		),
	}
}

// operationsServiceClient implements OperationsServiceClient.
type operationsServiceClient struct {
	getOperation   *connect.Client[v1.GetOperationRequest, v1.Operation]
	listOperations *connect.Client[v1.ListOperationsRequest, v1.ListOperationsResponse]
}

// GetOperation calls metarr.v1.OperationsService.GetOperation.
func (c *operationsServiceClient) GetOperation(ctx context.Context, req *connect.Request[v1.GetOperationRequest]) (*connect.Response[v1.Operation], error) {
	return c.getOperation.CallUnary(ctx, req)
}

// ListOperations calls metarr.v1.OperationsService.ListOperations.
func (c *operationsServiceClient) ListOperations(ctx context.Context, req *connect.Request[v1.ListOperationsRequest]) (*connect.Response[v1.ListOperationsResponse], error) {
	return c.listOperations.CallUnary(ctx, req)
}

// OperationsServiceHandler is an implementation of the metarr.v1.OperationsService service.
type OperationsServiceHandler interface {
	GetOperation(context.Context, *connect.Request[v1.GetOperationRequest]) (*connect.Response[v1.Operation], error)
	ListOperations(context.Context, *connect.Request[v1.ListOperationsRequest]) (*connect.Response[v1.ListOperationsResponse], error)
}

// NewOperationsServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOperationsServiceHandler(svc OperationsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	operationsServiceMethods := v1.File_metarr_v1_operations_proto.Services().ByName("OperationsService").Methods()
	operationsServiceGetOperationHandler := connect.NewUnaryHandler(
		OperationsServiceGetOperationProcedure,
		svc.GetOperation,
		connect.WithSchema(operationsServiceMethods.ByName("GetOperation")),
		connect.WithHandlerOptions(opts...),
	)
	operationsServiceListOperationsHandler := connect.NewUnaryHandler(
		OperationsServiceListOperationsProcedure,
		svc.ListOperations,
		connect.WithSchema(operationsServiceMethods.ByName("ListOperations")),
		connect.WithHandlerOptions(opts...),
	)
	return "/metarr.v1.OperationsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OperationsServiceGetOperationProcedure:
			operationsServiceGetOperationHandler.ServeHTTP(w, r)
		case OperationsServiceListOperationsProcedure:
			operationsServiceListOperationsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOperationsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOperationsServiceHandler struct{}

func (UnimplementedOperationsServiceHandler) GetOperation(context.Context, *connect.Request[v1.GetOperationRequest]) (*connect.Response[v1.Operation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.OperationsService.GetOperation is not implemented"))
}

func (UnimplementedOperationsServiceHandler) ListOperations(context.Context, *connect.Request[v1.ListOperationsRequest]) (*connect.Response[v1.ListOperationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.OperationsService.ListOperations is not implemented"))
}
