// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: metarr/v1/stats.proto

package metarrv1connect

import (
	v1 "Metarr/internal/genproto/metarr/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StatsServiceName is the fully-qualified name of the StatsService service.
	StatsServiceName = "metarr.v1.StatsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StatsServiceGetProcedure is the fully-qualified name of the StatsService's Get RPC.
	StatsServiceGetProcedure = "/metarr.v1.StatsService/Get"
	// StatsServiceStreamProcedure is the fully-qualified name of the StatsService's Stream RPC.
	StatsServiceStreamProcedure = "/metarr.v1.StatsService/Stream"
)

// StatsServiceClient is a client for the metarr.v1.StatsService service.
type StatsServiceClient interface {
	Get(context.Context, *connect.Request[v1.StatsServiceGetRequest]) (*connect.Response[v1.StatsServiceGetResponse], error)
	Stream(context.Context, *connect.Request[v1.StatsServiceStreamRequest]) (*connect.ServerStreamForClient[v1.StatsServiceStreamResponse], error)
}

// NewStatsServiceClient constructs a client for the metarr.v1.StatsService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStatsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StatsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	statsServiceMethods := v1.File_metarr_v1_stats_proto.Services().ByName("StatsService").Methods()
	return &statsServiceClient{
		get: connect.NewClient[v1.StatsServiceGetRequest, v1.StatsServiceGetResponse](
			httpClient,
			baseURL+StatsServiceGetProcedure,
			connect.WithSchema(statsServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		stream: connect.NewClient[v1.StatsServiceStreamRequest, v1.StatsServiceStreamResponse](
			httpClient,
			baseURL+StatsServiceStreamProcedure,
			connect.WithSchema(statsServiceMethods.ByName("Stream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// statsServiceClient implements StatsServiceClient.
type statsServiceClient struct {
	get    *connect.Client[v1.StatsServiceGetRequest, v1.StatsServiceGetResponse]
	stream *connect.Client[v1.StatsServiceStreamRequest, v1.StatsServiceStreamResponse]
}

// Get calls metarr.v1.StatsService.Get.
func (c *statsServiceClient) Get(ctx context.Context, req *connect.Request[v1.StatsServiceGetRequest]) (*connect.Response[v1.StatsServiceGetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Stream calls metarr.v1.StatsService.Stream.
func (c *statsServiceClient) Stream(ctx context.Context, req *connect.Request[v1.StatsServiceStreamRequest]) (*connect.ServerStreamForClient[v1.StatsServiceStreamResponse], error) {
	return c.stream.CallServerStream(ctx, req)
}

// StatsServiceHandler is an implementation of the metarr.v1.StatsService service.
type StatsServiceHandler interface {
	Get(context.Context, *connect.Request[v1.StatsServiceGetRequest]) (*connect.Response[v1.StatsServiceGetResponse], error)
	Stream(context.Context, *connect.Request[v1.StatsServiceStreamRequest], *connect.ServerStream[v1.StatsServiceStreamResponse]) error
}

// NewStatsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStatsServiceHandler(svc StatsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	statsServiceMethods := v1.File_metarr_v1_stats_proto.Services().ByName("StatsService").Methods()
	statsServiceGetHandler := connect.NewUnaryHandler(
		StatsServiceGetProcedure,
		svc.Get,
		connect.WithSchema(statsServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	statsServiceStreamHandler := connect.NewServerStreamHandler(
		StatsServiceStreamProcedure,
		svc.Stream,
		connect.WithSchema(statsServiceMethods.ByName("Stream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/metarr.v1.StatsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StatsServiceGetProcedure:
			statsServiceGetHandler.ServeHTTP(w, r)
		case StatsServiceStreamProcedure:
			statsServiceStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStatsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStatsServiceHandler struct{}

func (UnimplementedStatsServiceHandler) Get(context.Context, *connect.Request[v1.StatsServiceGetRequest]) (*connect.Response[v1.StatsServiceGetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.StatsService.Get is not implemented"))
}

func (UnimplementedStatsServiceHandler) Stream(context.Context, *connect.Request[v1.StatsServiceStreamRequest], *connect.ServerStream[v1.StatsServiceStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.StatsService.Stream is not implemented"))
}
