// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: metarr/v1/tasks.proto

package metarrv1connect

import (
	v1 "Metarr/internal/genproto/metarr/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TaskServiceName is the fully-qualified name of the TaskService service.
	TaskServiceName = "metarr.v1.TaskService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TaskServiceRunDirectoryScanProcedure is the fully-qualified name of the TaskService's
	// RunDirectoryScan RPC.
	TaskServiceRunDirectoryScanProcedure = "/metarr.v1.TaskService/RunDirectoryScan"
)

// TaskServiceClient is a client for the metarr.v1.TaskService service.
type TaskServiceClient interface {
	RunDirectoryScan(context.Context, *connect.Request[v1.TaskServiceRunDirectoryScanRequest]) (*connect.Response[v1.TaskServiceRunDirectoryScanResponse], error)
}

// NewTaskServiceClient constructs a client for the metarr.v1.TaskService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaskServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TaskServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	taskServiceMethods := v1.File_metarr_v1_tasks_proto.Services().ByName("TaskService").Methods()
	return &taskServiceClient{
		runDirectoryScan: connect.NewClient[v1.TaskServiceRunDirectoryScanRequest, v1.TaskServiceRunDirectoryScanResponse](
			httpClient,
			baseURL+TaskServiceRunDirectoryScanProcedure,
			connect.WithSchema(taskServiceMethods.ByName("RunDirectoryScan")),
			connect.WithClientOptions(opts...),
		),
	}
}

// taskServiceClient implements TaskServiceClient.
type taskServiceClient struct {
	runDirectoryScan *connect.Client[v1.TaskServiceRunDirectoryScanRequest, v1.TaskServiceRunDirectoryScanResponse]
}

// RunDirectoryScan calls metarr.v1.TaskService.RunDirectoryScan.
func (c *taskServiceClient) RunDirectoryScan(ctx context.Context, req *connect.Request[v1.TaskServiceRunDirectoryScanRequest]) (*connect.Response[v1.TaskServiceRunDirectoryScanResponse], error) {
	return c.runDirectoryScan.CallUnary(ctx, req)
}

// TaskServiceHandler is an implementation of the metarr.v1.TaskService service.
type TaskServiceHandler interface {
	RunDirectoryScan(context.Context, *connect.Request[v1.TaskServiceRunDirectoryScanRequest]) (*connect.Response[v1.TaskServiceRunDirectoryScanResponse], error)
}

// NewTaskServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaskServiceHandler(svc TaskServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	taskServiceMethods := v1.File_metarr_v1_tasks_proto.Services().ByName("TaskService").Methods()
	taskServiceRunDirectoryScanHandler := connect.NewUnaryHandler(
		TaskServiceRunDirectoryScanProcedure,
		svc.RunDirectoryScan,
		connect.WithSchema(taskServiceMethods.ByName("RunDirectoryScan")),
		connect.WithHandlerOptions(opts...),
	)
	return "/metarr.v1.TaskService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TaskServiceRunDirectoryScanProcedure:
			taskServiceRunDirectoryScanHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTaskServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTaskServiceHandler struct{}

func (UnimplementedTaskServiceHandler) RunDirectoryScan(context.Context, *connect.Request[v1.TaskServiceRunDirectoryScanRequest]) (*connect.Response[v1.TaskServiceRunDirectoryScanResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("metarr.v1.TaskService.RunDirectoryScan is not implemented"))
}
