import js from '@eslint/js'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  { ignores: ['dist/**', '.vite/**'] },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      react.configs.flat.recommended,
      reactHooks.configs.flat['recommended-latest'],
    ],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    settings: {
      react: { version: 'detect' },
    },
    plugins: {
      'react-refresh': reactRefresh,
    },
    rules: {
      'react-refresh/only-export-components': 'warn',
      // The JSX transform (tsconfig.json's "jsx": "react-jsx") means React
      // never needs to be in scope for JSX to work.
      'react/react-in-jsx-scope': 'off',
      'react/jsx-uses-react': 'off',
      // TypeScript already enforces this; enabling both just double-reports.
      'react/prop-types': 'off',
      // Icons are CSS classes generated by scripts/generate-icons.mjs, not
      // React components — see lib/icons/typeIcons.css and lib/typeIcons.ts.
      // react-icons is a devDependency used only by that generation script;
      // nothing under src/ may import it.
      'no-restricted-imports': ['error', {
        patterns: [{
          group: ['react-icons', 'react-icons/*'],
          message: 'Icons are CSS classes generated by scripts/generate-icons.mjs, not React components — see lib/icons/typeIcons.css. Never import react-icons under src/.',
        }],
      }],
    },
  },
)
